import { createHash, randomUUID } from "node:crypto";
import { chmod, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import type { DesktopProjectMemoryAddRequest, DesktopProjectMemoryClearResult, DesktopProjectMemoryEntry, DesktopProjectMemoryListRequest, DesktopProjectMemorySource, DesktopProjectMemoryUpdateRequest } from "../api/desktopApi";
import { replaceFileSafely } from "./atomicFileReplace";
import { redactDesktopSecrets } from "./secretRedaction";

type Store = { schemaVersion: 2; workspaces: Record<string, DesktopProjectMemoryEntry[]> };
export class ProjectMemoryStore {
  #queue = Promise.resolve();
  constructor(readonly filePath: string) {}
  list(raw: unknown): Promise<DesktopProjectMemoryEntry[]> { return this.#run(async () => { const request = listRequest(raw); const entries = (await this.#read()).workspaces[key(request.workspacePath)] ?? []; const query = request.query?.toLocaleLowerCase(); return entries.filter((item) => !query || item.content.toLocaleLowerCase().includes(query)).sort(compare).slice(0, request.limit ?? 20); }); }
  add(raw: unknown): Promise<DesktopProjectMemoryEntry> { return this.#run(async () => { const request = addRequest(raw); const store = await this.#read(); const workspaceKey = key(request.workspacePath); const now = new Date().toISOString(); const entry: DesktopProjectMemoryEntry = { id: `memory-${randomUUID()}`, workspacePath: request.workspacePath, content: request.content, source: request.source ?? "manual", createdAt: now, updatedAt: now }; store.workspaces[workspaceKey] = [entry, ...(store.workspaces[workspaceKey] ?? [])].sort(compare).slice(0, 200); await this.#write(store); return entry; }); }
  update(raw: unknown): Promise<DesktopProjectMemoryEntry> { return this.#run(async () => { const request = updateRequest(raw); const store = await this.#read(); const workspaceKey = key(request.workspacePath); const entries = store.workspaces[workspaceKey] ?? []; const index = entries.findIndex((item) => item.id === request.entryId); if (index < 0) throw new Error("Project memory entry was not found."); const updated = { ...entries[index], content: request.content, source: request.source ?? entries[index].source, updatedAt: new Date().toISOString() }; entries[index] = updated; store.workspaces[workspaceKey] = entries.sort(compare); await this.#write(store); return updated; }); }
  clear(raw: unknown): Promise<DesktopProjectMemoryClearResult> { return this.#run(async () => { const request = clearRequest(raw); const store = await this.#read(); const workspaceKey = key(request.workspacePath); const entries = store.workspaces[workspaceKey] ?? []; const next = request.entryId ? entries.filter((item) => item.id !== request.entryId) : []; if (next.length) store.workspaces[workspaceKey] = next; else delete store.workspaces[workspaceKey]; if (next.length !== entries.length) await this.#write(store); return { workspacePath: request.workspacePath, removedCount: entries.length - next.length }; }); }
  async #read(): Promise<Store> { try { const parsed = JSON.parse(await readFile(this.filePath, "utf8")) as { workspaces?: unknown }; const workspaces: Store["workspaces"] = {}; if (parsed.workspaces && typeof parsed.workspaces === "object") for (const [workspaceKey, values] of Object.entries(parsed.workspaces)) if (/^[a-f0-9]{64}$/.test(workspaceKey) && Array.isArray(values)) { const entries = values.filter(isEntry).sort(compare).slice(0, 200); if (entries.length) workspaces[workspaceKey] = entries; } return { schemaVersion: 2, workspaces }; } catch { return { schemaVersion: 2, workspaces: {} }; } }
  async #write(store: Store): Promise<void> { await mkdir(dirname(this.filePath), { recursive: true }); const temporary = `${this.filePath}.${process.pid}.${randomUUID()}.tmp`; try { await writeFile(temporary, `${JSON.stringify({ ...store, schemaVersion: 2 }, null, 2)}\n`, { encoding: "utf8", mode: 0o600 }); await replaceFileSafely(temporary, this.filePath); await chmod(this.filePath, 0o600).catch(() => undefined); } finally { await rm(temporary, { force: true }); } }
  #run<T>(operation: () => Promise<T>): Promise<T> { const run = this.#queue.catch(() => undefined).then(operation); this.#queue = run.then(() => undefined, () => undefined); return run; }
}
function path(value: unknown): string { if (typeof value !== "string" || !value.trim() || value.length > 4096 || /[\r\n\0]/.test(value)) throw new Error("Project memory workspace path is invalid."); return value.trim(); }
function content(value: unknown): string { if (typeof value !== "string" || !value.trim() || value.length > 4000) throw new Error("Project memory content is invalid."); const result = value.trim(); if (redactDesktopSecrets(result) !== result) throw new Error("Project memory must not contain credentials or secrets."); return result; }
function source(value: unknown): DesktopProjectMemorySource | undefined { return value === "manual" || value === "chat_command" || value === "retrospective" ? value : undefined; }
function query(value: unknown): string | undefined { if (value === undefined) return undefined; if (typeof value !== "string" || !value.trim() || value.length > 240 || /[\r\n\0]/.test(value)) throw new Error("Project memory query is invalid."); return value.trim(); }
function limit(value: unknown): number | undefined { return value === undefined ? undefined : Math.max(1, Math.min(100, Math.floor(Number(value) || 20))); }
function id(value: unknown, optional = false): string | undefined { if (value === undefined && optional) return undefined; if (typeof value !== "string" || !/^memory-[A-Za-z0-9-]{36}$/.test(value)) throw new Error("Project memory id is invalid."); return value; }
function listRequest(raw: unknown): DesktopProjectMemoryListRequest { if (!raw || typeof raw !== "object") throw new Error("Project memory list request must be an object."); const value = raw as Record<string, unknown>; return { workspacePath: path(value.workspacePath), limit: limit(value.limit), query: query(value.query) }; }
function addRequest(raw: unknown): DesktopProjectMemoryAddRequest { if (!raw || typeof raw !== "object") throw new Error("Project memory add request must be an object."); const value = raw as Record<string, unknown>; return { workspacePath: path(value.workspacePath), content: content(value.content), source: source(value.source) ?? "manual" }; }
function updateRequest(raw: unknown): DesktopProjectMemoryUpdateRequest { if (!raw || typeof raw !== "object") throw new Error("Project memory update request must be an object."); const value = raw as Record<string, unknown>; return { workspacePath: path(value.workspacePath), entryId: id(value.entryId)!, content: content(value.content), ...(source(value.source) ? { source: source(value.source) } : {}) }; }
function clearRequest(raw: unknown): { workspacePath: string; entryId?: string } { if (!raw || typeof raw !== "object") throw new Error("Project memory clear request must be an object."); const value = raw as Record<string, unknown>; return { workspacePath: path(value.workspacePath), ...(id(value.entryId, true) ? { entryId: id(value.entryId, true) } : {}) }; }
function key(value: string): string { return createHash("sha256").update(value.toLowerCase()).digest("hex"); }
function compare(a: DesktopProjectMemoryEntry, b: DesktopProjectMemoryEntry): number { return b.updatedAt.localeCompare(a.updatedAt); }
function isEntry(value: unknown): value is DesktopProjectMemoryEntry { const item = value as DesktopProjectMemoryEntry; return Boolean(item && /^memory-[A-Za-z0-9-]{36}$/.test(item.id) && typeof item.workspacePath === "string" && typeof item.content === "string" && item.content.length <= 4000 && source(item.source) && typeof item.createdAt === "string" && typeof item.updatedAt === "string"); }
const dataRoot = process.env.DRSAI_HOME?.trim() || join(homedir(), ".drsai"); export const projectMemoryStore = new ProjectMemoryStore(join(dataRoot, "desktop", "project-memory.json"));
export const listProjectMemory = (raw: unknown) => projectMemoryStore.list(raw); export const addProjectMemory = (raw: unknown) => projectMemoryStore.add(raw); export const updateProjectMemory = (raw: unknown) => projectMemoryStore.update(raw); export const clearProjectMemory = (raw: unknown) => projectMemoryStore.clear(raw);
