import { createHash, randomUUID } from "node:crypto";
import { join } from "node:path";
import { homedir } from "node:os";
import { realpath } from "node:fs/promises";
import type { DesktopWorkflowRun, DesktopWorkflowRunRecipe, DesktopWorkflowRunStartResult, DesktopWorkflowRunStep, DesktopWorkflowRunStepCompleteResult, DesktopWorkflowRunStepDispatchResult, DesktopWorkflowRunStepExecution } from "../api/desktopApi";
import { readDurableJson, writeDurableJson } from "./durableJsonStore";
import { redactDesktopSecrets } from "./secretRedaction";
type Store = { schemaVersion: 2; workspaces: Record<string, DesktopWorkflowRun[]> };
const MAX_WORKFLOW_RUN_STORE_BYTES = 32 * 1024 * 1024;
export class WorkflowRunStore {
  #queue = Promise.resolve(); constructor(readonly filePath: string) {}
  list(rawPath?: unknown): Promise<DesktopWorkflowRun[]> { return this.#run(async () => { const path = rawPath === undefined ? undefined : await canonicalWorkspacePath(workspacePath(rawPath)); const store = await this.#read(); return (path ? store.workspaces[key(path)] ?? [] : Object.values(store.workspaces).flat()).filter((run) => !path || run.workspacePath === path).sort(compare).map(clone); }); }
  start(raw: unknown): Promise<DesktopWorkflowRunStartResult> { return this.#run(async () => {
    const recipe = validateRecipe(raw && typeof raw === "object" ? (raw as { recipe?: unknown }).recipe : undefined);
    if (recipe.status !== "ready") throw new Error("Workflow recipe is not approved and ready.");
    const idempotencyKey = raw && typeof raw === "object" ? (raw as { idempotencyKey?: unknown }).idempotencyKey : undefined;
    if (idempotencyKey !== undefined && (typeof idempotencyKey !== "string" || !/^[a-f0-9]{64}$/.test(idempotencyKey))) throw new Error("Workflow run idempotency key is invalid.");
    const store = await this.#read();
    const workspaceKey = key(recipe.workspacePath);
    const existing = idempotencyKey ? (store.workspaces[workspaceKey] ?? []).find((run) => run.recipeId === recipe.id) : undefined;
    if (existing) return startResult(recipe, existing);
    const now = new Date().toISOString();
    const executions = recipe.steps.map((step, index): DesktopWorkflowRunStepExecution => ({ ...step, status: index === 0 ? initialStatus(step) : "pending", message: index === 0 ? initialMessage(step) : "Waiting for the previous workflow step." }));
    const run: DesktopWorkflowRun = { id: `workflow-run-${randomUUID()}`, recipeId: recipe.id, templateId: recipe.templateId, name: recipe.name, ...(recipe.workspacePath ? { workspacePath: recipe.workspacePath } : {}), status: executions[0]?.status === "waiting_approval" ? "waiting_approval" : executions.length ? "running" : "complete", createdAt: now, updatedAt: now, ...(executions[0] ? { currentStepId: executions[0].id } : {}), steps: executions, verification: recipe.verification, message: executions.length ? "Workflow run started." : "Workflow run completed." };
    store.workspaces[workspaceKey] = [run, ...(store.workspaces[workspaceKey] ?? [])].sort(compare).slice(0, 100);
    await this.#write(store);
    return startResult(recipe, run);
  }); }
  dispatch(raw: unknown): Promise<DesktopWorkflowRunStepDispatchResult> { return this.#run(async () => { const request = stepRequest(raw); const store = await this.#read(); const found = find(store, request.runId); if (!found) throw new Error("Workflow run was not found."); const run = clone(found.run); if (run.currentStepId !== request.stepId) throw new Error("Workflow steps must be dispatched in order."); const index = run.steps.findIndex((step) => step.id === request.stepId); const step = run.steps[index]; if (!step) throw new Error("Workflow run step was not found."); if (step.status === "waiting_approval" || step.kind === "approval" || step.kind === "external_runtime") return { run, dispatched: false, kind: step.kind, ...(step.command ? { command: step.command } : {}), requiresApproval: step.requiresApproval, message: step.kind === "external_runtime" ? "External runtime requires explicit provider reconnect." : "Workflow step is waiting for Approval Center." }; if (step.status !== "ready") throw new Error("Workflow run step is not ready."); const now = new Date().toISOString(); const waitsForResult = step.kind === "terminal_command" || step.kind === "chat_command"; run.steps[index] = { ...step, status: waitsForResult ? "running" : "completed", ...(waitsForResult ? {} : { completedAt: now }), message: step.kind === "terminal_command" ? "Terminal command dispatched; waiting for its exit result." : step.kind === "chat_command" ? "Chat command prepared; confirm this step only after the chat action finishes." : "Manual workflow checkpoint confirmed." }; advance(run, now); found.runs[found.index] = run; await this.#write(store); return { run: clone(run), dispatched: true, kind: step.kind, ...(step.command ? { command: step.command } : {}), requiresApproval: step.requiresApproval, message: run.steps[index].message }; }); }
  complete(raw: unknown): Promise<DesktopWorkflowRunStepCompleteResult> { return this.#run(async () => { const request = completeRequest(raw); const store = await this.#read(); const found = find(store, request.runId); if (!found) throw new Error("Workflow run was not found."); const run = clone(found.run); const index = run.steps.findIndex((step) => step.id === request.stepId); const step = run.steps[index]; const completable = step && ((step.kind === "external_runtime" && step.status === "waiting_approval") || ((step.kind === "terminal_command" || step.kind === "chat_command") && step.status === "running")); if (!step || !completable) throw new Error("Only a dispatched terminal/chat step or explicitly reconnected external runtime can be completed."); const now = new Date().toISOString(); const succeeded = request.exitCode === 0; const summary = request.output ? ` Output: ${request.output.replace(/\s+/g, " ").slice(0, 500)}` : ""; const label = step.kind === "terminal_command" ? "Terminal command" : step.kind === "chat_command" ? "Chat action" : "External runtime reconnect"; run.steps[index] = { ...step, status: succeeded ? "completed" : "blocked", ...(succeeded ? { completedAt: now } : {}), message: succeeded ? `${label} completed.${summary}` : `${label} failed with exit code ${request.exitCode}.${summary}` }; advance(run, now); found.runs[found.index] = run; await this.#write(store); return { run: clone(run), completed: succeeded, blocked: !succeeded, message: run.steps[index].message }; }); }
  recover(): Promise<{ recovered: number; runs: DesktopWorkflowRun[] }> { return this.#run(async () => { const store = await this.#read(); const recovered: DesktopWorkflowRun[] = []; const now = new Date().toISOString(); for (const runs of Object.values(store.workspaces)) for (let index = 0; index < runs.length; index += 1) { const run = runs[index]; if (run.status === "complete" || run.status === "blocked") continue; const steps = run.steps.map((step) => step.status === "completed" || step.status === "blocked" ? step : step.status === "waiting_approval" ? { ...step, resumableAfterRestart: false, resumeAction: "wait_approval" as const, resumeMessage: "Approval Center still owns this step.", lastResumedAt: now } : { ...step, status: "ready" as const, resumableAfterRestart: true, resumeAction: step.kind === "terminal_command" ? "prepare_terminal" as const : step.kind === "external_runtime" ? "reconnect_external" as const : step.kind === "manual_review" ? "confirm_manual" as const : "dispatch_chat" as const, resumeMessage: "Explicitly resume this step after restart.", lastResumedAt: now }); const pending = steps.filter((step) => step.status !== "completed"); const next: DesktopWorkflowRun = { ...run, steps, status: pending.some((step) => step.status === "waiting_approval") ? "waiting_approval" : "running", updatedAt: now, currentStepId: pending[0]?.id, resumePlan: { restartDetectedAt: now, pendingStepCount: pending.length, resumableStepIds: pending.filter((step) => step.resumableAfterRestart).map((step) => step.id), waitingApprovalStepIds: pending.filter((step) => step.status === "waiting_approval").map((step) => step.id), message: "Recovered after restart without automatically executing any step." }, message: "Recovered after restart; explicit resume is required." }; runs[index] = next; recovered.push(clone(next)); } if (recovered.length) await this.#write(store); return { recovered: recovered.length, runs: recovered }; }); }
  async #read(): Promise<Store> { return (await readDurableJson(this.filePath, decodeStore, { maxBytes: MAX_WORKFLOW_RUN_STORE_BYTES }))?.value ?? { schemaVersion: 2, workspaces: {} }; }
  async #write(store: Store): Promise<void> { await writeDurableJson(this.filePath, { ...store, schemaVersion: 2 }, { maxBytes: MAX_WORKFLOW_RUN_STORE_BYTES }); }
  #run<T>(operation: () => Promise<T>): Promise<T> { const run = this.#queue.catch(() => undefined).then(operation); this.#queue = run.then(() => undefined, () => undefined); return run; }
}
function startResult(recipe: DesktopWorkflowRunRecipe, run: DesktopWorkflowRun): DesktopWorkflowRunStartResult { return { run: clone(run), chatCommands: recipe.steps.filter((step) => step.kind === "chat_command" && step.command).map((step) => step.command!), terminalCommands: recipe.steps.filter((step) => step.kind === "terminal_command" && step.command).map((step) => step.command!), approvalIds: [], manualCheckpoints: recipe.steps.filter((step) => step.kind === "manual_review").map((step) => step.title) }; }
function workspacePath(value: unknown): string { if (typeof value !== "string" || !value.trim() || value.length > 4096 || /[\r\n\0]/.test(value)) throw new Error("Workflow Workspace path is invalid."); return value.trim(); }
async function canonicalWorkspacePath(value: string): Promise<string> { try { return await realpath(value); } catch { return value; } }
function validateRecipe(value: unknown): DesktopWorkflowRunRecipe { if (!value || typeof value !== "object") throw new Error("Workflow recipe is invalid."); const recipe = value as DesktopWorkflowRunRecipe; if (!/^workflow:[a-z][a-z0-9-]{1,63}:[A-Za-z0-9-]{36}$/.test(recipe.id) || !/^[a-z][a-z0-9-]{1,63}$/.test(recipe.templateId) || typeof recipe.name !== "string" || !recipe.name || !Array.isArray(recipe.steps) || recipe.steps.length > 20 || typeof recipe.verification !== "string") throw new Error("Workflow recipe is invalid."); if (recipe.workspacePath) workspacePath(recipe.workspacePath); const ids = new Set<string>(); for (const step of recipe.steps) { if (!step || !/^[A-Za-z0-9_-]{1,80}$/.test(step.id) || ids.has(step.id) || !["chat_command", "terminal_command", "external_runtime", "manual_review", "approval"].includes(step.kind) || typeof step.title !== "string" || typeof step.detail !== "string" || typeof step.requiresApproval !== "boolean" || (step.command !== undefined && (typeof step.command !== "string" || step.command.length > 1000 || redactDesktopSecrets(step.command) !== step.command))) throw new Error("Workflow recipe step is invalid."); ids.add(step.id); } return structuredClone(recipe); }
function stepRequest(raw: unknown): { runId: string; stepId: string } { if (!raw || typeof raw !== "object") throw new Error("Workflow step request is invalid."); const value = raw as Record<string, unknown>; if (typeof value.runId !== "string" || !/^workflow-run-[A-Za-z0-9-]{36}$/.test(value.runId) || typeof value.stepId !== "string" || !/^[A-Za-z0-9_-]{1,80}$/.test(value.stepId)) throw new Error("Workflow step request is invalid."); return { runId: value.runId, stepId: value.stepId }; }
function completeRequest(raw: unknown): { runId: string; stepId: string; exitCode: number; output?: string } { const base = stepRequest(raw); const value = raw as Record<string, unknown>; if (!Number.isInteger(value.exitCode) || Number(value.exitCode) < -255 || Number(value.exitCode) > 255) throw new Error("Workflow exit code is invalid."); if (value.output !== undefined && (typeof value.output !== "string" || Buffer.byteLength(value.output, "utf8") > 64 * 1024)) throw new Error("Workflow output is invalid or too large."); return { ...base, exitCode: Number(value.exitCode), ...(typeof value.output === "string" ? { output: redactDesktopSecrets(value.output) } : {}) }; }
function initialStatus(step: DesktopWorkflowRunStep): DesktopWorkflowRunStepExecution["status"] { return step.kind === "approval" || step.kind === "external_runtime" ? "waiting_approval" : "ready"; }
function initialMessage(step: DesktopWorkflowRunStep): string { return initialStatus(step) === "waiting_approval" ? "Waiting for explicit approval or provider reconnect." : "Ready to dispatch."; }
function advance(run: DesktopWorkflowRun, now: string): void { const blocked = run.steps.some((step) => step.status === "blocked"); const current = run.steps.find((step) => step.status !== "completed" && step.status !== "blocked"); if (!blocked && current?.status === "pending") { current.status = initialStatus(current); current.message = initialMessage(current); } run.updatedAt = now; run.currentStepId = blocked ? run.steps.find((step) => step.status === "blocked")?.id : current?.id; run.status = blocked ? "blocked" : !current ? "complete" : current.status === "waiting_approval" ? "waiting_approval" : "running"; run.message = run.status === "complete" ? "Workflow run completed." : run.status === "blocked" ? "Workflow run is blocked." : "Workflow run is active."; }
function find(store: Store, id: string): { runs: DesktopWorkflowRun[]; index: number; run: DesktopWorkflowRun } | null { for (const runs of Object.values(store.workspaces)) { const index = runs.findIndex((run) => run.id === id); if (index >= 0) return { runs, index, run: runs[index] }; } return null; }
function key(path?: string): string { return path ? createHash("sha256").update(path.toLowerCase()).digest("hex") : "__global__"; } function compare(a: DesktopWorkflowRun, b: DesktopWorkflowRun): number { return b.updatedAt.localeCompare(a.updatedAt); } function clone(run: DesktopWorkflowRun): DesktopWorkflowRun { return structuredClone(run); }
function isRun(value: unknown): value is DesktopWorkflowRun { const run = value as DesktopWorkflowRun; return Boolean(run && /^workflow-run-[A-Za-z0-9-]{36}$/.test(run.id) && typeof run.recipeId === "string" && typeof run.templateId === "string" && typeof run.name === "string" && ["running", "waiting_approval", "blocked", "complete"].includes(run.status) && Array.isArray(run.steps) && run.steps.length <= 20 && typeof run.createdAt === "string" && typeof run.updatedAt === "string"); }
function decodeStore(value: unknown): Store { if (!value || typeof value !== "object" || !("workspaces" in value) || !value.workspaces || typeof value.workspaces !== "object" || Array.isArray(value.workspaces)) throw new Error("Workflow run store schema is invalid."); const workspaces: Store["workspaces"] = {}; for (const [workspaceKey, values] of Object.entries(value.workspaces)) if (/^(?:[a-f0-9]{64}|__global__)$/.test(workspaceKey) && Array.isArray(values)) { const runs = values.filter(isRun).slice(0, 100); if (runs.length) workspaces[workspaceKey] = runs; } return { schemaVersion: 2, workspaces }; }
const root = join(process.env.DRSAI_HOME?.trim() || join(homedir(), ".drsai"), "desktop"); export const workflowRunStore = new WorkflowRunStore(join(root, "workflow-runs.json"));
export const startWorkflowRun = (raw: unknown) => workflowRunStore.start(raw); export const listWorkflowRuns = (path?: unknown) => workflowRunStore.list(path); export const dispatchWorkflowRunStep = (raw: unknown) => workflowRunStore.dispatch(raw); export const completeWorkflowRunStep = (raw: unknown) => workflowRunStore.complete(raw); export const recoverWorkflowRunsAfterRestart = () => workflowRunStore.recover();
