import { useEffect,useMemo,useRef,useState,useSyncExternalStore } from "react";
import { Bug,CirclePause,CirclePlay,Download,Search,Trash2 } from "lucide-react";
import { clearDebugLogs,getDebugLogs,subscribeDebugLogs,type DebugLogLevel } from "../debugLogStore";
import type { AppLanguage } from "../navigation";
export function DebugPanel({language}:{language:AppLanguage}):React.JSX.Element {
 const logs=useSyncExternalStore(subscribeDebugLogs,getDebugLogs),[visible,setVisible]=useState(logs),[paused,setPaused]=useState(false),[query,setQuery]=useState(""),[levels,setLevels]=useState<Set<DebugLogLevel>>(new Set(["log","info","warn","error"])),outputRef=useRef<HTMLDivElement|null>(null),zh=language==="zh";
 useEffect(()=>{if(!paused)setVisible(logs);},[logs,paused]);
 const filtered=useMemo(()=>visible.filter((entry)=>levels.has(entry.level)&&entry.message.toLowerCase().includes(query.toLowerCase())),[visible,levels,query]);
 useEffect(()=>outputRef.current?.scrollTo({top:outputRef.current.scrollHeight}),[filtered.length]);
 const toggle=(level:DebugLogLevel)=>setLevels((current)=>{const next=new Set(current);next.has(level)?next.delete(level):next.add(level);return next;});
 const exportLogs=()=>{const text=filtered.map((entry)=>`${new Date(entry.timestamp).toISOString()} [${entry.level.toUpperCase()}] ${entry.message}`).join("\n"),url=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`opendrsai-debug-${Date.now()}.log`;link.click();URL.revokeObjectURL(url);};
 return <section className="debug-panel" aria-label={zh?"调试输出":"Debug output"}><header className="debug-panel-header"><div><Bug size={16}/><strong>{zh?"调试输出":"Debug output"}</strong><span>{visible.length}</span></div><div className="debug-panel-actions"><button onClick={()=>setPaused(!paused)} title={paused?(zh?"继续":"Resume"):(zh?"暂停":"Pause")}>{paused?<CirclePlay size={15}/>:<CirclePause size={15}/>}</button><button onClick={exportLogs} title={zh?"导出日志":"Export logs"}><Download size={15}/></button><button onClick={()=>{clearDebugLogs();setVisible([]);}} title={zh?"清空":"Clear"}><Trash2 size={15}/></button></div></header><div className="debug-filter-bar"><label><Search size={14}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={zh?"筛选调试信息":"Filter debug output"}/></label><div>{(["log","info","warn","error"] as DebugLogLevel[]).map((level)=><button key={level} className={levels.has(level)?`active ${level}`:""} onClick={()=>toggle(level)}>{level}</button>)}</div></div><div className="debug-output" ref={outputRef} role="log">{filtered.length?filtered.map((entry)=><article key={entry.id} className={`debug-entry ${entry.level}`}><time>{new Date(entry.timestamp).toLocaleTimeString()}</time><span>{entry.source}</span><pre>{entry.message}</pre></article>):<div className="debug-empty">{zh?"暂无匹配的调试信息":"No matching debug output"}</div>}</div><footer>{paused?(zh?"输出已暂停":"Output paused"):(zh?"实时捕获 renderer 输出":"Capturing renderer output live")}</footer></section>;
}
