"""Generated by generate_codex_stable_contract.py; DO NOT EDIT."""

CONTRACT_VERSION = 5
CONTRACT_DIGEST = '65f598e91ef0c3539570cd654d70a30f9cb50444be1cb9a2e4f71f4f8f27d605'
GENERATED_BASELINE = {
    'codexVersion': '0.147.0-alpha.6.6',
    'schemaPath': 'cores/protocol/codex-app-server/0.147.0-alpha.6.6',
    'v2BundleCanonicalSha256': '80cecd56a6883f2c9c39580122f2adc08b7cc0ad1f24705fd7d917c1651d598c',
}
REVIEWED_COMPATIBLE_VERSIONS = frozenset({
    '0.142.5',
    '0.144.5',
    '0.146.0-alpha.9.2',
    '0.147.0-alpha.1.2',
})
REVIEWED_SCHEMA_SHA256 = {
    '0.142.5': '7e164fed2c3d3de0e6c3520d42e6d53f1433937b41a950e1b44f72172a3d2086',
    '0.144.5': '0da5949167c30a09e459d94559e1ada6910d6ca503a5b5f0e09c0f8eae5ae931',
    '0.146.0-alpha.9.2': 'aaa61aa4ab9794bc80405177e86ecdd3afd4f152fc4fd5dd92ef23babaf9f4f1',
    '0.147.0-alpha.1.2': 'e8b1a177553c52620c4735ebd890578dd5333803428af73d33ef02edf02a43ff',
    '0.147.0-alpha.6.6': '7d79fe309dd7520843459070f3884ecf0e39cee2620c1c49aad6efb4eca76ecb',
}
SEMANTIC_DISPOSITIONS = {
    'hook/completed': {
    'disposition': 'mapped',
    'handler': 'hook_lifecycle',
    'oaep': 'interaction.completed',
    'reason': 'Expose the reviewed hook result in the processing timeline.',
},
    'hook/started': {
    'disposition': 'mapped',
    'handler': 'hook_lifecycle',
    'oaep': 'interaction.started',
    'reason': 'Expose the reviewed hook start in the processing timeline.',
},
    'item/agentMessage/delta': {
    'disposition': 'mapped',
    'handler': 'item_delta',
    'oaep': 'message.text.append',
    'reason': 'Stream assistant message text.',
},
    'item/commandExecution/outputDelta': {
    'disposition': 'mapped',
    'handler': 'item_delta',
    'oaep': 'command.output.append',
    'reason': 'Stream command output.',
},
    'item/commandExecution/terminalInteraction': {
    'disposition': 'mapped',
    'handler': 'terminal_interaction',
    'oaep': 'command.updated',
    'reason': 'Report terminal interaction without retaining stdin content.',
},
    'item/completed': {
    'disposition': 'mapped',
    'handler': 'item_lifecycle',
    'oaep': 'item.completed',
    'reason': 'Complete the typed OAEP item.',
},
    'item/fileChange/outputDelta': {
    'disposition': 'reviewed_ignored',
    'handler': 'deprecated_file_output',
    'oaep': 'none',
    'reason': 'The reviewed Codex schema marks this legacy notification as no longer emitted; patchUpdated and item lifecycle are authoritative.',
},
    'item/fileChange/patchUpdated': {
    'disposition': 'mapped',
    'handler': 'file_patch_updated',
    'oaep': 'file_change.updated',
    'reason': 'Update the structured file-change item.',
},
    'item/mcpToolCall/progress': {
    'disposition': 'mapped',
    'handler': 'item_delta',
    'oaep': 'tool.output.append',
    'reason': 'Stream public MCP progress text.',
},
    'item/plan/delta': {
    'disposition': 'mapped',
    'handler': 'item_delta',
    'oaep': 'plan.text.append',
    'reason': 'Stream plan text.',
},
    'item/reasoning/summaryPartAdded': {
    'disposition': 'mapped',
    'handler': 'item_delta',
    'oaep': 'reasoning.segment.added',
    'reason': 'Create a public reasoning-summary segment.',
},
    'item/reasoning/summaryTextDelta': {
    'disposition': 'mapped',
    'handler': 'item_delta',
    'oaep': 'reasoning.text.append',
    'reason': 'Stream public reasoning-summary text.',
},
    'item/reasoning/textDelta': {
    'disposition': 'mapped',
    'handler': 'item_delta',
    'oaep': 'reasoning.text.append',
    'reason': 'Stream only backend-provided visible reasoning text under OAEP visibility policy.',
},
    'item/started': {
    'disposition': 'mapped',
    'handler': 'item_lifecycle',
    'oaep': 'item.started',
    'reason': 'Start the typed OAEP item.',
},
    'thread/archived': {
    'disposition': 'mapped',
    'handler': 'thread_lifecycle',
    'oaep': 'session.archived',
    'reason': 'Synchronize archive state.',
},
    'thread/closed': {
    'disposition': 'mapped',
    'handler': 'thread_lifecycle',
    'oaep': 'session.updated',
    'reason': 'Expose a closed backend thread without treating it as deletion.',
},
    'thread/deleted': {
    'disposition': 'mapped',
    'handler': 'thread_lifecycle',
    'oaep': 'session.deleted',
    'reason': 'Synchronize deletion state.',
},
    'thread/started': {
    'disposition': 'mapped',
    'handler': 'thread_lifecycle',
    'oaep': 'session.created',
    'reason': 'Bind the created backend thread.',
},
    'thread/unarchived': {
    'disposition': 'mapped',
    'handler': 'thread_lifecycle',
    'oaep': 'session.unarchived',
    'reason': 'Synchronize unarchive state.',
},
    'turn/completed': {
    'disposition': 'mapped',
    'handler': 'turn_lifecycle',
    'oaep': 'run.terminal',
    'reason': 'Finalize the backend turn once.',
},
    'turn/diff/updated': {
    'disposition': 'mapped',
    'handler': 'turn_diff_updated',
    'oaep': 'file_change.updated',
    'reason': 'Expose the latest reviewed turn-level unified diff.',
},
    'turn/plan/updated': {
    'disposition': 'mapped',
    'handler': 'plan_updated',
    'oaep': 'plan.updated',
    'reason': 'Update structured plan steps.',
},
    'turn/started': {
    'disposition': 'mapped',
    'handler': 'turn_lifecycle',
    'oaep': 'run.started',
    'reason': 'Bind the backend turn to the Runtime run.',
},
}
CLIENT_METHOD_PARAMS = {
    'account/login/cancel': frozenset({
    'loginId',
}),
    'account/login/start': frozenset({
    'type',
}),
    'account/logout': frozenset({

}),
    'account/read': frozenset({
    'refreshToken',
}),
    'initialize': frozenset({
    'capabilities',
    'clientInfo',
}),
    'initialized': frozenset({

}),
    'model/list': frozenset({
    'cursor',
    'includeHidden',
    'limit',
}),
    'thread/archive': frozenset({
    'threadId',
}),
    'thread/list': frozenset({
    'archived',
    'cursor',
    'cwd',
    'limit',
    'modelProviders',
    'searchTerm',
    'sectionId',
    'sortDirection',
    'sortKey',
    'sourceKinds',
    'useStateDbOnly',
}),
    'thread/read': frozenset({
    'includeTurns',
    'threadId',
}),
    'thread/resume': frozenset({
    'approvalPolicy',
    'approvalsReviewer',
    'baseInstructions',
    'config',
    'cwd',
    'developerInstructions',
    'model',
    'modelProvider',
    'personality',
    'sandbox',
    'serviceTier',
    'threadId',
}),
    'thread/start': frozenset({
    'approvalPolicy',
    'approvalsReviewer',
    'baseInstructions',
    'config',
    'cwd',
    'developerInstructions',
    'ephemeral',
    'model',
    'modelProvider',
    'personality',
    'sandbox',
    'serviceName',
    'serviceTier',
    'sessionStartSource',
    'threadSource',
}),
    'thread/unarchive': frozenset({
    'threadId',
}),
    'turn/interrupt': frozenset({
    'threadId',
    'turnId',
}),
    'turn/start': frozenset({
    'approvalPolicy',
    'approvalsReviewer',
    'clientUserMessageId',
    'cwd',
    'effort',
    'input',
    'model',
    'outputSchema',
    'personality',
    'sandboxPolicy',
    'serviceTier',
    'summary',
    'threadId',
}),
}
CLIENT_REQUIRED_PARAMS = {
    'account/login/cancel': frozenset({
    'loginId',
}),
    'account/login/start': frozenset({

}),
    'account/logout': frozenset({

}),
    'account/read': frozenset({

}),
    'initialize': frozenset({
    'clientInfo',
}),
    'initialized': frozenset({

}),
    'model/list': frozenset({

}),
    'thread/archive': frozenset({
    'threadId',
}),
    'thread/list': frozenset({

}),
    'thread/read': frozenset({
    'threadId',
}),
    'thread/resume': frozenset({
    'threadId',
}),
    'thread/start': frozenset({

}),
    'thread/unarchive': frozenset({
    'threadId',
}),
    'turn/interrupt': frozenset({
    'threadId',
    'turnId',
}),
    'turn/start': frozenset({
    'input',
    'threadId',
}),
}

CLIENT_METHODS = frozenset({
    'account/login/cancel',
    'account/login/start',
    'account/logout',
    'account/read',
    'initialize',
    'initialized',
    'model/list',
    'thread/archive',
    'thread/list',
    'thread/read',
    'thread/resume',
    'thread/start',
    'thread/unarchive',
    'turn/interrupt',
    'turn/start',
})

SERVER_REQUESTS = frozenset({
    'item/commandExecution/requestApproval',
    'item/fileChange/requestApproval',
    'item/permissions/requestApproval',
})

SEMANTIC_NOTIFICATIONS = frozenset({
    'hook/completed',
    'hook/started',
    'item/agentMessage/delta',
    'item/commandExecution/outputDelta',
    'item/commandExecution/terminalInteraction',
    'item/completed',
    'item/fileChange/outputDelta',
    'item/fileChange/patchUpdated',
    'item/mcpToolCall/progress',
    'item/plan/delta',
    'item/reasoning/summaryPartAdded',
    'item/reasoning/summaryTextDelta',
    'item/reasoning/textDelta',
    'item/started',
    'thread/archived',
    'thread/closed',
    'thread/deleted',
    'thread/started',
    'thread/unarchived',
    'turn/completed',
    'turn/diff/updated',
    'turn/plan/updated',
    'turn/started',
})

USER_NOTICE_NOTIFICATIONS = frozenset({
    'configWarning',
    'deprecationNotice',
    'guardianWarning',
    'model/rerouted',
    'model/safetyBuffering/updated',
    'model/verification',
    'thread/compacted',
    'warning',
    'windows/worldWritableWarning',
})

DIAGNOSTIC_NOTIFICATIONS = frozenset({
    'account/rateLimits/updated',
    'command/exec/outputDelta',
    'item/autoApprovalReview/completed',
    'item/autoApprovalReview/started',
    'mcpServer/startupStatus/updated',
    'process/exited',
    'process/outputDelta',
    'serverRequest/resolved',
    'thread/tokenUsage/updated',
    'turn/moderationMetadata',
    'windowsSandbox/setupCompleted',
})

KNOWN_IGNORED_NOTIFICATIONS = frozenset({
    'account/login/completed',
    'account/updated',
    'app/list/updated',
    'externalAgentConfig/import/completed',
    'externalAgentConfig/import/progress',
    'fs/changed',
    'fuzzyFileSearch/sessionCompleted',
    'fuzzyFileSearch/sessionUpdated',
    'mcpServer/oauthLogin/completed',
    'remoteControl/status/changed',
    'skills/changed',
    'thread/environment/connected',
    'thread/environment/disconnected',
    'thread/goal/cleared',
    'thread/goal/updated',
    'thread/name/updated',
    'thread/realtime/closed',
    'thread/realtime/error',
    'thread/realtime/itemAdded',
    'thread/realtime/outputAudio/delta',
    'thread/realtime/sdp',
    'thread/realtime/started',
    'thread/realtime/transcript/delta',
    'thread/realtime/transcript/done',
    'thread/settings/updated',
    'thread/status/changed',
})

FATAL_NOTIFICATIONS = frozenset({
    'error',
})

LEGACY_NOTIFICATIONS = frozenset({
    'appServer/fatal',
})

STABLE_NOTIFICATIONS = (
    SEMANTIC_NOTIFICATIONS | USER_NOTICE_NOTIFICATIONS | DIAGNOSTIC_NOTIFICATIONS
    | KNOWN_IGNORED_NOTIFICATIONS | SERVER_REQUESTS | FATAL_NOTIFICATIONS | LEGACY_NOTIFICATIONS
)
