"""Unified user model-provider configuration for OpenDrSai."""

from .loader import ConfigError, load_user_config
from .connectivity import test_provider_connection
from .credentials import credential_available, delete_credential, resolve_credential, store_credential
from .credential_lifecycle import cleanup_orphaned_credentials, scan_orphaned_credentials
from .provider_registry import builtin_provider_names
from .probe import ProviderDraft, probe_provider_draft
from .provider_presets import get_provider_preset, list_provider_presets
from .model_discovery import cached_provider_model_catalog, clear_model_discovery_cache, discover_provider_models
from .model_operation_routing import (
    AgentModelRole,
    ModelOperationRoute,
    ModelOperationRoutePlan,
    ModelOperationRoutingError,
    OperationProtocol,
    ResolvedAgentOperation,
    default_operation_routes,
    resolve_agent_operation,
)
from .agent_model_policy import (
    AgentKnowledgePolicy,
    AgentModelPolicyConflict,
    AgentModelPolicySnapshot,
    AgentRuntimePolicySnapshot,
    AgentSkillPolicy,
    AgentToolPolicy,
    agent_model_policy_path,
    canonical_agent_name,
    commit_agent_model_policy,
    commit_agent_runtime_policy,
    current_agent_name,
    list_agent_names,
    load_agent_descriptor,
    load_agent_model_policy,
    load_agent_runtime_policy,
)
from .probe_history import clear_probe_history, latest_probe_result, probe_fingerprint, reload_probe_history
from .telemetry import clear_telemetry, telemetry_snapshot
from .doctor import diagnose_model_config
from .guidance import guidance_for
from .revisions import config_revision
from .service import (
    ConfigCommitResult,
    ConfigConflict,
    ConfigPreview,
    ConfigSnapshot,
    ConfigUpdateRequest,
    commit_update,
    preview_update,
    restore_last_known_good,
    last_known_good_path,
    load_config_snapshot,
)
from .migration import MigrationResult, migrate_legacy_model_config
from .desktop_bootstrap import DesktopBootstrapResult, ensure_desktop_runtime_config
from .resolver import resolve_model_config, resolve_model_ref
from .writer import delete_provider, remove_legacy_model_selection, update_current_agent, update_model_selection, upsert_provider
from .schema import (
    DrSaiConfig,
    ModelCapabilities,
    ProviderConfig,
    ReasoningCapabilities,
    ResolvedModelConfig,
    SecretValue,
)
from .tool_registry import (
    ToolResource,
    ResolvedToolSet,
    canonical_tool_id,
    delete_tool_resource,
    get_tool_resource,
    legacy_tool_id,
    list_tool_resources,
    put_tool_resource,
    merge_tool_secret_placeholders,
    resolve_tool_config,
    resolve_tool_set,
    tool_resource_payload,
)
from .knowledge_registry import (
    KnowledgeEvidence,
    KnowledgeResource,
    canonical_knowledge_id,
    delete_knowledge_resource,
    get_knowledge_resource,
    index_local_files,
    knowledge_resource_payload,
    knowledge_registry_revision,
    knowledge_status,
    list_knowledge_resources,
    put_knowledge_resource,
    search_local_knowledge,
)
from .perceptor_registry import (
    PERCEPTOR_SECRET_PLACEHOLDER,
    PerceptorResource,
    canonical_perceptor_id,
    delete_perceptor_resource,
    get_perceptor_resource,
    list_perceptor_resources,
    merge_perceptor_secret_placeholders,
    perceptor_revision,
    public_perceptor_payload,
    put_perceptor_resource,
    resolve_perceptor_config,
)

__all__ = [
    "ConfigError",
    "DrSaiConfig",
    "ModelCapabilities",
    "MigrationResult",
    "DesktopBootstrapResult",
    "ProviderConfig",
    "ReasoningCapabilities",
    "ResolvedModelConfig",
    "SecretValue",
    "load_user_config",
    "migrate_legacy_model_config",
    "ensure_desktop_runtime_config",
    "resolve_model_config",
    "resolve_model_ref",
    "delete_provider",
    "remove_legacy_model_selection",
    "update_model_selection",
    "upsert_provider",
    "test_provider_connection",
    "store_credential",
    "resolve_credential",
    "delete_credential",
    "credential_available",
    "builtin_provider_names",
    "config_revision",
    "ConfigCommitResult",
    "ConfigConflict",
    "ConfigPreview",
    "ConfigSnapshot",
    "ConfigUpdateRequest",
    "commit_update",
    "preview_update",
    "ProviderDraft",
    "probe_provider_draft",
    "diagnose_model_config",
    "guidance_for",
    "restore_last_known_good",
    "last_known_good_path",
    "load_config_snapshot",
    "get_provider_preset",
    "list_provider_presets",
    "discover_provider_models",
    "cached_provider_model_catalog",
    "clear_model_discovery_cache",
    "AgentModelRole",
    "ModelOperationRoute",
    "ModelOperationRoutePlan",
    "ModelOperationRoutingError",
    "OperationProtocol",
    "ResolvedAgentOperation",
    "default_operation_routes",
    "resolve_agent_operation",
    "AgentModelPolicyConflict",
    "AgentModelPolicySnapshot",
    "AgentToolPolicy",
    "AgentSkillPolicy",
    "AgentKnowledgePolicy",
    "AgentRuntimePolicySnapshot",
    "agent_model_policy_path",
    "canonical_agent_name",
    "commit_agent_model_policy",
    "commit_agent_runtime_policy",
    "current_agent_name",
    "list_agent_names",
    "load_agent_descriptor",
    "load_agent_model_policy",
    "load_agent_runtime_policy",
    "update_current_agent",
    "scan_orphaned_credentials",
    "cleanup_orphaned_credentials",
    "latest_probe_result",
    "probe_fingerprint",
    "reload_probe_history",
    "clear_probe_history",
    "telemetry_snapshot",
    "clear_telemetry",
    "ToolResource",
    "ResolvedToolSet",
    "canonical_tool_id",
    "legacy_tool_id",
    "list_tool_resources",
    "get_tool_resource",
    "put_tool_resource",
    "merge_tool_secret_placeholders",
    "resolve_tool_config",
    "resolve_tool_set",
    "delete_tool_resource",
    "tool_resource_payload",
    "KnowledgeEvidence",
    "KnowledgeResource",
    "canonical_knowledge_id",
    "list_knowledge_resources",
    "get_knowledge_resource",
    "put_knowledge_resource",
    "delete_knowledge_resource",
    "knowledge_resource_payload",
    "knowledge_registry_revision",
    "knowledge_status",
    "index_local_files",
    "search_local_knowledge",
    "PERCEPTOR_SECRET_PLACEHOLDER",
    "PerceptorResource",
    "canonical_perceptor_id",
    "delete_perceptor_resource",
    "get_perceptor_resource",
    "list_perceptor_resources",
    "merge_perceptor_secret_placeholders",
    "perceptor_revision",
    "public_perceptor_payload",
    "put_perceptor_resource",
    "resolve_perceptor_config",
]
