import type { BrowserActionMode } from "./types";

export const LINK_NAVIGATION_MESSAGE = "__OPENDRSAI_BROWSER_NAVIGATE__";

export const LINK_NAVIGATION_SCRIPT = [
  "(() => {",
  "  if (window.__opendrsaiLinkRouterInstalled) return 'already-installed';",
  "  window.__opendrsaiLinkRouterInstalled = true;",
  `  const bridgePrefix = ${JSON.stringify(LINK_NAVIGATION_MESSAGE)};`,
  "  const navigable = (rawUrl) => {",
  "    try {",
  "      const url = new URL(rawUrl, location.href);",
  "      if (!['http:', 'https:'].includes(url.protocol)) return '';",
  "      return url.href;",
  "    } catch {",
  "      return '';",
  "    }",
  "  };",
  "  const requestNewTab = (rawUrl, source) => {",
  "    const url = navigable(rawUrl);",
  "    if (!url) return null;",
  "    console.info(bridgePrefix + JSON.stringify({ url, disposition: 'new-tab', source }));",
  "    return window;",
  "  };",
  "  const nativeOpen = window.open?.bind(window);",
  "  window.open = (rawUrl, target, features) => {",
  "    if (typeof rawUrl === 'string' && rawUrl.trim()) return requestNewTab(rawUrl, 'window.open');",
  "    return nativeOpen ? nativeOpen(rawUrl, target, features) : null;",
  "  };",
  "  document.addEventListener('click', (event) => {",
  "    if (event.defaultPrevented || event.button !== 0) return;",
  "    const anchor = event.target?.closest?.('a[href]');",
  "    if (!anchor) return;",
  "    if (anchor.hasAttribute('download')) return;",
  "    const href = navigable(anchor.href || anchor.getAttribute('href'));",
  "    if (!href) return;",
  "    const target = (anchor.getAttribute('target') || '').toLowerCase();",
  "    const opensNewContext = target === '_blank' || event.metaKey || event.ctrlKey || event.shiftKey;",
  "    if (!opensNewContext) return;",
  "    event.preventDefault();",
  "    event.stopPropagation();",
  "    requestNewTab(href, target || 'modified-click');",
  "  }, true);",
  "  return 'installed';",
  "})()",
].join("\n");

export const READ_TEXT_SCRIPT = [
  "(() => {",
  '  const text = document.body?.innerText || "";',
  '  return text.replace(/\\n{3,}/g, "\\n\\n").trim().slice(0, 12000);',
  "})()",
].join("\n");

export const SNAPSHOT_SCRIPT = [
  "(() => {",
  "  const textOf = (node) => (node?.innerText || node?.textContent || node?.getAttribute?.('aria-label') || '').trim();",
  "  const cssEscape = (value) => window.CSS?.escape ? window.CSS.escape(value) : String(value).replace(/\"/g, '\\\\\"');",
  "  const selectorFor = (node) => {",
  "    if (node.id) return '#' + cssEscape(node.id);",
  "    const name = node.getAttribute('name');",
  "    if (name) return node.tagName.toLowerCase() + '[name=\"' + cssEscape(name) + '\"]';",
  "    const label = node.getAttribute('aria-label');",
  "    if (label) return node.tagName.toLowerCase() + '[aria-label=\"' + cssEscape(label) + '\"]';",
  "    const parts = [];",
  "    let current = node;",
  "    while (current && current.nodeType === Node.ELEMENT_NODE && parts.length < 4) {",
  "      const parent = current.parentElement;",
  "      const tag = current.tagName.toLowerCase();",
  "      if (!parent) { parts.unshift(tag); break; }",
  "      const index = Array.from(parent.children).filter((item) => item.tagName === current.tagName).indexOf(current) + 1;",
  "      parts.unshift(tag + ':nth-of-type(' + index + ')');",
  "      current = parent;",
  "    }",
  "    return parts.join(' > ');",
  "  };",
  "  const values = (selector) => Array.from(document.querySelectorAll(selector)).map(textOf).filter(Boolean).slice(0, 60);",
  "  const elements = Array.from(document.querySelectorAll('a[href],button,[role=button],input,textarea,select,[contenteditable=true],h1,h2,h3')).slice(0, 80).map((node) => {",
  "    const rect = node.getBoundingClientRect();",
  "    const style = getComputedStyle(node);",
  "    return { selector: selectorFor(node), tag: node.tagName.toLowerCase(), role: node.getAttribute('role') || node.getAttribute('type') || '', text: textOf(node).slice(0, 180), rect: { x: Math.round(rect.x), y: Math.round(rect.y), width: Math.round(rect.width), height: Math.round(rect.height) }, styles: { display: style.display, visibility: style.visibility, color: style.color, backgroundColor: style.backgroundColor, fontSize: style.fontSize } };",
  "  });",
  "  return {",
  "    title: document.title || '',",
  "    url: location.href,",
  "    viewport: { width: innerWidth, height: innerHeight, scrollX, scrollY },",
  "    visibleText: (document.body?.innerText || '').replace(/\\n{3,}/g, '\\n\\n').trim().slice(0, 16000),",
  "    structure: {",
  "      headings: values('h1,h2,h3,[role=heading]'),",
  "      buttons: values('button,[role=button]'),",
  "      links: Array.from(document.querySelectorAll('a[href]')).map((node) => { const label = textOf(node); const href = node.getAttribute('href') || ''; return label ? label + ' (' + href + ')' : href; }).filter(Boolean).slice(0, 60),",
  "      inputs: Array.from(document.querySelectorAll('input,textarea,select,[contenteditable=true]')).map((node) => { const label = node.getAttribute('aria-label') || node.getAttribute('placeholder') || node.getAttribute('name') || node.id || node.tagName.toLowerCase(); const type = node.getAttribute('type') || node.tagName.toLowerCase(); return label + ' [' + type + '] ' + selectorFor(node); }).filter(Boolean).slice(0, 60),",
  "      elements,",
  "    },",
  "    resources: performance.getEntriesByType('resource').slice(-40).map((item) => ({ name: item.name, type: item.initiatorType || 'resource', duration: Math.round(item.duration) })),",
  "  };",
  "})()",
].join("\n");

export const PICK_ELEMENT_SCRIPT = [
  "new Promise((resolve) => {",
  "  const previous = { outline: null, node: null };",
  "  const cssEscape = (value) => window.CSS?.escape ? window.CSS.escape(value) : String(value).replace(/\"/g, '\\\\\"');",
  "  const selectorFor = (node) => {",
  "    if (node.id) return '#' + cssEscape(node.id);",
  "    const name = node.getAttribute('name');",
  "    if (name) return node.tagName.toLowerCase() + '[name=\"' + cssEscape(name) + '\"]';",
  "    const label = node.getAttribute('aria-label');",
  "    if (label) return node.tagName.toLowerCase() + '[aria-label=\"' + cssEscape(label) + '\"]';",
  "    const parts = [];",
  "    let current = node;",
  "    while (current && current.nodeType === Node.ELEMENT_NODE && parts.length < 4) {",
  "      const parent = current.parentElement;",
  "      const tag = current.tagName.toLowerCase();",
  "      if (!parent) { parts.unshift(tag); break; }",
  "      const index = Array.from(parent.children).filter((item) => item.tagName === current.tagName).indexOf(current) + 1;",
  "      parts.unshift(tag + ':nth-of-type(' + index + ')');",
  "      current = parent;",
  "    }",
  "    return parts.join(' > ');",
  "  };",
  "  const cleanup = () => { document.removeEventListener('mouseover', over, true); document.removeEventListener('click', click, true); if (previous.node) previous.node.style.outline = previous.outline || ''; };",
  "  const over = (event) => { const node = event.target; if (previous.node && previous.node !== node) previous.node.style.outline = previous.outline || ''; previous.node = node; previous.outline = node.style.outline; node.style.outline = '2px solid #8b5cf6'; };",
  "  const click = (event) => { event.preventDefault(); event.stopPropagation(); const selector = selectorFor(event.target); cleanup(); resolve(selector); };",
  "  document.addEventListener('mouseover', over, true);",
  "  document.addEventListener('click', click, true);",
  "  setTimeout(() => { cleanup(); resolve(''); }, 15000);",
  "})",
].join("\n");

export function createActionScript(mode: BrowserActionMode, selector: string, text: string, key: string): string {
  return [
    "(() => {",
    `  const mode = ${JSON.stringify(mode)};`,
    `  const selector = ${JSON.stringify(selector)};`,
    `  const text = ${JSON.stringify(text)};`,
    `  const key = ${JSON.stringify(key)};`,
    "  const find = () => selector ? document.querySelector(selector) : null;",
    "  if (mode === 'assert_text') { const source = selector ? (find()?.innerText || find()?.textContent || '') : (document.body?.innerText || ''); return source.includes(text) ? 'Assertion passed.' : 'Assertion failed: text not found.'; }",
    "  if (mode === 'wait_for') { const start = Date.now(); return new Promise((resolve) => { const tick = () => { if (find()) { resolve('Wait complete: selector found.'); return; } if (Date.now() - start > 5000) { resolve('Wait timed out: selector not found.'); return; } setTimeout(tick, 100); }; tick(); }); }",
    "  const node = find();",
    "  if (!node) return 'No element matched the selector.';",
    "  node.scrollIntoView({ block: 'center', inline: 'center' });",
    "  node.focus();",
    "  if (mode === 'click') { const rect = node.getBoundingClientRect(); const options = { bubbles: true, cancelable: true, view: window, clientX: rect.left + rect.width / 2, clientY: rect.top + rect.height / 2 }; node.dispatchEvent(new PointerEvent('pointerdown', options)); node.dispatchEvent(new MouseEvent('mousedown', options)); node.dispatchEvent(new PointerEvent('pointerup', options)); node.dispatchEvent(new MouseEvent('mouseup', options)); node.click(); return 'Approved click executed.'; }",
    "  if (mode === 'type') { if ('value' in node) node.value = text; else if (node.isContentEditable) node.textContent = text; else return 'Matched element is not editable.'; node.dispatchEvent(new InputEvent('input', { bubbles: true, inputType: 'insertText', data: text })); node.dispatchEvent(new Event('change', { bubbles: true })); return 'Approved type action executed.'; }",
    "  if (mode === 'select') { if (!('value' in node)) return 'Matched element is not selectable.'; node.value = text; node.dispatchEvent(new Event('input', { bubbles: true })); node.dispatchEvent(new Event('change', { bubbles: true })); return 'Approved select action executed.'; }",
    "  if (mode === 'key_press') { node.dispatchEvent(new KeyboardEvent('keydown', { key, bubbles: true, cancelable: true })); node.dispatchEvent(new KeyboardEvent('keyup', { key, bubbles: true, cancelable: true })); return 'Approved key action executed.'; }",
    "  return 'Unsupported action.';",
    "})()",
  ].join("\n");
}
