// Coverage scopes are architectural, not result-driven. Keep pure shared domain
// services here; Electron/OS adapters, wire clients, parsers and generated/static
// catalogs are verified by their L2/L4 contract suites instead.
export const sharedBusinessSources = [
  "a5ServiceGuidanceScenario.ts",
  "agentRunJournal.ts",
  "anomalyDecision.ts",
  "approvalStore.ts",
  "backgroundTasks.ts",
  "boundedEventDispatcher.ts",
  "completionNotifications.ts",
  "connectorDigestWorkflow.ts",
  "customCommands.ts",
  "dataCleanup.ts",
  "desktopHandoff.ts",
  "desktopPathPolicy.ts",
  "diagnosticContext.ts",
  "diagnostics.ts",
  "durableJsonStore.ts",
  "externalConnectionReadiness.ts",
  "forkLifecycle.ts",
  "forkQueue.ts",
  "gitCommit.ts",
  "hostConnectionManager.ts",
  "ideContext.ts",
  "managerPresentationTasks.ts",
  "mcpToolExecution.ts",
  "myDrSaiConfig.ts",
  "networkRecovery.ts",
  "portForwards.ts",
  "productionDiagnostics.ts",
  "projectMemory.ts",
  "projectSkills.ts",
  "remoteGatewayInstaller.ts",
  "remoteWorkspaceController.ts",
  "reusableTasks.ts",
  "scheduledTasks.ts",
  "secretRedaction.ts",
  "shareSensitivity.ts",
  "shares.ts",
  "sshHosts.ts",
  "teamMemory.ts",
  "userPreferences.ts",
  "workflowMarketplace.ts",
  "workflowRuns.ts",
  "workspaceCheckpoints.ts",
  "workspaceFileMutations.ts",
  "workspaceMigrations.ts",
  "workspaces.ts",
  "worktrees.ts",
  "browser/actionApproval.ts",
  "browser/browserTaskService.ts",
  "browser/urlPolicy.ts",
  "chatRunJournal.ts",
  "channelProviderAuth.ts",
];

// State machines with persistent transitions, approval/ownership decisions or
// restart recovery. Their aggregate branch coverage is a separate hard gate.
export const coreStateMachineSources = [
  "agentRunJournal.ts",
  "anomalyDecision.ts",
  "approvalStore.ts",
  "backgroundTasks.ts",
  "channelProviderAuth.ts",
  "chatRunJournal.ts",
  "durableJsonStore.ts",
  "forkQueue.ts",
  "hostConnectionManager.ts",
  "scheduledTasks.ts",
  "sshHosts.ts",
  "userPreferences.ts",
  "workflowMarketplace.ts",
  "workflowRuns.ts",
  "workspaceCheckpoints.ts",
];

export const integrationAdapterSources = ["channelAdapters.ts"];

export const coverageThresholds = Object.freeze({
  sharedBusinessLines: 80,
  coreStateMachineBranches: 90,
  integrationAdapterLines: 55,
});
