const node = process.execPath;
const bundled = "../shared/test-kit/run-bundled-test.mjs";

const direct = (id, file, aspects = ["positive", "negative"]) => ({ id, command: node, args: [file], entryFile: file, aspects });
const typed = (id, file, aspects = ["positive", "negative"]) => ({ id, command: node, args: [bundled, file], entryFile: file, aspects });

// Every entry is a separately executed acceptance suite. `aspects` describes
// the behavior classes that the suite proves and is validated per feature.
export const macosVerificationSuites = [
  direct("suite:macos-dev-setup", "../shared/test-kit/verify-macos-dev-setup.mjs", ["positive", "negative", "architecture"]),
  direct("p2:native-helper", "../shared/test-kit/verify-native-helper-static.mjs", ["positive", "negative", "architecture", "authorization"]),
  typed("p2:native-protocol", "../shared/test-kit/verify-native-helper.mts", ["positive", "negative", "cancel-timeout", "recovery"]),
  typed("p2:native-keychain", "../shared/test-kit/verify-native-credential-service.mts", ["positive", "negative", "authorization", "recovery", "privacy"]),
  typed("p2:process-lifecycle", "../shared/test-kit/verify-managed-process-registry.mts", ["positive", "negative", "cancel-timeout", "recovery", "architecture"]),
  direct("suite:shell-contract", "../shared/test-kit/verify-macos-contract.mjs", ["positive", "platform-contract"]),
  direct("suite:secure-ipc", "../shared/test-kit/verify-secure-ipc.mts", ["positive", "negative", "authorization", "cancel-timeout", "idempotency"]),
  direct("suite:security-policy", "../shared/test-kit/verify-desktop-security-policy.mts", ["positive", "negative", "authorization"]),
  direct("suite:secret-redaction", "../shared/test-kit/verify-secret-redaction.mts", ["positive", "negative", "privacy"]),
  typed("suite:auth-lifecycle", "../shared/test-kit/verify-auth-session-lifecycle.mts", ["positive", "negative", "recovery"]),
  typed("suite:approval-state", "../shared/test-kit/verify-approval-state-machine.mts", ["positive", "negative", "idempotency", "recovery"]),
  typed("suite:thread-lifecycle", "../shared/test-kit/verify-thread-lifecycle.mts", ["positive", "negative", "persistence", "recovery"]),
  typed("suite:agent-recovery", "../shared/test-kit/verify-agent-run-recovery.mts", ["positive", "negative", "cancel-timeout", "recovery"]),
  typed("suite:chat-recovery", "../shared/test-kit/verify-chat-run-recovery.mts", ["positive", "negative", "cancel-timeout", "recovery"]),
  typed("suite:stream-backpressure", "../shared/test-kit/verify-stream-backpressure.mts", ["positive", "negative", "cancel-timeout", "idempotency"]),
  typed("suite:git-approval", "../shared/test-kit/verify-git-commit-approval.mts", ["positive", "negative", "authorization"]),
  typed("suite:fork-approval", "../shared/test-kit/verify-fork-lifecycle-approval.mts", ["positive", "negative", "authorization", "recovery"]),
  typed("suite:mcp-tool-approval", "../shared/test-kit/verify-mcp-tool-approval.mts", ["positive", "negative", "authorization", "cancel-timeout"]),
  typed("suite:workspace-checkpoints", "../shared/test-kit/verify-workspace-checkpoints.mts", ["positive", "negative", "persistence", "recovery"]),
  typed("suite:worktree-lifecycle", "../shared/test-kit/verify-worktree-lifecycle.mts", ["positive", "negative", "recovery"]),
  typed("suite:fork-queue", "../shared/test-kit/verify-fork-queue-and-conflict.mts", ["positive", "negative", "idempotency", "recovery"]),
  typed("suite:desktop-handoff", "../shared/test-kit/verify-desktop-handoff.mts", ["positive", "negative", "authorization"]),
  typed("suite:terminal-lifecycle", "../shared/test-kit/verify-macos-terminal-lifecycle.mts", ["positive", "negative", "cancel-timeout", "recovery"]),
  typed("suite:diagnostics", "../shared/test-kit/verify-desktop-diagnostics.mts", ["positive", "negative", "privacy", "persistence"]),
  typed("suite:diagnostic-package", "../shared/test-kit/verify-diagnostic-source-and-package.mts", ["positive", "negative", "privacy", "reproducibility"]),
  direct("suite:codex-backend", "../shared/test-kit/verify-macos-codex-backend.mts", ["positive", "negative", "cancel-timeout", "recovery"]),
  direct("suite:macos-lifecycle", "../shared/test-kit/verify-macos-lifecycle.mts", ["positive", "negative", "recovery"]),
  direct("suite:macos-recovery", "../shared/test-kit/verify-macos-recovery.mts", ["positive", "negative", "idempotency", "recovery"]),
  direct("suite:process-lifecycle", "../shared/test-kit/verify-macos-process-lifecycle.mts", ["positive", "negative", "cancel-timeout", "idempotency", "recovery"]),
  direct("suite:credentials", "../shared/test-kit/verify-macos-credentials.mts", ["positive", "negative", "authorization", "recovery"]),
  direct("suite:system-permissions", "../shared/test-kit/verify-macos-system-permissions.mjs", ["positive", "negative", "authorization"]),
  direct("suite:runtime-contract", "../shared/test-kit/verify-macos-runtime-contract.mjs", ["positive", "negative", "cancel-timeout", "recovery", "reproducibility", "artifact-integrity"]),
  typed("p2:runtime-filesystem-policy", "../shared/test-kit/verify-macos-runtime-filesystem-policy.mts", ["positive", "negative", "authorization", "artifact-integrity"]),
  direct("suite:file-mutations", "../shared/test-kit/verify-workspace-file-mutations.mjs", ["positive", "negative", "authorization", "idempotency"]),
  typed("suite:workspace-git-actions", "../shared/test-kit/verify-workspace-git-actions.mts", ["positive", "negative", "authorization", "idempotency"]),
  direct("suite:mcp-sessions", "../shared/test-kit/verify-macos-mcp-sessions.mjs", ["positive", "negative", "authorization", "cancel-timeout", "recovery"]),
  typed("suite:ssh-hosts", "../shared/test-kit/verify-ssh-hosts.mts", ["positive", "negative", "authorization", "persistence", "recovery"]),
  typed("suite:remote-gateway", "../shared/test-kit/verify-remote-gateway-installer.mts", ["positive", "negative", "authorization", "cancel-timeout", "recovery"]),
  typed("suite:remote-workspace", "../shared/test-kit/verify-remote-workspace-controller.mts", ["positive", "negative", "authorization", "recovery"]),
  typed("suite:port-forwards", "../shared/test-kit/verify-port-forwards.mts", ["positive", "negative", "idempotency", "recovery"]),
  typed("suite:customization", "../shared/test-kit/verify-desktop-customization.mts", ["positive", "negative", "persistence", "recovery"]),
  typed("suite:memory", "../shared/test-kit/verify-memory-stores.mts", ["positive", "negative", "authorization", "persistence", "recovery"]),
  typed("suite:project-skills", "../shared/test-kit/verify-project-skills.mts", ["positive", "negative", "authorization", "persistence", "recovery"]),
  typed("suite:workflows", "../shared/test-kit/verify-workflow-marketplace.mts", ["positive", "negative", "authorization", "cancel-timeout", "recovery"]),
  typed("suite:scheduled-tasks", "../shared/test-kit/verify-scheduled-tasks.mts", ["positive", "negative", "idempotency", "persistence", "recovery"]),
  typed("suite:background-tasks", "../shared/test-kit/verify-background-tasks.mts", ["positive", "negative", "cancel-timeout", "idempotency", "recovery"]),
  typed("suite:shares", "../shared/test-kit/verify-shares.mts", ["positive", "negative", "authorization", "persistence", "recovery", "privacy"]),
  typed("suite:channels", "../shared/test-kit/verify-channel-adapters.mts", ["positive", "negative", "authorization", "cancel-timeout", "recovery", "privacy"]),
  typed("suite:channel-provider-auth", "../shared/test-kit/verify-channel-provider-auth.mts", ["positive", "negative", "authorization", "persistence", "recovery", "privacy"]),
  typed("suite:manager-presentation", "../shared/test-kit/verify-manager-presentation.mts", ["positive", "negative", "cancel-timeout", "recovery"]),
  direct("suite:voice-contract", "../windows/scripts/test-streaming-voice-contracts.mjs", ["positive", "negative", "cancel-timeout", "idempotency"]),
  direct("suite:voice-main", "../windows/scripts/test-streaming-voice-main.mjs", ["positive", "negative", "cancel-timeout", "recovery"]),
  typed("suite:reusable-tasks", "../shared/test-kit/verify-reusable-tasks.mts", ["positive", "negative", "idempotency", "persistence", "recovery"]),
  direct("suite:mobile-pairing-controller", "../windows/scripts/verify-mobile-pairing-controller.mjs", ["positive", "negative", "cancel-timeout", "recovery"]),
  direct("suite:mobile-pairing-security", "../windows/scripts/verify-mobile-pairing-security.mjs", ["positive", "negative", "authorization", "privacy"]),
  typed("suite:anomaly-decision", "../shared/test-kit/verify-anomaly-decision.mts", ["positive", "negative", "idempotency", "persistence"]),
  typed("suite:completion-notifications", "../shared/test-kit/verify-completion-notifications.mts", ["positive", "negative", "authorization", "recovery"]),
  typed("suite:data-cleanup", "../shared/test-kit/verify-data-cleanup.mts", ["positive", "negative", "authorization", "persistence"]),
  typed("suite:browser-tasks", "../shared/test-kit/verify-browser-task-service.mts", ["positive", "negative", "authorization", "cancel-timeout", "recovery"]),
  typed("suite:a5-service-guidance", "../shared/test-kit/verify-a5-service-guidance.mts", ["positive", "negative", "recovery"]),
  direct("suite:interactive-debugger", "../windows/scripts/verify-interactive-debugging.mjs", ["positive", "negative", "authorization", "cancel-timeout", "recovery"]),
  direct("suite:platform-feature-evidence", "../shared/test-kit/verify-platform-feature-evidence.mjs", ["positive", "negative", "artifact-integrity"]),
  direct("suite:inventory", "../shared/test-kit/verify-desktop-ipc-inventory.mjs", ["positive", "inventory"]),
  direct("suite:architecture-boundaries", "../shared/test-kit/verify-architecture-boundaries.mjs", ["positive", "architecture"]),
  direct("suite:release-contract", "../shared/test-kit/verify-macos-release-contract.mjs", ["positive", "negative", "release-contract"]),
  direct("suite:build-output", "../shared/test-kit/verify-macos-build-output.mjs", ["positive", "artifact-integrity"]),
  direct("suite:build-metadata", "../shared/test-kit/verify-macos-build-metadata.mjs", ["positive", "artifact-integrity", "reproducibility"]),
];

export const macosVerificationSuiteIds = new Set(macosVerificationSuites.map((suite) => suite.id));

export const macosVerificationSuiteDefinition = (suite) => ({
  id: suite.id,
  entryFile: suite.entryFile,
  aspects: suite.aspects,
});
