import assert from "node:assert/strict";
import { access, mkdir, mkdtemp, readFile, rm, stat, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";

const root = await mkdtemp(join(tmpdir(), "drsai-shares-")); process.env.DRSAI_HOME = root;
const secrets = new Map<string, string>(); let sequence = 0;
try {
  const [auth, tasks, shares] = await Promise.all([import("../main/auth.ts"), import("../main/backgroundTasks.ts"), import("../main/shares.ts")]);
  auth.configureAuthPlatform({ credentials: { available: () => true, protect: (secret: string) => { const ref = `keychain:share-${++sequence}`; secrets.set(ref, secret); return ref; }, unprotect: (ref?: string) => ref ? secrets.get(ref) : undefined, remove: (ref?: string) => ref ? secrets.delete(ref) : false }, openExternal: async () => undefined });
  const login = async (id: string, email: string) => { await auth.logout().catch(() => undefined); await mkdir(join(root, "auth"), { recursive: true }); await writeFile(join(root, "auth", "session.json"), JSON.stringify({ authenticated: true, authMode: "sso", sessionId: `session-${id}`, createdAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 86_400_000).toISOString(), accessTokenExpiresAt: new Date(Date.now() + 3_600_000).toISOString(), accessToken: `e30.${Buffer.from(JSON.stringify({ exp: Math.floor(Date.now() / 1000) + 3600 })).toString("base64url")}.sig`, refreshToken: `refresh-${id}`, user: { id, email, role: "member" } })); assert.equal((await auth.getAuthSession()).authenticated, true); };
  await login("owner", "owner@example.test");
  const workspace = join(root, "workspace"); await mkdir(workspace); const artifactPath = join(workspace, "report.txt"); await writeFile(artifactPath, "version one\n");
  const source = await tasks.enqueueBackgroundTask({ kind: "agent_run", source: "agent", title: "Completed analysis", status: "completed", workspacePath: workspace, targetId: "agent-result", idempotencyKey: "share-source:agent-result", deliverySummary: { summary: "Analysis complete", artifacts: [{ id: "artifact-1", label: "Report", path: artifactPath, kind: "report" }] } });
  const inspection = await shares.inspectShare({ sourceTaskId: source.id, scope: "complete_task" }); assert.equal(inspection.requiresResolution, false);
  const manifest = await shares.createShare({ sourceTaskId: source.id, scope: "complete_task", recipientAccount: "recipient@example.test", permission: "view" }); assert.equal(manifest.version, 1); assert.equal(manifest.objects.length, 2);
  await login("recipient", "recipient@example.test"); assert.equal((await shares.listIncomingShares())[0].id, manifest.id);
  const artifactObject = manifest.objects.find((item) => item.objectType === "artifact")!;
  const opened = await shares.openSharedObject({ shareId: manifest.id, objectType: "artifact", objectId: artifactObject.objectId }); assert.equal(opened.authorized, true);
  const download = await shares.downloadSharedArtifact({ shareId: manifest.id, objectId: artifactObject.objectId }); assert.equal(Buffer.from(download.base64, "base64").toString(), "version one\n"); assert.equal(download.sha256, createHash("sha256").update("version one\n").digest("hex"));
  await assert.rejects(() => shares.addShareComment({ shareId: manifest.id, body: "Needs detail", objectId: artifactObject.objectId, anchorType: "paragraph", anchorLabel: "Summary" }), /permission/i);

  await login("owner", "owner@example.test"); await shares.updateSharePermission({ shareId: manifest.id, permission: "comment" });
  await login("recipient", "recipient@example.test"); const comment = await shares.addShareComment({ shareId: manifest.id, body: "Needs detail", objectId: artifactObject.objectId, anchorType: "paragraph", anchorLabel: "Summary" }); assert.equal(comment.target.anchorType, "paragraph");
  await login("owner", "owner@example.test"); const preview = await shares.previewShareCommentTask({ shareId: manifest.id, commentId: comment.id }); const commentTask = await shares.createShareCommentTask({ shareId: manifest.id, commentId: comment.id, title: preview.title, instructions: preview.instructions }); const edited = await shares.updateShareCommentTask({ taskId: commentTask.id, title: "Clarify report", instructions: "Add evidence." }); assert.equal(edited.title, "Clarify report"); assert.equal((await shares.completeShareCommentTask({ taskId: commentTask.id })).status, "completed"); assert.equal((await shares.listShareCommentTasks({ shareId: manifest.id })).length, 1);

  const beforePublishStore = JSON.parse(await readFile(join(root, "desktop", "shares.json"), "utf8")); const oldSnapshot = beforePublishStore.shares[0].internalObjects.find((item: { artifactPath?: string }) => item.artifactPath)?.artifactPath;
  await writeFile(artifactPath, "version two\n"); const version = await shares.inspectShareVersion({ shareId: manifest.id }); assert.equal(version.hasChanges, true); const published = await shares.publishShareVersion({ shareId: manifest.id, expectedVersion: 1, sourceFingerprints: version.sourceFingerprints }); assert.equal(published.currentVersion, 2); await assert.rejects(() => shares.publishShareVersion({ shareId: manifest.id, expectedVersion: 1, sourceFingerprints: version.sourceFingerprints }), /version|changed|conflict/i); if (oldSnapshot) await assert.rejects(access(oldSnapshot), /ENOENT/, "superseded snapshots must be removed after commit");
  const comments = await shares.listShareComments({ shareId: manifest.id }); assert.equal(comments[0].versionStatus, "stale");
  await shares.updateSharePermission({ shareId: manifest.id, permission: "continue" }); await login("recipient", "recipient@example.test"); const continuation = await shares.continueSharedTask({ shareId: manifest.id }); assert.equal(continuation.status, "requested");
  await login("owner", "owner@example.test");
  const secretPath = join(workspace, "sensitive.txt"); await writeFile(secretPath, "Bearer abcdefghijklmnop\ncontact person@example.test\n"); const secretTask = await tasks.enqueueBackgroundTask({ kind: "agent_run", source: "agent", title: "Sensitive analysis", status: "completed", workspacePath: workspace, idempotencyKey: "share-source:sensitive", deliverySummary: { summary: "Sensitive", artifacts: [{ id: "artifact-secret", label: "Sensitive report", path: secretPath, kind: "report" }] } });
  const sensitive = await shares.inspectShare({ sourceTaskId: secretTask.id, scope: "result_only", artifactId: "artifact-secret" }); assert.equal(sensitive.requiresResolution, true); assert(sensitive.findings.some((item) => item.kind === "bearer_token") && sensitive.findings.some((item) => item.kind === "email"));
  await assert.rejects(() => shares.createShare({ sourceTaskId: secretTask.id, scope: "result_only", artifactId: "artifact-secret", recipientAccount: "recipient@example.test" }), /review/i);
  await assert.rejects(() => shares.createShare({ sourceTaskId: secretTask.id, scope: "result_only", artifactId: "artifact-secret", recipientAccount: "recipient@example.test", sensitiveResolutions: [{ findingId: sensitive.findings[0].id, action: "redact" }, { findingId: "sensitive:00000000000000000000", action: "remove" }] }), /match|review/i);
  const secretShare = await shares.createShare({ sourceTaskId: secretTask.id, scope: "result_only", artifactId: "artifact-secret", recipientAccount: "recipient@example.test", sensitiveResolutions: sensitive.findings.map((item) => ({ findingId: item.id, action: item.kind === "email" ? "remove" as const : "redact" as const })) }); assert.equal(secretShare.sensitiveReview?.highRiskSecretsDirectlyShared, 0);
  await writeFile(secretPath, "Bearer zyxwvutsrqponmlk\ncontact next@example.test\n"); const secretVersion = await shares.inspectShareVersion({ shareId: secretShare.id }); await assert.rejects(() => shares.publishShareVersion({ shareId: secretShare.id, expectedVersion: 1, sourceFingerprints: secretVersion.sourceFingerprints }), /review/i); const currentSensitive = await shares.inspectShare({ sourceTaskId: secretTask.id, scope: "result_only", artifactId: "artifact-secret" }); const secretPublished = await shares.publishShareVersion({ shareId: secretShare.id, expectedVersion: 1, sourceFingerprints: secretVersion.sourceFingerprints, sensitiveResolutions: currentSensitive.findings.map((item) => ({ findingId: item.id, action: "redact" as const })) }); assert.equal(secretPublished.currentVersion, 2); assert.equal(secretPublished.manifest.sensitiveReview?.highRiskSecretsDirectlyShared, 0); const secretAudit = await shares.listShareAudit({ shareId: secretShare.id }); assert(secretAudit.some((entry) => entry.action === "version_publish" && entry.outcome === "denied"));
  const shareMode = (await stat(join(root, "desktop", "shares.json"))).mode & 0o077; if (process.platform !== "win32") assert.equal(shareMode, 0, "share index must be private");
  const outsideDirectory = join(root, "outside"); const linkedDirectory = join(workspace, "linked-outside"); await mkdir(outsideDirectory); const outside = join(outsideDirectory, "secret.txt"); await writeFile(outside, "password=outside-secret\n"); await symlink(outsideDirectory, linkedDirectory, "junction"); const linked = join(linkedDirectory, "secret.txt"); const linkedTask = await tasks.enqueueBackgroundTask({ kind: "agent_run", source: "agent", title: "Linked result", status: "completed", workspacePath: workspace, idempotencyKey: "share-source:linked", deliverySummary: { summary: "Linked", artifacts: [{ id: "artifact-link", label: "Link", path: linked, kind: "report" }] } }); await assert.rejects(() => shares.inspectShare({ sourceTaskId: linkedTask.id, scope: "result_only", artifactId: "artifact-link" }), /symbolic-link|outside/i);
  await login("recipient", "recipient@example.test"); const sanitizedDownload = await shares.downloadSharedArtifact({ shareId: secretShare.id, objectId: "artifact-secret" }); const sanitized = Buffer.from(sanitizedDownload.base64, "base64").toString(); assert.doesNotMatch(sanitized, /zyxwvutsrqponmlk|next@example/i); assert.match(sanitized, /已遮蔽秘密/);
  await login("owner", "owner@example.test"); const revoked = await shares.revokeShare({ shareId: manifest.id, confirmation: "REVOKE" }); assert.equal(revoked.objectsInvalidated, 2); const audit = await shares.listShareAudit({ shareId: manifest.id }); assert(audit.some((entry) => entry.outcome === "denied") && audit.some((entry) => entry.action === "revoke"));
  await login("recipient", "recipient@example.test"); assert.equal((await shares.listIncomingShares()).some((item) => item.id === manifest.id), false); await assert.rejects(() => shares.openSharedObject({ shareId: manifest.id, objectType: "artifact", objectId: artifactObject.objectId }), /active|access|available/i); await assert.rejects(() => shares.downloadSharedArtifact({ shareId: manifest.id, objectId: artifactObject.objectId }), /active|access|available/i);
  const stored = JSON.parse(await readFile(join(root, "desktop", "shares.json"), "utf8")); assert.equal(stored.revision > 0, true);
  console.log("Share create, permission, recipient access, download integrity, comments, tasks, version conflict, continuation, audit and revocation passed.");
} finally { await rm(root, { recursive: true, force: true }); }
