import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const root = await mkdtemp(join(tmpdir(), "drsai-workflows-"));
try {
  process.env.DRSAI_HOME = root;
  const [workflowViewSource, mockApiSource] = await Promise.all([
    readFile(join(process.cwd(), "../shared/renderer/src/components/SkillSquareView.tsx"), "utf8"),
    readFile(join(process.cwd(), "../shared/renderer/src/mockDesktopApi.ts"), "utf8"),
  ]);
  assert.match(workflowViewSource, /Confirm chat complete/);
  assert.match(workflowViewSource, /completeWorkflowRunStep/);
  assert.match(workflowViewSource, /step\.kind === "chat_command" && step\.status === "running"/);
  assert.match(mockApiSource, /Mock chat command prepared; confirm this step only after the chat action finishes/);
  assert.doesNotMatch(mockApiSource, /Mock dispatched to the chat bar:/);
  assert.doesNotMatch(mockApiSource, /Add connector runtime verifier after live OAuth is wired/);
  const [{ WorkflowMarketplaceStore }, { WorkflowRunStore }, { PersistentApprovalStore }] = await Promise.all([import("../main/workflowMarketplace.ts"), import("../main/workflowRuns.ts"), import("../main/approvalStore.ts")]);
  const workspace = join(root, "workspace"); await mkdir(join(workspace, ".drsai"), { recursive: true }); const sourcePath = join(workspace, ".drsai", "workflow-marketplace.json");
  await writeFile(sourcePath, JSON.stringify({ templates: [{ id: "docs-release", name: "Docs release", category: "release", status: "available", summary: "Review and publish docs", trigger: "manual", steps: ["Review docs", "Confirm release"], requiredCapabilities: ["review"], approvalRequired: true, verification: "Run docs verifier", risk: "high" }, { broken: true }] }));
  const marketplace = new WorkflowMarketplaceStore(join(root, "imports.json")); const synced = await marketplace.sync({ workspacePath: workspace }); assert.equal(synced.importedCount, 1); assert.equal(synced.ignoredCount, 1); assert.equal((await marketplace.list(workspace)).syncedCount, 1); assert.equal(JSON.parse(await readFile(join(root, "imports.json"), "utf8")).schemaVersion, 2);
  assert.equal(JSON.parse(await readFile(join(root, "imports.json.bak"), "utf8")).schemaVersion, 2);
  await writeFile(join(root, "imports.json"), "{partial-marketplace-state");
  assert.equal((await new WorkflowMarketplaceStore(join(root, "imports.json")).list(workspace)).syncedCount, 1, "corrupt marketplace primary must recover imported templates from backup");
  await assert.rejects(() => marketplace.sync({ workspacePath: workspace, sourcePath: join(root, "outside.json") }), /inside the Workspace|ENOENT/i);
  await writeFile(sourcePath, JSON.stringify({ templates: [], token: "Bearer abc.def.ghi" })); await assert.rejects(() => marketplace.sync({ workspacePath: workspace }), /must not contain/i);

  const blocked = await marketplace.prepare({ templateId: "missing", workspacePath: workspace }); assert.equal(blocked.blocked, true);
  const connectorCatalog = await marketplace.list(workspace); const connectorTemplate = connectorCatalog.templates.find((item) => item.id === "connector-digest"); assert(connectorTemplate); assert.equal(connectorTemplate.status, "available"); assert.equal(connectorTemplate.approvalRequired, false); assert.equal(connectorCatalog.availableCount, connectorCatalog.templates.filter((item) => item.status === "available").length);
  const connector = await marketplace.prepare({ templateId: "connector-digest", workspacePath: workspace }); assert.equal(connector.blocked, false); assert.equal(connector.queued, false); assert.equal(connector.recipe.status, "ready"); assert.deepEqual(connector.recipe.steps.map((item) => [item.id, item.kind]), [["review-context", "manual_review"], ["draft-brief", "chat_command"], ["verify-brief", "manual_review"]]); assert.match(connector.recipe.steps[0].detail, /no provider fetch/i); assert.match(connector.recipe.steps[1].command ?? "", /only visible reviewed Channel attachments/i); assert.match(connector.recipe.steps[1].command ?? "", /do not fetch or send provider data/i);
  const connectorRuns = new WorkflowRunStore(join(root, "connector-runs.json")); let connectorRun = (await connectorRuns.start({ recipe: connector.recipe })).run; connectorRun = (await connectorRuns.dispatch({ runId: connectorRun.id, stepId: "review-context" })).run; assert.equal(connectorRun.currentStepId, "draft-brief"); connectorRun = (await connectorRuns.dispatch({ runId: connectorRun.id, stepId: "draft-brief" })).run; assert.equal(connectorRun.currentStepId, "draft-brief"); assert.equal(connectorRun.steps[1].status, "running"); connectorRun = (await connectorRuns.complete({ runId: connectorRun.id, stepId: "draft-brief", exitCode: 0, output: "brief reviewed" })).run; assert.equal(connectorRun.currentStepId, "verify-brief"); connectorRun = (await connectorRuns.dispatch({ runId: connectorRun.id, stepId: "verify-brief" })).run; assert.equal(connectorRun.status, "complete");
  const testCommit = await marketplace.prepare({ templateId: "test-and-commit", workspacePath: workspace }); assert.deepEqual(testCommit.recipe.steps.map((item) => [item.id, item.kind, item.command]), [["test", "chat_command", "/test"], ["capture", "manual_review", undefined], ["preflight", "manual_review", undefined], ["commit", "chat_command", "/commit <message>"]]); assert(testCommit.recipe.steps.every((item) => item.kind !== "approval"), "commit approval is owned by the real /commit path, not a dead workflow approval step");
  const memorySkill = await marketplace.prepare({ templateId: "memory-to-skill", workspacePath: workspace }); assert.equal(memorySkill.recipe.steps[0].command, "/memory retrospective <lesson>"); assert.deepEqual(memorySkill.recipe.steps.slice(1).map((item) => item.kind), ["manual_review", "manual_review", "manual_review"]);
  const externalWithoutApproval = await marketplace.prepare({ templateId: "external-runtime-reconnect", workspacePath: workspace }); assert.equal(externalWithoutApproval.blocked, true); assert.match(externalWithoutApproval.reason, /approval proposal is required/i); await assert.rejects(() => new WorkflowRunStore(join(root, "bypass-runs.json")).start({ recipe: externalWithoutApproval.recipe }), /not approved and ready/i);
  const approvedProposal = { queued: false, allowed: true, requiresApproval: false, blocked: false, reason: "Approved workflow proposal." } as const; const external = await marketplace.prepare({ templateId: "external-runtime-reconnect", workspacePath: workspace }, approvedProposal); assert.deepEqual(external.recipe.steps.map((item) => [item.id, item.kind]), [["prepare", "chat_command"], ["runtime", "external_runtime"], ["verify-runtime", "manual_review"]]); const externalRuns = new WorkflowRunStore(join(root, "external-runs.json")); let externalRun = (await externalRuns.start({ recipe: external.recipe })).run; externalRun = (await externalRuns.dispatch({ runId: externalRun.id, stepId: "prepare" })).run; externalRun = (await externalRuns.complete({ runId: externalRun.id, stepId: "prepare", exitCode: 0 })).run; assert.equal(externalRun.currentStepId, "runtime"); assert.equal(externalRun.status, "waiting_approval"); const reconnected = await externalRuns.complete({ runId: externalRun.id, stepId: "runtime", exitCode: 0, output: "provider reconnected" }); assert.equal(reconnected.completed, true); assert.equal(reconnected.run.currentStepId, "verify-runtime"); externalRun = (await externalRuns.dispatch({ runId: externalRun.id, stepId: "verify-runtime" })).run; assert.equal(externalRun.status, "complete");
  const approvals = new PersistentApprovalStore(join(root, "approvals.json")); const template = await marketplace.get("docs-release", workspace); assert(template);
  const proposal = await approvals.propose({ source: "workflow", actionKind: "workflow.run", title: `Run ${template.name}`, detail: template.summary, target: workspace, risk: "high", idempotencyKey: `workflow:${"a".repeat(64)}` }, async () => true); const queued = await marketplace.prepare({ templateId: template.id, workspacePath: workspace }, proposal); assert.equal(queued.queued, true);
  const runs = new WorkflowRunStore(join(root, "runs.json")); await assert.rejects(() => runs.start({ recipe: queued.recipe }), /not approved and ready/i); assert(proposal.approval); assert.equal(await approvals.decide({ id: proposal.approval.id, approved: true }), true);
  const repeated = await approvals.propose({ source: "workflow", actionKind: "workflow.run", title: `Run ${template.name}`, detail: template.summary, target: workspace, risk: "high", idempotencyKey: `workflow:${"a".repeat(64)}` }, async () => true); const readyImported = await marketplace.prepare({ templateId: template.id, workspacePath: workspace }, repeated); assert.equal(readyImported.recipe.status, "ready"); assert(readyImported.recipe.steps.every((item) => item.kind === "manual_review" && item.command === undefined), "synced templates must not synthesize nonexistent /workflow commands");

  const ready = await marketplace.prepare({ templateId: "plan-review-fix", workspacePath: workspace }); const started = await runs.start({ recipe: ready.recipe }); assert.equal(started.run.status, "running"); await assert.rejects(() => runs.dispatch({ runId: started.run.id, stepId: "review" }), /in order/i);
  let current = started.run; for (const stepId of ["plan", "review", "fix"]) { const dispatched = await runs.dispatch({ runId: current.id, stepId }); assert.equal(dispatched.dispatched, true); assert.equal(dispatched.run.steps.find((item) => item.id === stepId)?.status, "running", "preparing chat text must not claim the action completed"); await assert.rejects(() => runs.dispatch({ runId: current.id, stepId }), /not ready/i); const confirmed = await runs.complete({ runId: current.id, stepId, exitCode: 0, output: "chat action completed" }); assert.equal(confirmed.completed, true); current = confirmed.run; }
  const terminal = await runs.dispatch({ runId: current.id, stepId: "verify" }); assert.equal(terminal.dispatched, true); assert.equal(terminal.requiresApproval, true); assert.equal(terminal.run.steps.find((item) => item.id === "verify")?.status, "running");
  const completed = await runs.complete({ runId: current.id, stepId: "verify", exitCode: 0, output: "all tests passed access_token=secret-value" }); assert.equal(completed.run.status, "complete"); assert.doesNotMatch(completed.message, /secret-value/);
  const history = await runs.list(workspace); assert.equal(history[0].status, "complete"); assert.equal(JSON.parse(await readFile(join(root, "runs.json"), "utf8")).schemaVersion, 2);

  const interrupted = await runs.start({ recipe: ready.recipe }); const first = await runs.dispatch({ runId: interrupted.run.id, stepId: "plan" }); assert.equal(first.run.currentStepId, "plan", "an unconfirmed chat action must remain current"); const recovered = await runs.recover(); assert(recovered.recovered >= 1); const recoveredRun = recovered.runs.find((item) => item.id === interrupted.run.id); assert(recoveredRun?.resumePlan); assert.equal(recoveredRun?.currentStepId, "plan", "restart recovery must not skip an unconfirmed chat action"); assert.equal(recoveredRun?.steps.find((item) => item.id === "plan")?.resumeAction, "dispatch_chat");
  const failureRun = await runs.start({ recipe: ready.recipe }); for (const id of ["plan", "review", "fix"]) { await runs.dispatch({ runId: failureRun.run.id, stepId: id }); await runs.complete({ runId: failureRun.run.id, stepId: id, exitCode: 0 }); } await runs.dispatch({ runId: failureRun.run.id, stepId: "verify" }); const failed = await runs.complete({ runId: failureRun.run.id, stepId: "verify", exitCode: 2, output: "failed" }); assert.equal(failed.blocked, true); assert.equal(failed.run.status, "blocked");
  await approvals.shutdown(); console.log("Workflow marketplace sync, approval, strict dispatch, terminal completion, history, failure and restart recovery passed.");
} finally { await rm(root, { recursive: true, force: true }); }
