import assert from "node:assert/strict";
import { access, mkdir, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ChannelProviderAuthService } from "../main/channelProviderAuth.ts";

const root = await mkdtemp(join(tmpdir(), "opendrsai-channel-provider-auth-"));
process.env.DRSAI_HOME = root;
const storePath = join(root, "desktop", "channel-provider-auth.json");
const secrets = new Map<string, string>();
const removed: string[] = [];
let reference = 0;
const credentials = {
  available: () => true,
  protect(secret: string) { const id = `keychain:channel-${++reference}`; secrets.set(id, secret); return id; },
  unprotect(id: string | undefined) { return id ? secrets.get(id) : undefined; },
  remove(id: string | undefined) { if (!id) return false; removed.push(id); return secrets.delete(id); },
};
const responses: Array<{ status?: number; body: unknown; headers?: Record<string, string>; failAfterAccept?: string; onRequest?: () => void | Promise<void> }> = [];
const requests: Array<{ url: string; authorization?: string; body?: string }> = [];
const legacyHash = (value: string) => { let hash = 0; for (let index = 0; index < value.length; index += 1) hash = (hash * 31 + value.charCodeAt(index)) >>> 0; return hash.toString(36); };
const fetcher = (async (input: string | URL | Request, init?: RequestInit) => {
  const next = responses.shift(); if (!next) throw new Error("Unexpected provider request");
  const headers = new Headers(init?.headers); requests.push({ url: String(input), authorization: headers.get("authorization") ?? undefined, body: String(init?.body ?? "") });
  await next.onRequest?.();
  if (next.failAfterAccept) throw new Error(next.failAfterAccept);
  return new Response(JSON.stringify(next.body), { status: next.status ?? 200, headers: { "content-type": "application/json", ...(next.headers ?? {}) } });
}) as typeof fetch;

try {
  responses.push({ body: { device_code: "device-secret", user_code: "ABCD-EFGH", verification_uri: "https://github.com/login/device", expires_in: 900, interval: 5 } });
  let service = new ChannelProviderAuthService(storePath, credentials, fetcher, "github-client-test", () => Date.parse("2026-07-22T00:00:00Z"));
  const started = await service.startGitHub("workspace-a", ["repo", "repo", "invalid", "read:user"]);
  assert.match(started.operationId, /^channel-auth:/); assert.deepEqual(started.scopes, ["repo", "read:user"]); assert.equal(started.userCode, "ABCD-EFGH");
  const stored = await readFile(storePath, "utf8"); assert(!stored.includes("device-secret"), "device code must not be persisted in plaintext"); assert(stored.includes("keychain:channel-1"));
  if (process.platform !== "win32") assert.equal((await stat(storePath)).mode & 0o777, 0o600);

  service = new ChannelProviderAuthService(storePath, credentials, fetcher, "github-client-test", () => Date.parse("2026-07-22T00:00:01Z"));
  responses.push({ body: { error: "authorization_pending" } });
  assert.equal((await service.pollGitHub("workspace-a", started.operationId)).status, "pending");
  responses.push({ body: { error: "slow_down" } });
  const slow = await service.pollGitHub("workspace-a", started.operationId); assert.equal(slow.status, "slow_down"); if (slow.status === "slow_down") assert.equal(slow.intervalSeconds, 10);
  responses.push({ body: { access_token: "github-access-secret", token_type: "bearer", scope: "repo,read:user" } }, { body: { id: 42, login: "octo-reviewer" } });
  const complete = await service.pollGitHub("workspace-a", started.operationId); assert.equal(complete.status, "complete"); if (complete.status === "complete") assert.equal(complete.accountLabel, "octo-reviewer");
  assert.equal(requests.at(-1)?.authorization, "Bearer github-access-secret");
  const completedStore = await readFile(storePath, "utf8"); assert(!completedStore.includes("github-access-secret") && !completedStore.includes("device-secret"));
  const recovered = await new ChannelProviderAuthService(storePath, credentials, fetcher, "github-client-test").githubCredential("workspace-a"); assert.equal(recovered?.token, "github-access-secret"); assert.equal(recovered?.accountLabel, "octo-reviewer");
  assert.equal(await service.revokeGitHub("workspace-a"), true); assert.equal(await service.revokeGitHub("workspace-a"), false); assert.equal(await service.githubCredential("workspace-a"), null); assert(removed.length >= 2);

  await assert.rejects(() => new ChannelProviderAuthService(join(root, "missing.json"), credentials, fetcher, undefined).startGitHub("workspace", []), /not configured/i);
  await assert.rejects(() => new ChannelProviderAuthService(join(root, "locked.json"), { ...credentials, available: () => false }, fetcher, "github-client-test").startGitHub("workspace", []), /unavailable or locked/i);
  await assert.rejects(() => service.pollGitHub("workspace-a", "bad"), /operation id is invalid/i);

  responses.push({ body: { device_code: "expires", user_code: "EXPI-RE00", verification_uri: "https://github.com/login/device", expires_in: 60, interval: 1 } });
  const expiring = await new ChannelProviderAuthService(storePath, credentials, fetcher, "github-client-test", () => 0).startGitHub("workspace-expired", []);
  const expired = await new ChannelProviderAuthService(storePath, credentials, fetcher, "github-client-test", () => 61_000).pollGitHub("workspace-expired", expiring.operationId); assert.equal(expired.status, "expired");

  responses.push({ body: { device_code: "denied", user_code: "DENI-ED00", verification_uri: "https://github.com/login/device", expires_in: 60, interval: 1 } });
  const denying = await new ChannelProviderAuthService(storePath, credentials, fetcher, "github-client-test", () => 0).startGitHub("workspace-denied", []);
  responses.push({ body: { error: "access_denied" } }); assert.equal((await new ChannelProviderAuthService(storePath, credentials, fetcher, "github-client-test", () => 1_000).pollGitHub("workspace-denied", denying.operationId)).status, "denied");

  responses.push({ status: 500, body: { message: "secret provider detail" } });
  await assert.rejects(() => service.startGitHub("workspace-error", []), /HTTP 500/);

  const [channels, readiness] = await Promise.all([import("../main/channelAdapters.ts"), import("../main/externalConnectionReadiness.ts")]);
  channels.configureChannelProviderAuth({ credentials, fetcher, githubClientId: "github-client-test" });
  const workspace = join(root, "workspace"); await mkdir(workspace);
  responses.push({ body: { device_code: "integrated-device", user_code: "INTE-GRAT", verification_uri: "https://github.com/login/device", expires_in: 900, interval: 5 } });
  const integratedStart = await channels.startChannelAdapterAuth({ adapterId: "github-connector", workspacePath: workspace, scopes: ["repo"] }); assert.ok(integratedStart.operationId); const pendingAdapter = channels.listChannelAdapters(workspace).adapters.find((item) => item.id === "github-connector"); assert.equal(pendingAdapter?.configured, false); assert.equal(pendingAdapter?.authOperationId, integratedStart.operationId, "pending operation must survive a renderer reload");
  responses.push({ body: { error: "authorization_pending" } }); assert.equal((await channels.pollChannelAdapterAuth({ adapterId: "github-connector", workspacePath: workspace, operationId: integratedStart.operationId! })).status, "pending");
  responses.push({ body: { access_token: "integrated-token" } }, { body: { id: 84, login: "integrated-user" } });
  assert.equal((await channels.pollChannelAdapterAuth({ adapterId: "github-connector", workspacePath: workspace, operationId: integratedStart.operationId! })).status, "complete");
  const integratedAdapter = channels.listChannelAdapters(workspace).adapters.find((item) => item.id === "github-connector"); assert.equal(integratedAdapter?.configured, true); assert.equal(integratedAdapter?.authMode, "oauth"); assert.equal(integratedAdapter?.credentialState, "configured"); assert.equal(integratedAdapter?.authOperationId, undefined, "completed authorization must clear the pending operation"); const githubLiveReadiness = readiness.listExternalConnectionReadiness(workspace).connections.find((item) => item.id === "github"); assert.equal(githubLiveReadiness?.readOnly, false); assert.match(githubLiveReadiness?.verification ?? "", /Device OAuth/);
  await assert.rejects(() => service.githubApi("workspace-a", "/user"), /path is invalid/i);
  await assert.rejects(() => channels.syncLiveChannelContext({ adapterId: "github-connector", workspacePath: workspace, repository: "hepai/drsai/extra" }), /repository must be/i);
  responses.push({ body: [{ number: 42, title: "Investigate capacity", body: "Use API_TOKEN=must-not-leak", state: "open", html_url: "https://github.com/hepai/drsai/issues/42", user: { login: "alice" } }, { number: 7, title: "Fix scheduler", body: "Reviewed", state: "open", html_url: "https://github.com/hepai/drsai/pull/7", user: { login: "bob" }, pull_request: { url: "https://api.github.com/repos/hepai/drsai/pulls/7" } }, { title: "invalid" }] });
  const live = await channels.syncLiveChannelContext({ adapterId: "github-connector", workspacePath: workspace, repository: "hepai/drsai", limit: 10 }); assert.equal(live.items.length, 2); assert.equal(live.items[0].kind, "issue"); assert.equal(live.items[1].kind, "pull_request"); assert(!JSON.stringify(live).includes("must-not-leak")); assert.equal(channels.listChannelInboundEvents({ workspacePath: workspace }).some((event) => event.items.some((item) => item.id === live.items[0].id)), true);
  assert.match(requests.at(-1)?.url ?? "", /\/repos\/hepai\/drsai\/issues\?state=open&per_page=10&sort=updated&direction=desc$/); assert.equal(requests.at(-1)?.authorization, "Bearer integrated-token");
  responses.push({ body: { message: "not an array" } }); await assert.rejects(() => channels.syncLiveChannelContext({ adapterId: "github-connector", workspacePath: workspace, repository: "hepai/drsai" }), /invalid response/i);
  const requestCountBeforeSend = requests.length; responses.push({ body: { id: 9001, html_url: "https://github.com/hepai/drsai/issues/42#issuecomment-9001" } });
  const draft = { adapterId: "github-connector", workspacePath: workspace, target: "https://github.com/hepai/drsai/issues/42", body: "Approved provider comment", idempotencyKey: "github-comment:hepai:drsai:42" };
  const sent = await channels.executeChannelOutboundDeliveryAsync(draft, "approval:github-live", true); assert.equal(sent.status, "sent"); assert.equal(sent.runtime, "github_api");
  const githubSendBody = JSON.parse(requests.at(-1)?.body ?? "{}"); assert.match(githubSendBody.body, /^Approved provider comment\n\n<!-- opendrsai-delivery:[0-9a-f]{32} -->$/); assert.equal(requests.at(-1)?.authorization, "Bearer integrated-token");
  const replayed = await channels.executeChannelOutboundDeliveryAsync(draft, "approval:github-live-retry", true); assert.equal(replayed.id, sent.id); assert.equal(requests.length, requestCountBeforeSend + 1, "idempotent retry must not issue a second provider POST");
  const rejectedRequestCount = requests.length; assert.equal((await channels.executeChannelOutboundDeliveryAsync({ ...draft, idempotencyKey: "github-comment:rejected" }, "approval:rejected", false)).status, "rejected"); assert.equal(requests.length, rejectedRequestCount, "rejected approval must never call GitHub");
  await assert.rejects(() => channels.executeChannelOutboundDeliveryAsync({ ...draft, target: "evil/repo/../../1" }, "approval:bad-target", true), /target must be/i);
  responses.push({ body: { id: "invalid", html_url: "https://example.com/not-github" } }); const failed = await channels.executeChannelOutboundDeliveryAsync({ ...draft, idempotencyKey: "github-comment:invalid-receipt" }, "approval:invalid-receipt", true); assert.equal(failed.status, "failed"); assert.equal(failed.runtime, "github_api");
  const ambiguousGithubDraft = { ...draft, idempotencyKey: "github-comment:accepted-response-lost" }; responses.push({ body: {}, failAfterAccept: "connection closed after GitHub accepted the comment", onRequest: async () => { const store = JSON.parse(await readFile(join(root, "desktop", "channel-deliveries.json"), "utf8")); assert.equal(Object.values(store.workspaces).flat().find((item: any) => item.approvalId === "approval:github-ambiguous")?.status, "pending", "GitHub intent must be durable before POST"); } }); const ambiguousGithubFailure = await channels.executeChannelOutboundDeliveryAsync(ambiguousGithubDraft, "approval:github-ambiguous", true); assert.equal(ambiguousGithubFailure.status, "failed"); const ambiguousGithubPost = JSON.parse(requests.at(-1)?.body ?? "{}"); const githubRequestCountAfterAmbiguousPost = requests.length; responses.push({ body: [{ id: 9002, body: ambiguousGithubPost.body, issue_url: "https://api.github.com/repos/hepai/drsai/issues/42", html_url: "https://github.com/hepai/drsai/issues/42#issuecomment-9002" }] }); const recoveredGithub = await channels.executeChannelOutboundDeliveryAsync(ambiguousGithubDraft, "approval:github-ambiguous-retry", true); assert.equal(recoveredGithub.status, "sent"); assert.match(recoveredGithub.verification, /found in GitHub/); assert.equal(requests.length, githubRequestCountAfterAmbiguousPost + 1, "GitHub reconciliation must replace a second POST with one bounded GET"); assert.match(requests.at(-1)?.url ?? "", /issues\/comments\?sort=created&direction=desc&since=/); assert.equal(requests.at(-1)?.body, "", "GitHub reconciliation must be read-only");
  const aliasConcurrentCount = requests.length; responses.push({ body: { id: 9003, html_url: "https://github.com/hepai/drsai/issues/42#issuecomment-9003" } }); const aliasDraft = { ...draft, idempotencyKey: "github-comment:normalized-alias" }; const [aliasA, aliasB] = await Promise.all([channels.executeChannelOutboundDeliveryAsync(aliasDraft, "approval:github-alias-a", true), channels.executeChannelOutboundDeliveryAsync({ ...aliasDraft, target: "hepai/drsai#42" }, "approval:github-alias-b", true)]); assert.equal(aliasA.status, "sent"); assert.equal(aliasB.id, aliasA.id); assert.equal(requests.length, aliasConcurrentCount + 1, "equivalent GitHub URL and owner/repository#number targets must share one serialized execution");
  assert.equal((await channels.revokeChannelAdapterAuth({ adapterId: "github-connector", workspacePath: workspace })).revoked, true); assert.equal(channels.listChannelAdapters(workspace).adapters.find((item) => item.id === "github-connector")?.configured, false);
  await assert.rejects(() => channels.syncLiveChannelContext({ adapterId: "github-connector", workspacePath: workspace, repository: "hepai/drsai" }), /authorization is required/i);

  // Deliberately non-production-shaped: valid for our local format validator,
  // but not a Slack credential pattern that secret scanners should flag.
  const slackToken = "xoxb-fixture-not-a-credential";
  await assert.rejects(() => channels.configureChannelProviderToken({ adapterId: "slack-chat", workspacePath: workspace, token: "not-a-token" }), /token is invalid/i);
  responses.push({ body: { ok: true, team: "OpenDrSai", user: "release-bot", user_id: "U0123456789", team_id: "T0123456789" } });
  const slackConfigured = await channels.configureChannelProviderToken({ adapterId: "slack-chat", workspacePath: workspace, token: slackToken }); assert.equal(slackConfigured.accountLabel, "OpenDrSai / release-bot"); assert.equal(channels.listChannelAdapters(workspace).adapters.find((item) => item.id === "slack-chat")?.configured, true); const slackLiveReadiness = readiness.listExternalConnectionReadiness(workspace).connections.find((item) => item.id === "slack"); assert.equal(slackLiveReadiness?.readOnly, false); assert.match(slackLiveReadiness?.verification ?? "", /conversations\.history/); assert(!((await readFile(storePath, "utf8")).includes(slackToken)), "Slack token must not be persisted in plaintext");
  assert.equal(requests.at(-1)?.url, "https://slack.com/api/auth.test"); assert.equal(requests.at(-1)?.authorization, `Bearer ${slackToken}`);
  await assert.rejects(() => channels.syncLiveChannelContext({ adapterId: "slack-chat", workspacePath: workspace, channelId: "general" }), /valid channel ID/i);
  responses.push({ body: { ok: true, has_more: false, messages: [{ ts: "1760000000.123456", user: "U0123456789", text: "Deploy complete; API_TOKEN=slack-secret" }, { ts: "1760000001.123456", bot_id: "B0123456789", text: "Checks green" }, { text: "invalid" }] } });
  const slackLive = await channels.syncLiveChannelContext({ adapterId: "slack-chat", workspacePath: workspace, channelId: "C0123456789", limit: 10 }); assert.equal(slackLive.items.length, 2); assert.equal(slackLive.items[0].kind, "slack_message"); assert(!JSON.stringify(slackLive).includes("slack-secret")); assert.deepEqual(JSON.parse(requests.at(-1)?.body ?? "{}"), { channel: "C0123456789", limit: 10, inclusive: true });
  const slackDraft = { adapterId: "slack-chat", workspacePath: workspace, target: "C0123456789", body: "Approved Slack update", idempotencyKey: "slack-message:C0123456789:release" };
  const slackRequestCount = requests.length; responses.push({ body: { ok: true, channel: "C0123456789", ts: "1760000002.123456", message: { text: "Approved Slack update" } } });
  const slackSent = await channels.executeChannelOutboundDeliveryAsync(slackDraft, "approval:slack-live", true); assert.equal(slackSent.status, "sent"); assert.equal(slackSent.runtime, "slack_api"); const slackSendBody = JSON.parse(requests.at(-1)?.body ?? "{}"); assert.equal(slackSendBody.channel, "C0123456789"); assert.equal(slackSendBody.text, "Approved Slack update"); assert.match(slackSendBody.client_msg_id, /^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
  const slackReplay = await channels.executeChannelOutboundDeliveryAsync(slackDraft, "approval:slack-retry", true); assert.equal(slackReplay.id, slackSent.id); assert.equal(requests.length, slackRequestCount + 1);
  const slackRejectedCount = requests.length; assert.equal((await channels.executeChannelOutboundDeliveryAsync({ ...slackDraft, idempotencyKey: "slack-rejected" }, "approval:slack-rejected", false)).status, "rejected"); assert.equal(requests.length, slackRejectedCount);
  responses.push({ body: { ok: false, error: "channel_not_found" } }); const slackFailed = await channels.executeChannelOutboundDeliveryAsync({ ...slackDraft, idempotencyKey: "slack-failed" }, "approval:slack-failed", true); assert.equal(slackFailed.status, "failed"); assert.match(slackFailed.message, /channel_not_found/);
  const ambiguousDraft = { ...slackDraft, idempotencyKey: "slack-accepted-response-lost" }; responses.push({ body: {}, failAfterAccept: "connection closed after provider accepted the message" }); const ambiguousFailure = await channels.executeChannelOutboundDeliveryAsync(ambiguousDraft, "approval:slack-ambiguous", true); assert.equal(ambiguousFailure.status, "failed"); const ambiguousFirstBody = JSON.parse(requests.at(-1)?.body ?? "{}"); responses.push({ body: { ok: true, channel: "C0123456789", ts: "1760000003.123456", message: { text: "Approved Slack update" } } }); const ambiguousRecovered = await channels.executeChannelOutboundDeliveryAsync(ambiguousDraft, "approval:slack-ambiguous-retry", true); assert.equal(ambiguousRecovered.status, "sent"); const ambiguousRetryBody = JSON.parse(requests.at(-1)?.body ?? "{}"); assert.equal(ambiguousRetryBody.client_msg_id, ambiguousFirstBody.client_msg_id, "ambiguous retries must reuse Slack's provider idempotency key"); assert.match(ambiguousRecovered.verification, /stable provider idempotency key/);
  const concurrentDraft = { ...slackDraft, idempotencyKey: "slack-concurrent-once" }; const concurrentRequestCount = requests.length; responses.push({ body: { ok: true, channel: "C0123456789", ts: "1760000004.123456", message: { text: "Approved Slack update" } } }); const [concurrentA, concurrentB] = await Promise.all([channels.executeChannelOutboundDeliveryAsync(concurrentDraft, "approval:slack-concurrent-a", true), channels.executeChannelOutboundDeliveryAsync(concurrentDraft, "approval:slack-concurrent-b", true)]); assert.equal(concurrentA.status, "sent"); assert.equal(concurrentB.id, concurrentA.id); assert.equal(requests.length, concurrentRequestCount + 1, "same workspace/provider/idempotency key must serialize to one provider request");
  const legacyKey = "slack-legacy-ledger"; const legacyId = `channel-delivery:${legacyHash(legacyKey)}:${legacyHash("C0123456789")}`; const deliveryStorePath = join(root, "desktop", "channel-deliveries.json"); const legacyStore = JSON.parse(await readFile(deliveryStorePath, "utf8")); const legacyWorkspaceDeliveries = Object.values(legacyStore.workspaces)[0] as any[]; legacyWorkspaceDeliveries.unshift({ ...slackSent, id: legacyId, approvalId: "approval:slack-legacy" }); await writeFile(deliveryStorePath, JSON.stringify(legacyStore)); const legacyRequestCount = requests.length; const legacyReplay = await channels.executeChannelOutboundDeliveryAsync({ ...slackDraft, idempotencyKey: legacyKey }, "approval:slack-legacy-retry", true); assert.equal(legacyReplay.id, legacyId); assert.equal(requests.length, legacyRequestCount, "legacy sent delivery IDs must remain zero-request idempotent after v2 upgrade");
  const collisionRequestCount = requests.length; responses.push({ body: { ok: true, channel: "C0123456789", ts: "1760000005.123456", message: { text: "Approved Slack update" } } }, { body: { ok: true, channel: "C0123456789", ts: "1760000006.123456", message: { text: "Approved Slack update" } } }); const collisionA = await channels.executeChannelOutboundDeliveryAsync({ ...slackDraft, idempotencyKey: "Aa" }, "approval:slack-collision-a", true); const collisionB = await channels.executeChannelOutboundDeliveryAsync({ ...slackDraft, idempotencyKey: "BB" }, "approval:slack-collision-b", true); assert.equal(legacyHash("Aa"), legacyHash("BB"), "fixture must collide under the legacy rolling hash"); assert.notEqual(collisionA.id, collisionB.id, "SHA-256 v2 IDs must separate legacy hash collisions"); assert.match(collisionA.id, /^channel-delivery:v2:[0-9a-f]{64}$/); assert.equal(requests.length, collisionRequestCount + 2);
  assert.equal((await channels.revokeChannelAdapterAuth({ adapterId: "slack-chat", workspacePath: workspace })).revoked, true); assert.equal(channels.listChannelAdapters(workspace).adapters.find((item) => item.id === "slack-chat")?.configured, false); await assert.rejects(() => channels.syncLiveChannelContext({ adapterId: "slack-chat", workspacePath: workspace, channelId: "C0123456789" }), /authorization is required/i);

  const googleToken = "ya29.a_very_long_google_access_token_1234567890";
  const documentId = "1AbCdEfGhIjKlMnOpQrStUvWxYz123456789";
  await assert.rejects(() => channels.configureChannelProviderToken({ adapterId: "docs-connector", workspacePath: workspace, token: "invalid" }), /token is invalid/i);
  responses.push({ body: { aud: "google-client", email: "docs@example.test", sub: "google-user-1", scope: "openid email https://www.googleapis.com/auth/documents.readonly", expires_in: 3600 } }); await assert.rejects(() => channels.configureChannelProviderToken({ adapterId: "docs-connector", workspacePath: workspace, token: googleToken }), /read\/write scope is required/i);
  responses.push({ body: { aud: "google-client", email: "docs@example.test", sub: "google-user-1", scope: "openid email https://www.googleapis.com/auth/documents", expires_in: 3600 } });
  const docsConfigured = await channels.configureChannelProviderToken({ adapterId: "docs-connector", workspacePath: workspace, token: googleToken }); assert.equal(docsConfigured.accountLabel, "docs@example.test"); assert.ok(docsConfigured.expiresAt); assert.equal(channels.listChannelAdapters(workspace).adapters.find((item) => item.id === "docs-connector")?.authMode, "provider_token"); const docsLiveReadiness = readiness.listExternalConnectionReadiness(workspace).connections.find((item) => item.id === "docs"); assert.equal(docsLiveReadiness?.readOnly, false); assert.match(docsLiveReadiness?.verification ?? "", /batchUpdate/); assert(!((await readFile(storePath, "utf8")).includes(googleToken)), "Google token must not be persisted in plaintext"); assert.equal(requests.at(-1)?.url, "https://oauth2.googleapis.com/tokeninfo");
  const connectionStorePath = join(root, "desktop", "channel-connections.json"); const expireDocsConnection = async (value: string) => { const connectionStore = JSON.parse(await readFile(connectionStorePath, "utf8")); const workspaceConnections = Object.values(connectionStore.workspaces)[0] as Array<{ adapterId: string; sessionExpiresAt?: string }>; const docsConnection = workspaceConnections.find((item) => item.adapterId === "docs-connector")!; docsConnection.sessionExpiresAt = value; await writeFile(connectionStorePath, JSON.stringify(connectionStore)); };
  await expireDocsConnection(new Date(Date.now() - 1_000).toISOString()); let expiredDocs = channels.listChannelAdapters(workspace).adapters.find((item) => item.id === "docs-connector"); assert.equal(expiredDocs?.configured, false); assert.equal(expiredDocs?.status, "config_required"); assert.equal(expiredDocs?.credentialState, "expired"); const expiredDocsReadiness = readiness.listExternalConnectionReadiness(workspace).connections.find((item) => item.id === "docs"); assert.equal(expiredDocsReadiness?.configured, false); assert.equal(expiredDocsReadiness?.status, "partial"); const expiredRequestCount = requests.length; const expiredDelivery = await channels.executeChannelOutboundDeliveryAsync({ adapterId: "docs-connector", workspacePath: workspace, target: documentId, body: "Must not use expired token", idempotencyKey: "docs-expired" }, "approval:docs-expired", true); assert.equal(expiredDelivery.status, "blocked"); assert.equal(requests.length, expiredRequestCount, "expired metadata must block before a provider request");
  await expireDocsConnection("not-a-date"); expiredDocs = channels.listChannelAdapters(workspace).adapters.find((item) => item.id === "docs-connector"); assert.equal(expiredDocs?.credentialState, "expired", "malformed expiry must fail closed"); await expireDocsConnection(docsConfigured.expiresAt!); assert.equal(channels.listChannelAdapters(workspace).adapters.find((item) => item.id === "docs-connector")?.configured, true);
  await assert.rejects(() => channels.syncLiveChannelContext({ adapterId: "docs-connector", workspacePath: workspace, documentId: "bad" }), /document ID is invalid/i);
  responses.push({ body: { documentId, title: "Release API_TOKEN=hidden", revisionId: "rev-live", body: { content: [{ endIndex: 40, paragraph: { elements: [{ textRun: { content: "Release notes\nAPI_TOKEN=docs-secret\n" } }] } }] } } });
  const docsLive = await channels.syncLiveChannelContext({ adapterId: "docs-connector", workspacePath: workspace, documentId }); assert.equal(docsLive.items.length, 1); assert.equal(docsLive.items[0].kind, "document"); assert(!JSON.stringify(docsLive).includes("docs-secret") && !JSON.stringify(docsLive).includes("hidden")); assert.equal(requests.at(-1)?.authorization, `Bearer ${googleToken}`);
  const docsDraft = { adapterId: "docs-connector", workspacePath: workspace, target: `https://docs.google.com/document/d/${documentId}/edit`, body: "Approved appendix", idempotencyKey: "docs-append:release" };
  const docsRequestCount = requests.length; responses.push({ body: { documentId, title: "Release", revisionId: "rev-before", body: { content: [{ endIndex: 40 }] } } }, { body: { documentId, replies: [{}], writeControl: { requiredRevisionId: "rev-after" } } });
  const docsSent = await channels.executeChannelOutboundDeliveryAsync(docsDraft, "approval:docs-live", true); assert.equal(docsSent.status, "sent"); assert.equal(docsSent.runtime, "google_docs_api"); const docsWrite = JSON.parse(requests.at(-1)?.body ?? "{}"); assert.equal(docsWrite.requests[0].insertText.location.index, 39); assert.equal(docsWrite.requests[1].createNamedRange.range.startIndex, 39); assert.equal(docsWrite.requests[1].createNamedRange.range.endIndex, 39 + "\nApproved appendix".length); assert.match(docsWrite.requests[1].createNamedRange.name, /^opendrsai_delivery_[0-9a-f]{32}$/); assert.equal(docsWrite.writeControl.requiredRevisionId, "rev-before");
  const docsReplay = await channels.executeChannelOutboundDeliveryAsync(docsDraft, "approval:docs-retry", true); assert.equal(docsReplay.id, docsSent.id); assert.equal(requests.length, docsRequestCount + 2);
  const docsRejectedCount = requests.length; assert.equal((await channels.executeChannelOutboundDeliveryAsync({ ...docsDraft, idempotencyKey: "docs-rejected" }, "approval:docs-rejected", false)).status, "rejected"); assert.equal(requests.length, docsRejectedCount);
  responses.push({ body: { documentId, title: "Release", body: { content: [] } } }); const docsFailed = await channels.executeChannelOutboundDeliveryAsync({ ...docsDraft, idempotencyKey: "docs-failed" }, "approval:docs-failed", true); assert.equal(docsFailed.status, "failed"); assert.match(docsFailed.message, /insertion boundary/i);
  const ambiguousDocsDraft = { ...docsDraft, idempotencyKey: "docs-accepted-response-lost" }; responses.push({ body: { documentId, title: "Release", revisionId: "rev-ambiguous", body: { content: [{ endIndex: 50 }] } } }, { body: {}, failAfterAccept: "connection closed after Docs accepted batchUpdate", onRequest: async () => { const store = JSON.parse(await readFile(join(root, "desktop", "channel-deliveries.json"), "utf8")); assert.equal(Object.values(store.workspaces).flat().find((item: any) => item.approvalId === "approval:docs-ambiguous")?.status, "pending", "Docs intent must be durable before batchUpdate"); } }); const ambiguousDocsFailure = await channels.executeChannelOutboundDeliveryAsync(ambiguousDocsDraft, "approval:docs-ambiguous", true); assert.equal(ambiguousDocsFailure.status, "failed"); const ambiguousDocsWrite = JSON.parse(requests.at(-1)?.body ?? "{}"); const ambiguousNamedRange = ambiguousDocsWrite.requests[1].createNamedRange.name; const docsRequestCountAfterAmbiguousWrite = requests.length; responses.push({ body: { documentId, title: "Release", revisionId: "rev-after-ambiguous", namedRanges: { [ambiguousNamedRange]: { name: ambiguousNamedRange, namedRanges: [{ namedRangeId: "named-range-receipt-1", name: ambiguousNamedRange, ranges: [{ startIndex: 49, endIndex: 67 }] }] } }, body: { content: [{ endIndex: 68 }] } } }); const recoveredDocs = await channels.executeChannelOutboundDeliveryAsync(ambiguousDocsDraft, "approval:docs-ambiguous-retry", true); assert.equal(recoveredDocs.status, "sent"); assert.match(recoveredDocs.verification, /already exists as a document named range/); assert.equal(requests.length, docsRequestCountAfterAmbiguousWrite + 1, "Docs reconciliation must replace a second batchUpdate with one document GET"); assert.equal(requests.at(-1)?.body, "", "Docs reconciliation must be read-only");
  assert.equal((await channels.revokeChannelAdapterAuth({ adapterId: "docs-connector", workspacePath: workspace })).revoked, true); assert.equal(channels.listChannelAdapters(workspace).adapters.find((item) => item.id === "docs-connector")?.configured, false); await assert.rejects(() => channels.syncLiveChannelContext({ adapterId: "docs-connector", workspacePath: workspace, documentId }), /authorization is required/i);

  const calendarToken = "ya29.a_very_long_calendar_access_token_1234567890";
  responses.push({ body: { aud: "google-client", email: "calendar@example.test", sub: "google-calendar-user", scope: "openid email https://www.googleapis.com/auth/documents", expires_in: 3600 } }); await assert.rejects(() => channels.configureChannelProviderToken({ adapterId: "calendar-connector", workspacePath: workspace, token: calendarToken }), /Calendar read scope is required/i);
  responses.push({ body: { aud: "google-client", email: "calendar@example.test", sub: "google-calendar-user", scope: "openid email https://www.googleapis.com/auth/calendar.readonly", expires_in: 3600 } });
  const calendarConfigured = await channels.configureChannelProviderToken({ adapterId: "calendar-connector", workspacePath: workspace, token: calendarToken }); assert.equal(calendarConfigured.accountLabel, "calendar@example.test"); assert.ok(calendarConfigured.expiresAt); const calendarAdapter = channels.listChannelAdapters(workspace).adapters.find((item) => item.id === "calendar-connector"); assert.equal(calendarAdapter?.configured, true); assert.equal(calendarAdapter?.direction, "inbound"); const calendarLiveReadiness = readiness.listExternalConnectionReadiness(workspace).connections.find((item) => item.id === "calendar"); assert.equal(calendarLiveReadiness?.readOnly, true); assert.match(calendarLiveReadiness?.verification ?? "", /events\.list/); assert(!((await readFile(storePath, "utf8")).includes(calendarToken)), "Calendar token must not be persisted in plaintext");
  await assert.rejects(() => channels.syncLiveChannelContext({ adapterId: "calendar-connector", workspacePath: workspace, calendarId: "bad/id" }), /Calendar ID/i);
  await assert.rejects(() => channels.syncLiveChannelContext({ adapterId: "calendar-connector", workspacePath: workspace, calendarId: "primary", timeMin: "2026-07-01T00:00:00Z", timeMax: "2026-09-01T00:00:00Z" }), /at most 31 days/i);
  responses.push({ body: { nextPageToken: "next", items: [{ id: "event_1", summary: "Release API_TOKEN=calendar-hidden", description: "Discuss API_TOKEN=calendar-secret", location: "Room 1", start: { dateTime: "2026-07-23T09:00:00Z" }, end: { dateTime: "2026-07-23T10:00:00Z" }, htmlLink: "https://calendar.google.com/calendar/event?eid=event_1" }, { id: "event_2", summary: "All-day review", start: { date: "2026-07-24" }, end: { date: "2026-07-25" } }, { summary: "invalid" }] } });
  const calendarLive = await channels.syncLiveChannelContext({ adapterId: "calendar-connector", workspacePath: workspace, calendarId: "primary", timeMin: "2026-07-22T00:00:00Z", timeMax: "2026-07-29T00:00:00Z", limit: 10 }); assert.equal(calendarLive.items.length, 2); assert.equal(calendarLive.items[0].kind, "meeting"); assert.equal(calendarLive.truncated, true); assert(!JSON.stringify(calendarLive).includes("calendar-secret") && !JSON.stringify(calendarLive).includes("calendar-hidden")); assert.equal(requests.at(-1)?.authorization, `Bearer ${calendarToken}`); assert.match(requests.at(-1)?.url ?? "", /calendars\/primary\/events\?timeMin=2026-07-22T00%3A00%3A00.000Z&timeMax=2026-07-29T00%3A00%3A00.000Z&maxResults=10&singleEvents=true&orderBy=startTime$/);
  assert.equal((await channels.revokeChannelAdapterAuth({ adapterId: "calendar-connector", workspacePath: workspace })).revoked, true); assert.equal(channels.listChannelAdapters(workspace).adapters.find((item) => item.id === "calendar-connector")?.configured, false); await assert.rejects(() => channels.syncLiveChannelContext({ adapterId: "calendar-connector", workspacePath: workspace, calendarId: "primary" }), /authorization is required/i);
  await access(storePath);
  console.log("GitHub, Slack, Google Docs and Calendar provider credential, live sync, approval, idempotency and revoke verification passed.");
} finally { await rm(root, { recursive: true, force: true }); }
