"""Generate deterministic Python bindings from the reviewed Codex contract."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[5]
MANIFEST = ROOT / "cores/protocol/codex-app-server-stable-contract.json"
OUTPUT = ROOT / "cores/python/packages/drsai/src/drsai/backend/codex_adapter/stable_contract_generated.py"


def _literal(value: object) -> str:
    if isinstance(value, dict):
        rows = [f"    {key!r}: {_literal(item)}," for key, item in sorted(value.items())]
        return "{\n" + "\n".join(rows) + "\n}"
    if isinstance(value, (list, tuple, set, frozenset)):
        values = sorted(str(item) for item in value)
        return "frozenset({\n" + "\n".join(f"    {item!r}," for item in values) + "\n})"
    return repr(value)


def render(manifest: dict[str, object], digest: str) -> str:
    notifications = manifest["notifications"]
    requests = manifest["serverRequests"]
    assert isinstance(notifications, dict) and isinstance(requests, dict)
    client_methods = manifest["clientMethods"]
    assert isinstance(client_methods, dict)
    sections = {
        "CLIENT_METHODS": list(client_methods),
        "SERVER_REQUESTS": requests["supported"],
        "SEMANTIC_NOTIFICATIONS": notifications["semantic"],
        "USER_NOTICE_NOTIFICATIONS": notifications["user_notice"],
        "DIAGNOSTIC_NOTIFICATIONS": notifications["diagnostic"],
        "KNOWN_IGNORED_NOTIFICATIONS": notifications["known_ignored"],
        "FATAL_NOTIFICATIONS": notifications["fatal"],
        "LEGACY_NOTIFICATIONS": notifications.get("legacy", []),
    }
    lines = [
        '"""Generated by generate_codex_stable_contract.py; DO NOT EDIT."""',
        "",
        f"CONTRACT_VERSION = {int(manifest['contractVersion'])}",
        f"CONTRACT_DIGEST = {digest!r}",
        f"GENERATED_BASELINE = {_literal(manifest['generatedBaseline'])}",
        f"REVIEWED_COMPATIBLE_VERSIONS = {_literal(manifest.get('reviewedCompatibleVersions', []))}",
        f"REVIEWED_SCHEMA_SHA256 = {_literal(manifest.get('reviewedSchemaSha256', {}))}",
        f"SEMANTIC_DISPOSITIONS = {_literal(manifest.get('semanticDispositions', {}))}",
        f"CLIENT_METHOD_PARAMS = {_literal(client_methods)}",
        f"CLIENT_REQUIRED_PARAMS = {_literal(manifest.get('clientRequiredParams', {}))}",
        "",
    ]
    for name, values in sections.items():
        lines.extend([f"{name} = {_literal(values)}", ""])
    lines.extend([
        "STABLE_NOTIFICATIONS = (",
        "    SEMANTIC_NOTIFICATIONS | USER_NOTICE_NOTIFICATIONS | DIAGNOSTIC_NOTIFICATIONS",
        "    | KNOWN_IGNORED_NOTIFICATIONS | SERVER_REQUESTS | FATAL_NOTIFICATIONS | LEGACY_NOTIFICATIONS",
        ")",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = MANIFEST.read_bytes()
    manifest = json.loads(raw)
    digest = hashlib.sha256(raw).hexdigest()
    generated = render(manifest, digest)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("Codex stable-contract generated binding is stale.")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
