import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const apiSource = readFileSync(resolve(import.meta.dirname, "../../shared/api/desktopApi.ts"), "utf8");
const appSource = readFileSync(resolve(import.meta.dirname, "../../shared/renderer/src/App.tsx"), "utf8");
const discoverySource = readFileSync(resolve(import.meta.dirname, "../../../..", "cores/python/packages/drsai/src/drsai/config/model_discovery.py"), "utf8");
const schemaSource = readFileSync(resolve(import.meta.dirname, "../../../..", "cores/python/packages/drsai/src/drsai/config/schema.py"), "utf8");
const gatewaySource = readFileSync(resolve(import.meta.dirname, "../../../..", "cores/python/packages/drsai/src/drsai/backend/gateway.py"), "utf8");
const resolverSource = readFileSync(resolve(import.meta.dirname, "../../../..", "cores/python/packages/drsai/src/drsai/config/resolver.py"), "utf8");
const configSource = readFileSync(resolve(import.meta.dirname, "../../shared/main/myDrSaiConfig.ts"), "utf8");
const runtimeClientSource = readFileSync(resolve(import.meta.dirname, "../../shared/main/runtimeClient.ts"), "utf8");
const chatSource = readFileSync(resolve(import.meta.dirname, "../../shared/main/chat.ts"), "utf8");
const policySource = readFileSync(resolve(import.meta.dirname, "../../../..", "cores/python/packages/drsai/src/drsai/config/agent_model_policy.py"), "utf8");
const agentsSource = readFileSync(resolve(import.meta.dirname, "../../shared/main/agents.ts"), "utf8");
const baseAgentSource = readFileSync(resolve(import.meta.dirname, "../../../..", "cores/python/packages/drsai/src/drsai/modules/baseagent/drsaiagent.py"), "utf8");
const runtimeAgentSource = readFileSync(resolve(import.meta.dirname, "../../../..", "cores/python/packages/drsai/src/drsai/backend/runtime/agent.py"), "utf8");
const agentFactorySource = readFileSync(resolve(import.meta.dirname, "../../../..", "cores/python/packages/drsai/src/drsai/backend/run_drsai_agent_factory.py"), "utf8");
const replayExecutionSource = readFileSync(resolve(import.meta.dirname, "../../../..", "cores/python/packages/drsai/src/drsai/backend/runtime/replay_execution.py"), "utf8");
const inputResourcesSource = readFileSync(resolve(import.meta.dirname, "../../../..", "cores/python/packages/drsai/src/drsai/backend/runtime/input_resources.py"), "utf8");
const userFacingErrorsSource = readFileSync(resolve(import.meta.dirname, "../../shared/renderer/src/userFacingErrors.ts"), "utf8");

for (const contract of ["RuntimeModelRef", "RuntimeModelDescriptor", "AgentModelPolicy", "RuntimeModelCatalog"]) {
  assert.match(apiSource, new RegExp(`export interface ${contract}\\b`), `${contract} must be part of the shared Desktop contract`);
}
assert.match(apiSource, /provider_id: string;[\s\S]{0,120}model_id: string;/, "ModelRef identity must include provider and model");
assert.match(apiSource, /"image_generation" \| "image_edit"/, "image generation and editing must remain separate operations");
assert.match(apiSource, /"fresh" \| "stale" \| "offline" \| "unauthorized" \| "error"/, "catalog states must remain distinguishable");

assert.doesNotMatch(appSource, /DEFAULT_AGENT_IMAGE_MODEL/, "fixed image model preference must be removed");
assert.doesNotMatch(appSource, /Nano Banana 2 Lite/, "unwired image generation model must not be rendered");
assert.match(appSource, /onConfigureAgentCapabilityModel/, "renderer must write structured Agent capability-model policies");
assert.match(appSource, /image_understanding_model: role === "image_understanding_model"/, "image-understanding writes must use the Provider-aware policy");
assert.match(appSource, /image_generation_model: role === "image_generation_model"/, "image-generation writes must use the Provider-aware policy");
assert.match(appSource, /text_to_speech_model: role === "text_to_speech_model"/, "text-to-speech writes must use the Provider-aware policy");
assert.match(appSource, /speech_to_text_model: role === "speech_to_text_model"/, "speech-to-text writes must use the Provider-aware policy");
assert.match(appSource, /record\.imageModel/, "legacy image model values remain read-only for one-version migration compatibility");
assert.match(discoverySource, /"metadata_source": "builtin" if known else "unknown"/, "unknown discovered models must not claim generic capabilities");
assert.match(schemaSource, /vision: bool = False[\s\S]{0,100}function_calling: bool = False[\s\S]{0,100}json_output: bool = False/, "unknown capability defaults must fail closed");
assert.match(gatewaySource, /response_model=ModelDiscoveryResponse/, "Gateway OpenAPI must publish the canonical discovery response");
assert.match(gatewaySource, /@app\.get\("\/v1\/config\/runtime-models"/, "Gateway must expose one authoritative runtime model catalog");
assert.match(gatewaySource, /cached_provider_model_catalog/, "dynamic Provider discovery facts must enter the authoritative catalog");
assert.match(gatewaySource, /model-providers\/\{name\}\/references/, "Provider deletion must expose a read-only reference preflight");
assert.match(gatewaySource, /provider_references_present/, "referenced Providers must fail closed instead of silently falling back");
assert.match(configSource, /\/v1\/config\/runtime-models/, "Desktop must consume the authoritative runtime model catalog");
assert.doesNotMatch(configSource, /\/v1\/models\/config/, "Desktop model selection must not consume legacy model CRUD");
assert.doesNotMatch(configSource, /getGatewayModels/, "Desktop must not merge the OpenAI compatibility catalog into Provider choices");
assert.match(runtimeClientSource, /model_selection: provenance\.modelSelection/, "Runtime requests must carry provider-aware model selection");
assert.match(runtimeClientSource, /reasoning_effort: provenance\.metadata\.reasoning_effort/, "Runtime requests must promote reasoning effort into the typed execution contract");
assert.match(appSource, /model-provider-delete-references/, "Desktop must show affected model references before Provider deletion");
assert.match(appSource, /model-provider-delete-migrate-default/, "Desktop must offer an explicit default-model migration action");
assert.match(resolverSource, /def resolve_model_ref\(/, "Runtime resolver must accept the canonical Provider+model identity");
assert.match(resolverSource, /model_upstream_ids\.get\(model_id, model_id\)/, "canonical IDs must resolve to an explicit upstream request ID");
assert.match(resolverSource, /is not configured for provider/, "models outside Provider membership must fail closed");
assert.match(policySource, /class AgentModelPolicyConflict/, "Agent policy persistence must define revision conflicts");
assert.match(policySource, /expected_revision is not None and expected_revision != current_revision/, "Agent policy writes must enforce optimistic concurrency");
assert.match(gatewaySource, /\/v1\/config\/agents\/\{agent_id\}\/models/, "Gateway must own local OpenDrSai Agent model policies");
assert.match(chatSource, /getMyDrSaiAgentModelPolicy\("my-drsai"\)/, "local Runtime execution must resolve its persisted Agent policy");
assert.doesNotMatch(chatSource, /model_id: request\.model/, "renderer naked model strings must not override local OpenDrSai policy");
assert.match(appSource, /AGENT_MODEL_POLICY_MIGRATION_KEY/, "legacy renderer preferences must have a one-time migration marker");
assert.doesNotMatch(agentsSource, /model: "deepseek-v4-pro"/, "Agent Square must not hard-code the local OpenDrSai model");
assert.match(agentsSource, /getMyDrSaiAgentModelPolicy\("my-drsai"\)/, "Agent Square must display the effective persisted policy");
assert.match(gatewaySource, /def _validate_runtime_reasoning_effort\(/, "Gateway must validate reasoning effort against the exact resolved model");
assert.match(runtimeAgentSource, /reasoning_effort: str \| None = None/, "Runtime Agent execution must bind reasoning effort to one immutable request definition");
assert.match(baseAgentSource, /extra_create_args\["reasoning_effort"\] = effort/, "validated reasoning effort must reach the upstream model request");
assert.match(appSource, /normalizeRuntimeErrorEnvelope\(error\)\.code === "config_conflict"/, "revision conflicts must use structured errors rather than user-facing copy parsing");
assert.match(gatewaySource, /def _validate_runtime_model_admission\(/, "Run admission must revalidate the exact model against the authoritative catalog");
assert.match(gatewaySource, /"model_catalog_changed"/, "stale catalog selections must fail with a stable recoverable code");
assert.match(gatewaySource, /"model_capability_unsupported"/, "Full Agent Runtime capability admission must fail closed");
assert.match(gatewaySource, /model_provider=resolved_model\.provider\.name/, "effective Provider identity must enter the request-scoped Agent binding");
assert.match(gatewaySource, /requested_binding != current_binding/, "Agent clients must not be reused across Provider or revision bindings");
assert.match(agentFactorySource, /resolve_model_ref\([\s\S]{0,220}provider_id=model_provider/, "Agent factory must construct the client from the exact Provider-aware ModelRef");
assert.match(gatewaySource, /"upstream_model_id": resolved_model\.model/, "Run Manifest must record the real upstream model ID");
assert.match(gatewaySource, /"exact_revision_match": not replay_degraded_reasons/, "Replay evidence must explicitly state whether the model revision remains exact");
assert.match(replayExecutionSource, /"model_selection": dict\(model\) if model else None/, "Replay execution must preserve Provider-aware model selection");
assert.match(chatSource, /NATIVE_IMAGE_FILE_LIMIT_BYTES = 20 \* 1024 \* 1024/, "Desktop must bound native images before creating a Run");
assert.match(chatSource, /mime: imageMime/, "Desktop staging must preserve detected image MIME in OAEP resources");
assert.match(inputResourcesSource, /PILImage\.open\(path\)[\s\S]{0,180}opened\.verify\(\)/, "Runtime admission must decode and verify native images");
assert.match(inputResourcesSource, /MultiModalMessage[\s\S]{0,800}Image\.from_file\(target\)/, "OpenDrSai must pass a native image object into the Agent message");
assert.match(gatewaySource, /def _validate_runtime_multimodal_admission\(/, "Gateway must admit images only when the selected primary model is vision-capable");
assert.match(gatewaySource, /"model_image_input_unsupported"/, "non-vision image input must use a stable recoverable error");
assert.doesNotMatch(baseAgentSource, /return remove_images\(messages\)/, "Agent must never silently strip images from user context");
assert.match(baseAgentSource, /Model does not support vision and image was provided/, "Agent must fail closed if a non-vision client receives an image");
assert.match(gatewaySource, /model_evidence\["multimodal_input"\] = multimodal_input/, "Manifest must bind privacy-safe multimodal evidence");
assert.match(userFacingErrorsSource, /图片附件和输入内容已保留/, "Renderer recovery must tell users that image input was preserved");
assert.match(schemaSource, /model_operations: Mapping/, "Provider configuration must own model-scoped image operation declarations");
assert.match(gatewaySource, /core_tools = \[image_generation, image_edit\]/, "production OpenDrSai Agent must receive native image tools");
assert.match(appSource, /testId: "agent-image-understanding-model-setting"/, "declared image input capability must drive image understanding selection");
assert.match(appSource, /testId: "agent-image-generation-model-setting"/, "declared image output capability must drive image generation selection");
assert.match(appSource, /testId: "agent-text-to-speech-model-setting"/, "declared audio output capability must drive text-to-speech selection");
assert.match(appSource, /testId: "agent-speech-to-text-model-setting"/, "declared audio input capability must drive speech-to-text selection");

console.log("OpenDrSai P3 model convergence contracts verified: one Provider catalog, exact Runtime binding/evidence, native multimodal admission, and capability-gated image operations.");
