import { createHash, randomUUID } from "node:crypto";
import { join } from "node:path";
import { homedir } from "node:os";
import type { DesktopBackgroundTask, DesktopBackgroundTaskActionRequest, DesktopBackgroundTaskEnqueueRequest, DesktopBackgroundTaskListRequest, DesktopBackgroundTaskRecoveryResult, DesktopBackgroundTaskStatus, DesktopBackgroundTaskUpdateRequest, DesktopWorkflowRun } from "../api/desktopApi";
import { readDurableJson, writeDurableJson } from "./durableJsonStore";
import { redactDesktopSecrets } from "./secretRedaction";
import { requireAuthContext } from "./auth";

type Store = { schemaVersion: 2; workspaces: Record<string, DesktopBackgroundTask[]> };
type OwnerResolver = () => Promise<string | undefined>;
const ACTIVE = new Set<DesktopBackgroundTaskStatus>(["queued", "running", "waiting_approval"]);
const MAX_BACKGROUND_TASK_STORE_BYTES = 64 * 1024 * 1024;
const TRANSITIONS: Record<DesktopBackgroundTaskStatus, DesktopBackgroundTaskStatus[]> = {
  queued: ["running", "waiting_approval", "blocked", "completed", "failed", "cancelled"], running: ["waiting_approval", "blocked", "completed", "failed", "cancelled"], waiting_approval: ["queued", "running", "blocked", "cancelled"], blocked: ["queued", "cancelled"], failed: ["queued", "cancelled"], completed: [], cancelled: ["queued"],
};

export class BackgroundTaskStore {
  #queue = Promise.resolve();
  constructor(readonly filePath: string, readonly ownerResolver: OwnerResolver = async () => undefined) {}

  list(raw: unknown = {}): Promise<DesktopBackgroundTask[]> { return this.#run(async () => { const request = listRequest(raw); const owner = await this.ownerResolver(); const store = await this.#read(); return (request.workspacePath ? store.workspaces[key(request.workspacePath)] ?? [] : Object.values(store.workspaces).flat()).filter((task) => (!request.workspacePath || task.workspacePath === request.workspacePath) && (!owner || !task.ownerUserId || task.ownerUserId === owner)).sort(compare).slice(0, request.limit ?? 50).map(clone); }); }
  enqueue(raw: unknown): Promise<DesktopBackgroundTask> { return this.#run(async () => { const request = enqueueRequest(raw); const ownerUserId = await this.ownerResolver(); const store = await this.#read(); const tasks = store.workspaces[key(request.workspacePath)] ?? []; const duplicate = request.idempotencyKey ? tasks.find((task) => task.idempotencyKey === request.idempotencyKey && (!ownerUserId || task.ownerUserId === ownerUserId)) : undefined; if (duplicate) return clone(duplicate); const now = new Date().toISOString(); const task: DesktopBackgroundTask = { id: `background-task:${request.kind}:${randomUUID()}`, ...(ownerUserId ? { ownerUserId } : {}), kind: request.kind, source: request.source, title: request.title, status: request.status ?? "queued", createdAt: now, updatedAt: now, ...(request.workspacePath ? { workspacePath: request.workspacePath } : {}), ...(request.targetId ? { targetId: request.targetId } : {}), ...(request.approvalId ? { approvalId: request.approvalId } : {}), ...(request.currentStep ? { currentStep: request.currentStep } : {}), ...(request.progress !== undefined ? { progress: request.progress } : {}), ...(request.planSteps ? { planSteps: request.planSteps } : {}), ...(request.planAdjustments ? { planAdjustments: request.planAdjustments } : {}), ...(request.completedSteps ? { completedSteps: request.completedSteps } : {}), ...(request.pendingDecisions ? { pendingDecisions: request.pendingDecisions } : {}), message: request.message ?? "Background task is queued.", verification: request.verification ?? "Track lifecycle state and verify the final result.", ...(request.deliverySummary ? { deliverySummary: request.deliverySummary } : {}), ...(request.idempotencyKey ? { idempotencyKey: request.idempotencyKey } : {}), attempt: 1, maxAttempts: request.maxAttempts ?? 3 }; await this.#put(store, task); return clone(task); }); }
  update(raw: unknown): Promise<DesktopBackgroundTask> { return this.#run(async () => { const request = updateRequest(raw); const owner = await this.ownerResolver(); const store = await this.#read(); const found = locate(store, request.taskId, owner); if (!found) throw new Error("Background task was not found."); const current = found.tasks[found.index]; if (request.status !== current.status && !TRANSITIONS[current.status].includes(request.status)) throw new Error(`Background task transition ${current.status} -> ${request.status} is not allowed.`); const updated = merge(current, request); found.tasks[found.index] = updated; await this.#write(store); return clone(updated); }); }
  cancel(raw: unknown): Promise<DesktopBackgroundTask> { return this.#run(async () => { const request = actionRequest(raw); const owner = await this.ownerResolver(); const store = await this.#read(); const found = locate(store, request.taskId, owner); if (!found) throw new Error("Background task was not found."); const current = found.tasks[found.index]; if (current.status === "completed") throw new Error("Completed background tasks cannot be cancelled."); if (current.status === "cancelled") return clone(current); const now = new Date().toISOString(); const updated = { ...current, status: "cancelled" as const, updatedAt: now, cancelledAt: now, progress: current.progress, message: request.reason ?? "Background task was cancelled." }; found.tasks[found.index] = updated; await this.#write(store); return clone(updated); }); }
  retry(raw: unknown): Promise<DesktopBackgroundTask> { return this.#run(async () => { const request = actionRequest(raw); const owner = await this.ownerResolver(); const store = await this.#read(); const found = locate(store, request.taskId, owner); if (!found) throw new Error("Background task was not found."); const current = found.tasks[found.index]; if (current.status !== "failed" && current.status !== "blocked" && current.status !== "cancelled") throw new Error("Only failed, blocked or cancelled background tasks can be retried."); const attempt = (current.attempt ?? 1) + 1; if (attempt > (current.maxAttempts ?? 3)) throw new Error("Background task retry limit was reached."); const now = new Date().toISOString(); const updated: DesktopBackgroundTask = { ...current, status: "queued", updatedAt: now, attempt, retryOfTaskId: current.retryOfTaskId ?? current.id, progress: 0, message: request.reason ?? `Retry attempt ${attempt} is queued.`, cancelledAt: undefined, recoveredAt: undefined }; found.tasks[found.index] = updated; await this.#write(store); return clone(updated); }); }
  recover(): Promise<DesktopBackgroundTaskRecoveryResult> { return this.#run(async () => { const owner = await this.ownerResolver(); const store = await this.#read(); const generatedAt = new Date().toISOString(); const tasks: DesktopBackgroundTask[] = []; for (const rows of Object.values(store.workspaces)) for (let index = 0; index < rows.length; index += 1) { const task = rows[index]; if (owner && task.ownerUserId && task.ownerUserId !== owner || !ACTIVE.has(task.status)) continue; const status = task.status === "running" ? "queued" : task.status; const recovered = { ...task, status, updatedAt: generatedAt, recoveredAt: generatedAt, message: task.status === "running" ? "Recovered after restart; explicit dispatch is required." : task.message }; rows[index] = recovered; tasks.push(clone(recovered)); } if (tasks.length) await this.#write(store); return { generatedAt, recovered: tasks.length, tasks }; }); }
  upsertWorkflow(run: DesktopWorkflowRun): Promise<DesktopBackgroundTask> { return this.#run(async () => { const ownerUserId = await this.ownerResolver(); const store = await this.#read(); const rows = store.workspaces[key(run.workspacePath)] ?? []; const existing = rows.find((task) => task.kind === "workflow_run" && task.targetId === run.id); const now = new Date().toISOString(); const task: DesktopBackgroundTask = { ...(existing ?? { id: `background-task:workflow_run:${randomUUID()}`, kind: "workflow_run", source: "workflow", title: run.name, createdAt: now, attempt: 1, maxAttempts: 3 }), ...(ownerUserId ? { ownerUserId } : {}), status: run.status === "complete" ? "completed" : run.status === "blocked" ? "blocked" : run.status === "waiting_approval" ? "waiting_approval" : "running", updatedAt: now, ...(run.workspacePath ? { workspacePath: run.workspacePath } : {}), targetId: run.id, ...(run.approvalId ? { approvalId: run.approvalId } : {}), ...(run.currentStepId ? { currentStep: run.currentStepId } : {}), progress: run.steps.length ? Math.round(run.steps.filter((step) => step.status === "completed").length / run.steps.length * 100) : 0, completedSteps: run.steps.filter((step) => step.status === "completed").map((step) => step.title), pendingDecisions: run.steps.filter((step) => step.status === "waiting_approval").map((step) => step.title), message: run.message, verification: run.verification, idempotencyKey: `workflow:${run.id}` }; await this.#put(store, task); return clone(task); }); }
  async #put(store: Store, task: DesktopBackgroundTask): Promise<void> { const workspaceKey = key(task.workspacePath); const rows = store.workspaces[workspaceKey] ?? []; const index = rows.findIndex((item) => item.id === task.id || task.idempotencyKey && item.idempotencyKey === task.idempotencyKey && item.ownerUserId === task.ownerUserId); store.workspaces[workspaceKey] = (index >= 0 ? rows.map((item, row) => row === index ? task : item) : [task, ...rows]).sort(compare).slice(0, 100); await this.#write(store); }
  async #read(): Promise<Store> { return (await readDurableJson(this.filePath, decodeStore, { maxBytes: MAX_BACKGROUND_TASK_STORE_BYTES }))?.value ?? { schemaVersion: 2, workspaces: {} }; }
  async #write(store: Store): Promise<void> { await writeDurableJson(this.filePath, { ...store, schemaVersion: 2 }, { maxBytes: MAX_BACKGROUND_TASK_STORE_BYTES }); }
  #run<T>(operation: () => Promise<T>): Promise<T> { const run = this.#queue.catch(() => undefined).then(operation); this.#queue = run.then(() => undefined, () => undefined); return run; }
}

function listRequest(raw: unknown): DesktopBackgroundTaskListRequest & { limit: number } { const row = object(raw); return { ...(row.workspacePath === undefined ? {} : { workspacePath: text(row.workspacePath, "Workspace path", 4096) }), limit: Math.max(1, Math.min(100, Math.floor(Number(row.limit) || 50))) }; }
function enqueueRequest(raw: unknown): DesktopBackgroundTaskEnqueueRequest { const row = object(raw, true); const kinds = ["chat_run", "workflow_run", "agent_run", "connector_sync", "scheduled_monitor", "presentation_generation"]; const sources = ["chat", "workflow", "agent", "connector", "manual", "scheduled", "monitor", "presentation"]; if (!kinds.includes(String(row.kind)) || !sources.includes(String(row.source))) throw new Error("Background task kind or source is invalid."); const status = row.status === undefined ? undefined : taskStatus(row.status); return { kind: row.kind as DesktopBackgroundTaskEnqueueRequest["kind"], source: row.source as DesktopBackgroundTaskEnqueueRequest["source"], title: text(row.title, "Background task title"), ...(row.workspacePath === undefined ? {} : { workspacePath: text(row.workspacePath, "Workspace path", 4096) }), ...(row.targetId === undefined ? {} : { targetId: text(row.targetId, "Target id") }), ...(row.approvalId === undefined ? {} : { approvalId: text(row.approvalId, "Approval id") }), ...(row.currentStep === undefined ? {} : { currentStep: text(row.currentStep, "Current step", 500) }), ...(row.progress === undefined ? {} : { progress: progress(row.progress) }), ...(status ? { status } : {}), ...(row.message === undefined ? {} : { message: text(row.message, "Message", 2000) }), ...(row.verification === undefined ? {} : { verification: text(row.verification, "Verification", 2000) }), ...(row.idempotencyKey === undefined ? {} : { idempotencyKey: idempotency(row.idempotencyKey) }), ...(row.maxAttempts === undefined ? {} : { maxAttempts: integer(row.maxAttempts, 1, 10) }), ...(row.planSteps === undefined ? {} : { planSteps: boundedJson(row.planSteps, "Plan steps", 64_000) as NonNullable<DesktopBackgroundTaskEnqueueRequest["planSteps"]> }), ...(row.planAdjustments === undefined ? {} : { planAdjustments: boundedJson(row.planAdjustments, "Plan adjustments", 64_000) as NonNullable<DesktopBackgroundTaskEnqueueRequest["planAdjustments"]> }), ...(row.completedSteps === undefined ? {} : { completedSteps: boundedJson(row.completedSteps, "Completed steps", 32_000) as string[] }), ...(row.pendingDecisions === undefined ? {} : { pendingDecisions: boundedJson(row.pendingDecisions, "Pending decisions", 32_000) as string[] }), ...(row.deliverySummary === undefined ? {} : { deliverySummary: boundedJson(row.deliverySummary, "Delivery summary", 512_000) as NonNullable<DesktopBackgroundTaskEnqueueRequest["deliverySummary"]> }) }; }
function updateRequest(raw: unknown): DesktopBackgroundTaskUpdateRequest { const row = object(raw, true); return { taskId: taskId(row.taskId), status: taskStatus(row.status), ...(row.title === undefined ? {} : { title: text(row.title, "Title") }), ...(row.message === undefined ? {} : { message: text(row.message, "Message", 2000) }), ...(row.currentStep === undefined ? {} : { currentStep: text(row.currentStep, "Current step", 500) }), ...(row.progress === undefined ? {} : { progress: progress(row.progress) }), ...(row.verification === undefined ? {} : { verification: text(row.verification, "Verification", 2000) }), ...(row.planSteps === undefined ? {} : { planSteps: boundedJson(row.planSteps, "Plan steps", 64_000) as NonNullable<DesktopBackgroundTaskUpdateRequest["planSteps"]> }), ...(row.planAdjustments === undefined ? {} : { planAdjustments: boundedJson(row.planAdjustments, "Plan adjustments", 64_000) as NonNullable<DesktopBackgroundTaskUpdateRequest["planAdjustments"]> }), ...(row.completedSteps === undefined ? {} : { completedSteps: boundedJson(row.completedSteps, "Completed steps", 32_000) as string[] }), ...(row.pendingDecisions === undefined ? {} : { pendingDecisions: boundedJson(row.pendingDecisions, "Pending decisions", 32_000) as string[] }), ...(row.deliverySummary === undefined ? {} : { deliverySummary: boundedJson(row.deliverySummary, "Delivery summary", 512_000) as NonNullable<DesktopBackgroundTaskUpdateRequest["deliverySummary"]> }) }; }
function actionRequest(raw: unknown): DesktopBackgroundTaskActionRequest { const row = object(raw, true); return { taskId: taskId(row.taskId), ...(row.reason === undefined ? {} : { reason: text(row.reason, "Reason", 1000) }) }; }
function merge(current: DesktopBackgroundTask, request: DesktopBackgroundTaskUpdateRequest): DesktopBackgroundTask { return { ...current, status: request.status, updatedAt: new Date().toISOString(), ...(request.title !== undefined ? { title: request.title } : {}), ...(request.message !== undefined ? { message: request.message } : {}), ...(request.currentStep !== undefined ? { currentStep: request.currentStep } : {}), ...(request.progress !== undefined ? { progress: request.progress } : {}), ...(request.verification !== undefined ? { verification: request.verification } : {}), ...(request.planSteps !== undefined ? { planSteps: request.planSteps } : {}), ...(request.planAdjustments !== undefined ? { planAdjustments: request.planAdjustments } : {}), ...(request.completedSteps !== undefined ? { completedSteps: request.completedSteps } : {}), ...(request.pendingDecisions !== undefined ? { pendingDecisions: request.pendingDecisions } : {}), ...(request.deliverySummary !== undefined ? { deliverySummary: request.deliverySummary } : {}) }; }
function object(raw: unknown, required = false): Record<string, unknown> { if (!raw || typeof raw !== "object") { if (required) throw new Error("Background task request is invalid."); return {}; } return raw as Record<string, unknown>; }
function text(value: unknown, label: string, max = 240): string { if (typeof value !== "string" || !value.trim() || value.length > max || /[\0\r\n]/.test(value) && label.includes("path")) throw new Error(`${label} is invalid.`); const result = value.trim(); if (redactDesktopSecrets(result) !== result) throw new Error(`${label} must not contain credentials.`); return result; }
function taskId(value: unknown): string { if (typeof value !== "string" || !/^background-task:[a-z_]+:(?:[a-z0-9]+:)?[A-Za-z0-9-]{36}$/.test(value)) throw new Error("Background task id is invalid."); return value; }
function idempotency(value: unknown): string { if (typeof value !== "string" || !/^[A-Za-z0-9._:-]{8,200}$/.test(value)) throw new Error("Background task idempotency key is invalid."); return value; }
function taskStatus(value: unknown): DesktopBackgroundTaskStatus { if (!["queued", "running", "waiting_approval", "blocked", "completed", "failed", "cancelled"].includes(String(value))) throw new Error("Background task status is invalid."); return value as DesktopBackgroundTaskStatus; }
function progress(value: unknown): number { const number = Number(value); if (!Number.isFinite(number) || number < 0 || number > 100) throw new Error("Background task progress is invalid."); return Math.round(number); }
function integer(value: unknown, min: number, max: number): number { const number = Number(value); if (!Number.isInteger(number) || number < min || number > max) throw new Error("Background task limit is invalid."); return number; }
function locate(store: Store, id: string, owner?: string): { tasks: DesktopBackgroundTask[]; index: number } | null { for (const tasks of Object.values(store.workspaces)) { const index = tasks.findIndex((task) => task.id === id && (!owner || !task.ownerUserId || task.ownerUserId === owner)); if (index >= 0) return { tasks, index }; } return null; }
function key(path?: string): string { return path ? createHash("sha256").update(path.toLowerCase()).digest("hex") : "__global__"; }
function compare(a: DesktopBackgroundTask, b: DesktopBackgroundTask): number { return b.updatedAt.localeCompare(a.updatedAt); }
function clone(task: DesktopBackgroundTask): DesktopBackgroundTask { return structuredClone(task); }
function boundedJson(value: unknown, label: string, maxBytes: number): unknown { const serialized = JSON.stringify(value); if (!serialized || Buffer.byteLength(serialized, "utf8") > maxBytes || redactDesktopSecrets(serialized) !== serialized) throw new Error(`${label} is invalid or contains credentials.`); return structuredClone(value); }
function isTask(value: unknown): value is DesktopBackgroundTask { const task = value as DesktopBackgroundTask; return Boolean(task && typeof task.id === "string" && /^background-task:[a-z_]+:(?:[a-z0-9]+:)?[A-Za-z0-9-]{36}$/.test(task.id) && typeof task.title === "string" && typeof task.message === "string" && typeof task.verification === "string" && ["queued", "running", "waiting_approval", "blocked", "completed", "failed", "cancelled"].includes(task.status)); }
function decodeStore(value: unknown): Store { if (!value || typeof value !== "object" || !("workspaces" in value) || !value.workspaces || typeof value.workspaces !== "object" || Array.isArray(value.workspaces)) throw new Error("Background task store schema is invalid."); const workspaces: Store["workspaces"] = {}; for (const [workspaceKey, rows] of Object.entries(value.workspaces)) if (/^(?:[a-f0-9]{64}|__global__)$/.test(workspaceKey) && Array.isArray(rows)) { const tasks = rows.filter(isTask).slice(0, 100); if (tasks.length) workspaces[workspaceKey] = tasks; } return { schemaVersion: 2, workspaces }; }
const root = join(process.env.DRSAI_HOME?.trim() || join(homedir(), ".drsai"), "desktop");
export const backgroundTaskStore = new BackgroundTaskStore(join(root, "background-tasks.json"), async () => { try { return (await requireAuthContext()).userId; } catch { return undefined; } });
export const listBackgroundTasks = (raw?: unknown) => backgroundTaskStore.list(raw);
export const listOwnedBackgroundTasks = (raw?: unknown) => backgroundTaskStore.list(raw);
export const enqueueBackgroundTask = (raw: unknown) => backgroundTaskStore.enqueue(raw);
export const updateBackgroundTask = (raw: unknown) => backgroundTaskStore.update(raw);
