import { createHash, randomUUID } from "node:crypto";
import { chmod, mkdir, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import type { DesktopProjectSkillDraft, DesktopProjectSkillDraftCreateRequest, DesktopProjectSkillInstallResult, DesktopProjectSkillPublishResult } from "../api/desktopApi";
import { replaceFileSafely } from "./atomicFileReplace";
import { redactDesktopSecrets } from "./secretRedaction";

type Store = { schemaVersion: 2; workspaces: Record<string, DesktopProjectSkillDraft[]> };
export class ProjectSkillStore {
  #queue = Promise.resolve();
  readonly #draftsRoot: string; readonly #installedRoot: string; readonly #submissionsRoot: string;
  constructor(readonly filePath: string, root = dirname(filePath)) { this.#draftsRoot = join(root, "skill-drafts"); this.#installedRoot = join(root, "installed-skills"); this.#submissionsRoot = join(root, "skill-marketplace-submissions"); }
  list(raw: unknown): Promise<DesktopProjectSkillDraft[]> { return this.#run(async () => { const request = listRequest(raw); return ((await this.#read()).workspaces[key(request.workspacePath)] ?? []).slice().sort(compare).slice(0, request.limit ?? 20); }); }
  create(raw: unknown): Promise<DesktopProjectSkillDraft> { return this.#run(async () => { const request = createRequest(raw); const store = await this.#read(); const workspaceKey = key(request.workspacePath); const now = new Date().toISOString(); const title = request.title ?? inferTitle(request.content); const slug = `${slugify(title)}-${randomUUID().slice(0, 8)}`; const summary = request.content.replace(/\s+/g, " ").slice(0, 220); const skillMarkdown = renderSkill(title, slug, summary, request.content); const draftPath = join(this.#draftsRoot, workspaceKey, slug, "SKILL.md"); const draft: DesktopProjectSkillDraft = { id: `skill-draft-${randomUUID()}`, workspacePath: request.workspacePath, title, slug, summary, skillMarkdown, draftPath, createdAt: now, updatedAt: now, source: request.source ?? "project_memory", ...(request.memoryEntryId ? { memoryEntryId: request.memoryEntryId } : {}) }; await atomicManagedFile(draftPath, skillMarkdown); store.workspaces[workspaceKey] = [draft, ...(store.workspaces[workspaceKey] ?? [])].sort(compare).slice(0, 100); await this.#write(store); return draft; }); }
  install(raw: unknown): Promise<DesktopProjectSkillInstallResult> { return this.#run(async () => { const request = actionRequest(raw, "desktop_local"); const store = await this.#read(); const workspaceKey = key(request.workspacePath); const drafts = store.workspaces[workspaceKey] ?? []; const draft = requireDraft(drafts, request.draftId); validateStoredDraft(draft); const installDir = join(this.#installedRoot, workspaceKey, draft.slug); const installPath = join(installDir, "SKILL.md"); const alreadyInstalled = Boolean(draft.installedAt && draft.installPath === installPath && await sameFile(installPath, draft.skillMarkdown)); const now = new Date().toISOString(); if (!alreadyInstalled) await atomicManagedDirectory(installDir, [{ name: "SKILL.md", content: draft.skillMarkdown }]); const installedAt = draft.installedAt ?? now; const next = { ...draft, installedAt, installPath, updatedAt: now }; store.workspaces[workspaceKey] = drafts.map((item) => item.id === draft.id ? next : item).sort(compare); await this.#write(store); return { workspacePath: request.workspacePath, draftId: draft.id, title: draft.title, slug: draft.slug, target: "desktop_local", installedAt, installPath, alreadyInstalled }; }); }
  publish(raw: unknown): Promise<DesktopProjectSkillPublishResult> { return this.#run(async () => { const request = publishRequest(raw); const store = await this.#read(); const workspaceKey = key(request.workspacePath); const drafts = store.workspaces[workspaceKey] ?? []; const draft = requireDraft(drafts, request.draftId); validateStoredDraft(draft); const submissionDir = join(this.#submissionsRoot, workspaceKey, draft.slug); const submissionPath = join(submissionDir, "submission.json"); const alreadyPublished = Boolean(draft.publishedAt && draft.marketplaceSubmissionPath === submissionPath && await sameFile(join(submissionDir, "SKILL.md"), draft.skillMarkdown)); const now = new Date().toISOString(); const publishedAt = draft.publishedAt ?? now; const submission = { schemaVersion: 1, target: "marketplace_submission", workspacePath: request.workspacePath, draftId: draft.id, title: draft.title, slug: draft.slug, summary: draft.summary, source: draft.source, memoryEntryId: draft.memoryEntryId ?? null, contentSha256: createHash("sha256").update(draft.skillMarkdown).digest("hex"), createdAt: draft.createdAt, publishedAt, notes: request.notes ?? "", verification: "Review submission.json and SKILL.md before uploading to a curated marketplace." }; if (!alreadyPublished) await atomicManagedDirectory(submissionDir, [{ name: "submission.json", content: `${JSON.stringify(submission, null, 2)}\n` }, { name: "SKILL.md", content: draft.skillMarkdown }]); const next = { ...draft, publishedAt, marketplaceSubmissionPath: submissionPath, updatedAt: now }; store.workspaces[workspaceKey] = drafts.map((item) => item.id === draft.id ? next : item).sort(compare); await this.#write(store); return { workspacePath: request.workspacePath, draftId: draft.id, title: draft.title, slug: draft.slug, target: "marketplace_submission", publishedAt, submissionPath, alreadyPublished, verification: submission.verification }; }); }
  async #read(): Promise<Store> { try { const parsed = JSON.parse(await readFile(this.filePath, "utf8")) as { workspaces?: unknown }; const workspaces: Store["workspaces"] = {}; if (parsed.workspaces && typeof parsed.workspaces === "object") for (const [workspaceKey, values] of Object.entries(parsed.workspaces)) if (/^[a-f0-9]{64}$/.test(workspaceKey) && Array.isArray(values)) { const drafts = values.filter(isDraft).sort(compare).slice(0, 100); if (drafts.length) workspaces[workspaceKey] = drafts; } return { schemaVersion: 2, workspaces }; } catch { return { schemaVersion: 2, workspaces: {} }; } }
  async #write(store: Store): Promise<void> { await mkdir(dirname(this.filePath), { recursive: true }); const temporary = `${this.filePath}.${process.pid}.${randomUUID()}.tmp`; try { await writeFile(temporary, `${JSON.stringify({ ...store, schemaVersion: 2 }, null, 2)}\n`, { encoding: "utf8", mode: 0o600 }); await replaceFileSafely(temporary, this.filePath); await chmod(this.filePath, 0o600).catch(() => undefined); } finally { await rm(temporary, { force: true }); } }
  #run<T>(operation: () => Promise<T>): Promise<T> { const run = this.#queue.catch(() => undefined).then(operation); this.#queue = run.then(() => undefined, () => undefined); return run; }
}
function workspacePath(value: unknown): string { if (typeof value !== "string" || !value.trim() || value.length > 4096 || /[\r\n\0]/.test(value)) throw new Error("Project skill workspace path is invalid."); return value.trim(); }
function sourceContent(value: unknown): string { if (typeof value !== "string" || !value.trim() || value.length > 8000) throw new Error("Project skill content is invalid."); const result = value.trim(); if (redactDesktopSecrets(result) !== result) throw new Error("Project skill content must not contain credentials or secrets."); return result; }
function listRequest(raw: unknown): { workspacePath: string; limit?: number } { if (!raw || typeof raw !== "object") throw new Error("Project skill list request is invalid."); const value = raw as Record<string, unknown>; return { workspacePath: workspacePath(value.workspacePath), ...(value.limit === undefined ? {} : { limit: Math.max(1, Math.min(100, Math.floor(Number(value.limit) || 20))) }) }; }
function createRequest(raw: unknown): DesktopProjectSkillDraftCreateRequest { if (!raw || typeof raw !== "object") throw new Error("Project skill create request is invalid."); const value = raw as Record<string, unknown>; if (value.memoryEntryId !== undefined && (typeof value.memoryEntryId !== "string" || !/^memory-[A-Za-z0-9-]{36}$/.test(value.memoryEntryId))) throw new Error("Project memory id is invalid."); return { workspacePath: workspacePath(value.workspacePath), content: sourceContent(value.content), ...(typeof value.title === "string" && value.title.trim() ? { title: value.title.trim().slice(0, 80) } : {}), ...(typeof value.memoryEntryId === "string" ? { memoryEntryId: value.memoryEntryId } : {}), source: value.source === "manual" ? "manual" : "project_memory" }; }
function actionRequest(raw: unknown, target: "desktop_local"): { workspacePath: string; draftId: string; target: "desktop_local" } { if (!raw || typeof raw !== "object") throw new Error("Project skill install request is invalid."); const value = raw as Record<string, unknown>; if (typeof value.draftId !== "string" || !/^skill-draft-[A-Za-z0-9-]{36}$/.test(value.draftId) || (value.target !== undefined && value.target !== target)) throw new Error("Project skill install request is invalid."); return { workspacePath: workspacePath(value.workspacePath), draftId: value.draftId, target }; }
function publishRequest(raw: unknown): { workspacePath: string; draftId: string; notes?: string } { if (!raw || typeof raw !== "object") throw new Error("Project skill publish request is invalid."); const value = raw as Record<string, unknown>; if (typeof value.draftId !== "string" || !/^skill-draft-[A-Za-z0-9-]{36}$/.test(value.draftId) || (value.target !== undefined && value.target !== "marketplace_submission")) throw new Error("Project skill publish request is invalid."); if (value.notes !== undefined && (typeof value.notes !== "string" || value.notes.length > 1000 || /\0/.test(value.notes))) throw new Error("Project skill publish notes are invalid."); return { workspacePath: workspacePath(value.workspacePath), draftId: value.draftId, ...(typeof value.notes === "string" ? { notes: value.notes.trim() } : {}) }; }
function requireDraft(drafts: DesktopProjectSkillDraft[], id: string): DesktopProjectSkillDraft { const draft = drafts.find((item) => item.id === id); if (!draft) throw new Error("Project skill draft was not found."); return draft; }
function validateStoredDraft(draft: DesktopProjectSkillDraft): void { if (draft.skillMarkdown.length > 32_000 || !/^---\nname: [a-z0-9-]+\ndescription: .+\n---\n/s.test(draft.skillMarkdown) || redactDesktopSecrets(draft.skillMarkdown) !== draft.skillMarkdown) throw new Error("Project skill draft failed integrity validation."); }
function inferTitle(content: string): string { return content.replace(/^Skill promotion candidate:\s*/i, "").split(/\r?\n/)[0].trim().slice(0, 80) || "Project memory skill"; }
function slugify(value: string): string { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48) || "project-memory-skill"; }
function yaml(value: string): string { return value.replace(/[\r\n]/g, " ").replace(/[:#]/g, "-").trim(); }
function renderSkill(title: string, slug: string, summary: string, content: string): string { return `---\nname: ${slug}\ndescription: ${yaml(summary)}\n---\n\n# ${title}\n\nUse this skill when a future OpenDrSai task matches this project lesson.\n\n## Workflow\n\n1. Read the current project state before acting.\n2. Apply this lesson only when it matches the current task.\n3. Add or update verification.\n4. Record follow-up lessons in project memory.\n\n## Project Lesson\n\n${content}\n`; }
function key(value: string): string { return createHash("sha256").update(value.toLowerCase()).digest("hex"); }
function compare(a: DesktopProjectSkillDraft, b: DesktopProjectSkillDraft): number { return b.updatedAt.localeCompare(a.updatedAt); }
function isDraft(value: unknown): value is DesktopProjectSkillDraft { const item = value as DesktopProjectSkillDraft; return Boolean(item && /^skill-draft-[A-Za-z0-9-]{36}$/.test(item.id) && typeof item.workspacePath === "string" && typeof item.title === "string" && /^[a-z0-9-]{1,64}$/.test(item.slug) && typeof item.summary === "string" && typeof item.skillMarkdown === "string" && typeof item.draftPath === "string" && typeof item.createdAt === "string" && typeof item.updatedAt === "string"); }
async function atomicManagedFile(path: string, content: string): Promise<void> { await mkdir(dirname(path), { recursive: true }); const temporary = `${path}.${process.pid}.${randomUUID()}.tmp`; try { await writeFile(temporary, content, { encoding: "utf8", mode: 0o600 }); await replaceFileSafely(temporary, path); await chmod(path, 0o600).catch(() => undefined); } finally { await rm(temporary, { force: true }); } }
async function atomicManagedDirectory(target: string, files: Array<{ name: string; content: string }>): Promise<void> { await mkdir(dirname(target), { recursive: true }); const staging = `${target}.staging-${randomUUID()}`; const backup = `${target}.backup-${randomUUID()}`; try { await mkdir(staging, { recursive: false, mode: 0o700 }); for (const file of files) await writeFile(join(staging, file.name), file.content, { encoding: "utf8", mode: 0o600 }); let existed = false; try { await stat(target); existed = true; await rename(target, backup); } catch { /* target missing */ } try { await rename(staging, target); } catch (error) { if (existed) await rename(backup, target).catch(() => undefined); throw error; } await rm(backup, { recursive: true, force: true }); } finally { await rm(staging, { recursive: true, force: true }); } }
async function sameFile(path: string, expected: string): Promise<boolean> { try { const info = await stat(path); return info.isFile() && info.size <= 32_000 && await readFile(path, "utf8") === expected; } catch { return false; } }
const dataRoot = join(process.env.DRSAI_HOME?.trim() || join(homedir(), ".drsai"), "desktop"); export const projectSkillStore = new ProjectSkillStore(join(dataRoot, "project-skill-drafts.json"), dataRoot);
export const listProjectSkillDrafts = (raw: unknown) => projectSkillStore.list(raw); export const createProjectSkillDraft = (raw: unknown) => projectSkillStore.create(raw); export const installProjectSkillDraft = (raw: unknown) => projectSkillStore.install(raw); export const publishProjectSkillDraft = (raw: unknown) => projectSkillStore.publish(raw);
