import { createHash, randomUUID } from "node:crypto";
import { join } from "node:path";
import { homedir } from "node:os";
import type { DesktopScheduledTask, DesktopScheduledTaskCadence, DesktopScheduledTaskCreateRequest, DesktopScheduledTaskDeleteResult, DesktopScheduledTaskRunItem, DesktopScheduledTaskRunResult, DesktopScheduledTaskStatus, DesktopScheduledTaskUserDefinition, DesktopScheduledTaskWorkerStatus, DesktopWorkflowRun, DesktopWorkflowRunPrepareResult, DesktopWorkflowRunStartResult } from "../api/desktopApi";
import { readDurableJson, writeDurableJson } from "./durableJsonStore";
import { createScheduledTriggerAudit, DEFAULT_MISSED_RUN_POLICY, getNextRunAfterTrigger } from "./scheduleTiming";
import { redactDesktopSecrets } from "./secretRedaction";
type Store = { schemaVersion: 2; workspaces: Record<string, DesktopScheduledTask[]> };
const MAX_SCHEDULED_TASK_STORE_BYTES = 16 * 1024 * 1024;
export interface ScheduledTaskRuntime { prepare(request: { templateId: string; workspacePath?: string; triggerKey: string }): Promise<DesktopWorkflowRunPrepareResult>; start(request: { recipe: DesktopWorkflowRunPrepareResult["recipe"]; idempotencyKey: string }): Promise<DesktopWorkflowRunStartResult>; listRuns(workspacePath?: string): Promise<DesktopWorkflowRun[]>; }
export interface ScheduledTaskWorker { runOnce(): Promise<DesktopScheduledTaskRunResult | null>; getStatus(): DesktopScheduledTaskWorkerStatus; stop(): void; }
export class ScheduledTaskStore {
  #queue = Promise.resolve(); constructor(readonly filePath: string) {}
  list(raw: unknown = {}): Promise<DesktopScheduledTask[]> { return this.#run(async () => { const request = listRequest(raw); const store = await this.#read(); return (request.workspacePath ? store.workspaces[key(request.workspacePath)] ?? [] : Object.values(store.workspaces).flat()).filter((item) => !request.workspacePath || item.workspacePath === request.workspacePath).sort(compare).slice(0, request.limit).map(clone); }); }
  create(raw: unknown): Promise<DesktopScheduledTask> { return this.#run(async () => { const request = createRequest(raw); const now = new Date().toISOString(); const task: DesktopScheduledTask = { id: `scheduled-task:${request.kind}:${randomUUID()}`, kind: request.kind, title: request.title, status: request.status ?? "enabled", cadence: request.cadence, createdAt: now, updatedAt: now, ...(request.workspacePath ? { workspacePath: request.workspacePath } : {}), target: request.target, ...(request.workflowTemplateId ? { workflowTemplateId: request.workflowTemplateId } : {}), ...(request.nextRunAt ?? nextAt(now, request.cadence) ? { nextRunAt: request.nextRunAt ?? nextAt(now, request.cadence) } : {}), approvalRequired: request.approvalRequired ?? true, message: request.message ?? "Scheduled task is configured for approval-gated execution.", verification: request.verification ?? "Verify persisted state and due trigger results.", ...(request.userDefinition ? { userDefinition: request.userDefinition } : {}), missedRunPolicy: DEFAULT_MISSED_RUN_POLICY }; const store = await this.#read(); const workspaceKey = key(task.workspacePath); store.workspaces[workspaceKey] = [task, ...(store.workspaces[workspaceKey] ?? [])].sort(compare).slice(0, 100); await this.#write(store); return clone(task); }); }
  update(raw: unknown): Promise<DesktopScheduledTask> { return this.#run(async () => { const request = updateRequest(raw); const store = await this.#read(); const found = find(store, request.taskId); if (!found) throw new Error("Scheduled task was not found."); const current = found.tasks[found.index]; const updated: DesktopScheduledTask = { ...current, status: request.status, updatedAt: new Date().toISOString(), ...(request.title ? { title: request.title } : {}), ...(request.cadence ? { cadence: request.cadence } : {}), ...(request.target ? { target: request.target } : {}), ...(request.nextRunAt !== undefined ? request.nextRunAt ? { nextRunAt: request.nextRunAt } : { nextRunAt: undefined } : {}), ...(request.message ? { message: request.message } : {}), ...(request.verification ? { verification: request.verification } : {}), ...(request.userDefinition ? { userDefinition: request.userDefinition } : {}) }; found.tasks[found.index] = updated; await this.#write(store); return clone(updated); }); }
  delete(raw: unknown): Promise<DesktopScheduledTaskDeleteResult> { return this.#run(async () => { const taskId = taskIdFrom(raw); const store = await this.#read(); const found = find(store, taskId); if (!found) return { taskId, removed: false, historyPolicy: "retain_results", message: "Task was already absent; history remains." }; const [removed] = found.tasks.splice(found.index, 1); if (!found.tasks.length) delete store.workspaces[found.key]; await this.#write(store); return { taskId, removed: true, historyPolicy: "retain_results", ...(removed.activeWorkflowRunId ? { retainedWorkflowRunId: removed.activeWorkflowRunId } : {}), message: "Future triggers deleted; Workflow history remains." }; }); }
  runDue(raw: unknown, runtime: ScheduledTaskRuntime): Promise<DesktopScheduledTaskRunResult> { return this.#run(async () => { const request = runRequest(raw); const now = new Date(request.now ?? new Date().toISOString()); if (Number.isNaN(now.getTime())) throw new Error("Scheduled task run timestamp is invalid."); const generatedAt = now.toISOString(); const store = await this.#read(); const items: DesktopScheduledTaskRunItem[] = []; const runs: DesktopWorkflowRun[] = []; const containers = request.workspacePath ? [store.workspaces[key(request.workspacePath)] ?? []] : Object.values(store.workspaces); for (const tasks of containers) for (let index = 0; index < tasks.length && items.length < request.limit; index += 1) { const task = tasks[index]; if (request.workspacePath && task.workspacePath !== request.workspacePath || !due(task, now)) continue; try { const result = await trigger(task, generatedAt, runtime); tasks[index] = result.task; items.push(result.item); if (result.run) runs.push(result.run); } catch (error) { const audit = createScheduledTriggerAudit(task, generatedAt); const message = redactDesktopSecrets(error instanceof Error ? error.message : "Scheduled Workflow trigger failed.").slice(0, 1000); tasks[index] = { ...task, updatedAt: generatedAt, lastTriggerAudit: audit, message: `Scheduled Workflow trigger failed and remains due for retry: ${message}` }; items.push({ taskId: task.id, title: task.title, status: "failed", message, reason: "workflow_trigger_failed", triggerAudit: audit }); } await this.#write(store); } return { generatedAt, checked: items.length, triggered: items.filter((item) => item.status === "started" || item.status === "queued_approval").length, reconnected: items.filter((item) => item.status === "reconnected").length, skipped: items.filter((item) => item.status === "skipped").length, failed: items.filter((item) => item.status === "failed").length, blocked: items.filter((item) => item.status === "blocked").length, items, runs }; }); }
  async #read(): Promise<Store> { return (await readDurableJson(this.filePath, decodeStore, { maxBytes: MAX_SCHEDULED_TASK_STORE_BYTES }))?.value ?? { schemaVersion: 2, workspaces: {} }; }
  async #write(store: Store): Promise<void> { await writeDurableJson(this.filePath, { ...store, schemaVersion: 2 }, { maxBytes: MAX_SCHEDULED_TASK_STORE_BYTES }); }
  #run<T>(operation: () => Promise<T>): Promise<T> { const run = this.#queue.catch(() => undefined).then(operation); this.#queue = run.then(() => undefined, () => undefined); return run; }
}
async function trigger(task: DesktopScheduledTask, now: string, runtime: ScheduledTaskRuntime): Promise<{ task: DesktopScheduledTask; item: DesktopScheduledTaskRunItem; run?: DesktopWorkflowRun }> {
  const audit = createScheduledTriggerAudit(task, now);
  const runs = task.activeWorkflowRunId ? await runtime.listRuns(task.workspacePath) : [];
  const active = runs.find((run) => run.id === task.activeWorkflowRunId);
  if (active && (active.status === "running" || active.status === "waiting_approval")) return { task: { ...task, updatedAt: now, activeWorkflowRunStatus: active.status, activeWorkflowRunUpdatedAt: active.updatedAt, lastTriggerAudit: audit, message: "Reconnected to active Workflow run." }, item: { taskId: task.id, title: task.title, status: "reconnected", message: active.resumePlan?.message ?? active.message, workflowRunId: active.id, reason: "active_workflow_run", triggerAudit: audit }, run: active };
  if (active?.status === "blocked") return { task: { ...task, status: "blocked", updatedAt: now, lastTriggerAudit: audit, message: active.message }, item: { taskId: task.id, title: task.title, status: "blocked", message: active.message, workflowRunId: active.id, reason: "active_workflow_blocked", triggerAudit: audit }, run: active };
  if (!task.workflowTemplateId) {
    const nextRunAt = getNextRunAfterTrigger(task, now);
    return { task: { ...clearActive(task), updatedAt: now, ...(nextRunAt ? { nextRunAt } : { nextRunAt: undefined }), lastTriggerAudit: audit, message: "No Workflow template is bound." }, item: { taskId: task.id, title: task.title, status: "skipped", message: "No Workflow template is bound.", ...(nextRunAt ? { nextRunAt } : {}), reason: "missing_workflow_template", triggerAudit: audit } };
  }
  const prepared = await runtime.prepare({ templateId: task.workflowTemplateId, ...(task.workspacePath ? { workspacePath: task.workspacePath } : {}), triggerKey: audit.triggerKey });
  prepared.recipe.id = scheduledRecipeId(task.workflowTemplateId, audit.triggerKey);
  if (prepared.blocked || prepared.recipe.status === "blocked") return { task: { ...task, status: "blocked", updatedAt: now, lastTriggerAudit: audit, message: prepared.reason }, item: { taskId: task.id, title: task.title, status: "blocked", message: prepared.reason, reason: prepared.reason, triggerAudit: audit } };
  if (prepared.queued || prepared.recipe.status === "approval_queued") return { task: { ...task, updatedAt: now, lastTriggerAudit: audit, message: "Waiting for Workflow approval; scheduled time is retained." }, item: { taskId: task.id, title: task.title, status: "queued_approval", message: prepared.reason, ...(prepared.recipe.approvalId ? { approvalId: prepared.recipe.approvalId } : {}), triggerAudit: audit } };
  const started = await runtime.start({ recipe: prepared.recipe, idempotencyKey: audit.triggerKey });
  const nextRunAt = getNextRunAfterTrigger(task, now);
  return { task: { ...clearActive(task), updatedAt: now, lastRunAt: now, ...(nextRunAt ? { nextRunAt } : { nextRunAt: undefined }), activeWorkflowRunId: started.run.id, activeWorkflowRunStatus: started.run.status, activeWorkflowRunUpdatedAt: started.run.updatedAt, lastTriggerAudit: audit, message: "Scheduled task started a Workflow run.", verification: started.run.verification }, item: { taskId: task.id, title: task.title, status: "started", message: started.run.message, ...(nextRunAt ? { nextRunAt } : {}), workflowRunId: started.run.id, triggerAudit: audit }, run: started.run };
}
function scheduledRecipeId(templateId: string, triggerKey: string): string { const hex = triggerKey.slice(0, 32); return `workflow:${templateId}:${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`; }
function clearActive(task: DesktopScheduledTask): DesktopScheduledTask { const { activeWorkflowRunId: _id, activeWorkflowRunStatus: _status, activeWorkflowRunUpdatedAt: _updated, ...rest } = task; return rest; }
function text(value: unknown, label: string, max = 240): string { if (typeof value !== "string" || !value.trim() || value.length > max || /\0/.test(value)) throw new Error(`${label} is invalid.`); const result = value.trim(); if (redactDesktopSecrets(result) !== result) throw new Error(`${label} must not contain credentials.`); return result; }
function path(value: unknown): string { return text(value, "Scheduled task Workspace path", 4096); } function cadence(value: unknown): DesktopScheduledTaskCadence { if (value !== "manual" && value !== "hourly" && value !== "daily" && value !== "weekly") throw new Error("Scheduled task cadence is invalid."); return value; } function status(value: unknown): DesktopScheduledTaskStatus { if (value !== "enabled" && value !== "paused" && value !== "blocked") throw new Error("Scheduled task status is invalid."); return value; }
function iso(value: unknown, optional = false): string | undefined { if (value === undefined && optional) return undefined; if (typeof value !== "string" || Number.isNaN(Date.parse(value))) throw new Error("Scheduled task timestamp is invalid."); return new Date(value).toISOString(); }
function definition(value: unknown): DesktopScheduledTaskUserDefinition { if (!value || typeof value !== "object") throw new Error("Scheduled task user definition is invalid."); const row = value as Record<string, unknown>; const timezone = text(row.timezone, "Schedule timezone", 120); try { new Intl.DateTimeFormat("en", { timeZone: timezone }); } catch { throw new Error("Schedule timezone is invalid."); } if (row.weekday !== undefined && (!Number.isInteger(row.weekday) || Number(row.weekday) < 0 || Number(row.weekday) > 6) || row.localTime !== undefined && (typeof row.localTime !== "string" || !/^([01]\d|2[0-3]):[0-5]\d$/.test(row.localTime))) throw new Error("Scheduled task wall-clock definition is invalid."); return { sourceText: text(row.sourceText, "Schedule source", 1000), timeDescription: text(row.timeDescription, "Schedule time", 500), materialDescription: text(row.materialDescription, "Schedule material", 1000), actionDescription: text(row.actionDescription, "Schedule action", 1000), notificationDescription: text(row.notificationDescription, "Schedule notification", 500), timezone, ...(row.weekday !== undefined ? { weekday: Number(row.weekday) } : {}), ...(typeof row.localTime === "string" ? { localTime: row.localTime } : {}), confirmedAt: iso(row.confirmedAt)! }; }
function listRequest(raw: unknown): { workspacePath?: string; limit: number } { if (!raw || typeof raw !== "object") return { limit: 50 }; const row = raw as Record<string, unknown>; return { ...(row.workspacePath === undefined ? {} : { workspacePath: path(row.workspacePath) }), limit: Math.max(1, Math.min(100, Math.floor(Number(row.limit) || 50))) }; }
function createRequest(raw: unknown): DesktopScheduledTaskCreateRequest { if (!raw || typeof raw !== "object") throw new Error("Scheduled task create request is invalid."); const row = raw as Record<string, unknown>; if (row.kind !== "scheduled" && row.kind !== "monitor") throw new Error("Scheduled task kind is invalid."); if (row.workflowTemplateId !== undefined && (typeof row.workflowTemplateId !== "string" || !/^[a-z][a-z0-9-]{1,63}$/.test(row.workflowTemplateId))) throw new Error("Workflow template id is invalid."); return { kind: row.kind, title: text(row.title, "Scheduled task title"), cadence: cadence(row.cadence), target: text(row.target, "Scheduled task target", 1000), ...(row.workspacePath === undefined ? {} : { workspacePath: path(row.workspacePath) }), ...(typeof row.workflowTemplateId === "string" ? { workflowTemplateId: row.workflowTemplateId } : {}), ...(row.nextRunAt === undefined ? {} : { nextRunAt: iso(row.nextRunAt)! }), ...(typeof row.approvalRequired === "boolean" ? { approvalRequired: row.approvalRequired } : {}), ...(row.verification === undefined ? {} : { verification: text(row.verification, "Scheduled task verification", 2000) }), ...(row.message === undefined ? {} : { message: text(row.message, "Scheduled task message", 2000) }), ...(row.status === undefined ? {} : { status: status(row.status) }), ...(row.userDefinition === undefined ? {} : { userDefinition: definition(row.userDefinition) }) }; }
function updateRequest(raw: unknown): { taskId: string; status: DesktopScheduledTaskStatus; title?: string; cadence?: DesktopScheduledTaskCadence; target?: string; nextRunAt?: string; message?: string; verification?: string; userDefinition?: DesktopScheduledTaskUserDefinition } { if (!raw || typeof raw !== "object") throw new Error("Scheduled task update request is invalid."); const row = raw as Record<string, unknown>; return { taskId: taskIdFrom(raw), status: status(row.status), ...(row.title === undefined ? {} : { title: text(row.title, "Scheduled task title") }), ...(row.cadence === undefined ? {} : { cadence: cadence(row.cadence) }), ...(row.target === undefined ? {} : { target: text(row.target, "Scheduled task target", 1000) }), ...(row.nextRunAt === undefined ? {} : { nextRunAt: row.nextRunAt === "" ? "" : iso(row.nextRunAt)! }), ...(row.message === undefined ? {} : { message: text(row.message, "Scheduled task message", 2000) }), ...(row.verification === undefined ? {} : { verification: text(row.verification, "Scheduled task verification", 2000) }), ...(row.userDefinition === undefined ? {} : { userDefinition: definition(row.userDefinition) }) }; }
function taskIdFrom(raw: unknown): string { const id = raw && typeof raw === "object" ? (raw as { taskId?: unknown }).taskId : undefined; if (typeof id !== "string" || !/^scheduled-task:(?:scheduled|monitor):[A-Za-z0-9-]{36}$/.test(id)) throw new Error("Scheduled task id is invalid."); return id; }
function runRequest(raw: unknown): { workspacePath?: string; now?: string; limit: number } { if (!raw || typeof raw !== "object") return { limit: 50 }; const row = raw as Record<string, unknown>; return { ...(row.workspacePath === undefined ? {} : { workspacePath: path(row.workspacePath) }), ...(row.now === undefined ? {} : { now: iso(row.now)! }), limit: Math.max(1, Math.min(100, Math.floor(Number(row.limit) || 50))) }; }
function nextAt(now: string, value: DesktopScheduledTaskCadence): string | undefined { if (value === "manual") return undefined; const date = new Date(now); date.setTime(date.getTime() + (value === "hourly" ? 3_600_000 : value === "daily" ? 86_400_000 : 604_800_000)); return date.toISOString(); }
function due(task: DesktopScheduledTask, now: Date): boolean { return task.status === "enabled" && task.cadence !== "manual" && Boolean(task.nextRunAt) && Date.parse(task.nextRunAt!) <= now.getTime(); }
function find(store: Store, id: string): { key: string; tasks: DesktopScheduledTask[]; index: number } | null { for (const [key, tasks] of Object.entries(store.workspaces)) { const index = tasks.findIndex((task) => task.id === id); if (index >= 0) return { key, tasks, index }; } return null; }
function key(path?: string): string { return path ? createHash("sha256").update(path.toLowerCase()).digest("hex") : "__global__"; } function compare(a: DesktopScheduledTask, b: DesktopScheduledTask): number { return b.updatedAt.localeCompare(a.updatedAt); } function clone(task: DesktopScheduledTask): DesktopScheduledTask { return structuredClone(task); }
function isTask(value: unknown): value is DesktopScheduledTask { const task = value as DesktopScheduledTask; return Boolean(task && /^scheduled-task:(?:scheduled|monitor):[A-Za-z0-9-]{36}$/.test(task.id) && (task.kind === "scheduled" || task.kind === "monitor") && typeof task.title === "string" && ["enabled", "paused", "blocked"].includes(task.status) && ["manual", "hourly", "daily", "weekly"].includes(task.cadence) && typeof task.target === "string" && typeof task.approvalRequired === "boolean" && typeof task.message === "string" && typeof task.verification === "string"); }
function decodeStore(value: unknown): Store { if (!value || typeof value !== "object" || !("workspaces" in value) || !value.workspaces || typeof value.workspaces !== "object" || Array.isArray(value.workspaces)) throw new Error("Scheduled task store schema is invalid."); const workspaces: Store["workspaces"] = {}; for (const [workspaceKey, values] of Object.entries(value.workspaces)) if (/^(?:[a-f0-9]{64}|__global__)$/.test(workspaceKey) && Array.isArray(values)) { const tasks = values.filter(isTask).slice(0, 100); if (tasks.length) workspaces[workspaceKey] = tasks; } return { schemaVersion: 2, workspaces }; }
export function startScheduledTaskWorker(store: ScheduledTaskStore, runtime: ScheduledTaskRuntime, options: { intervalMs?: number; initialDelayMs?: number; limit?: number } = {}): ScheduledTaskWorker { const intervalMs = Math.max(60_000, Math.min(86_400_000, Math.floor(options.intervalMs ?? 300_000))); const initialDelayMs = Math.max(0, Math.min(300_000, Math.floor(options.initialDelayMs ?? 15_000))); const limit = Math.max(1, Math.min(100, Math.floor(options.limit ?? 50))); let stopped = false, running = false, timer: NodeJS.Timeout | undefined, nextRunAt: string | undefined, lastStartedAt: string | undefined, lastFinishedAt: string | undefined, lastError: string | undefined, lastResult: DesktopScheduledTaskWorkerStatus["lastResult"]; const runOnce = async () => { if (stopped || running) return null; running = true; lastStartedAt = new Date().toISOString(); try { const result = await store.runDue({ limit }, runtime); lastResult = { generatedAt: result.generatedAt, checked: result.checked, triggered: result.triggered, reconnected: result.reconnected, skipped: result.skipped, blocked: result.blocked }; lastError = undefined; return result; } catch (error) { lastError = error instanceof Error ? error.message.slice(0, 1000) : String(error).slice(0, 1000); return null; } finally { running = false; lastFinishedAt = new Date().toISOString(); } }; const schedule = (delay: number) => { if (stopped) return; nextRunAt = new Date(Date.now() + delay).toISOString(); timer = setTimeout(() => void runOnce().finally(() => schedule(intervalMs)), delay); timer.unref(); }; schedule(initialDelayMs); return { runOnce, getStatus: () => ({ enabled: true, running, stopped, intervalMs, initialDelayMs, ...(nextRunAt ? { nextRunAt } : {}), ...(lastStartedAt ? { lastStartedAt } : {}), ...(lastFinishedAt ? { lastFinishedAt } : {}), ...(lastResult ? { lastResult } : {}), ...(lastError ? { lastError } : {}), message: stopped ? "Scheduled task worker is stopped." : running ? "Scheduled task worker is scanning." : "Scheduled task worker is waiting." }), stop: () => { stopped = true; if (timer) clearTimeout(timer); timer = undefined; nextRunAt = undefined; } }; }
const root = join(process.env.DRSAI_HOME?.trim() || join(homedir(), ".drsai"), "desktop"); export const scheduledTaskStore = new ScheduledTaskStore(join(root, "scheduled-tasks.json"));
