import { randomUUID } from "node:crypto";
import { chmod, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import type { DesktopTeamMemoryDeleteResult, DesktopTeamMemoryEntry, DesktopTeamMemoryListRequest } from "../api/desktopApi";
import { replaceFileSafely } from "./atomicFileReplace";
import { requireAuthContext } from "./auth";
import { redactDesktopSecrets } from "./secretRedaction";

type Identity = { userId: string; groups: string[] };
type Store = { schemaVersion: 2; teams: Record<string, DesktopTeamMemoryEntry[]> };
export class TeamMemoryStore {
  #queue = Promise.resolve();
  constructor(readonly filePath: string, readonly identity: () => Promise<Identity>) {}
  list(raw: unknown = {}): Promise<DesktopTeamMemoryEntry[]> { return this.#run(async () => { const request = listRequest(raw); const identity = await this.#identity(); if (request.teamId) authorize(identity.groups, request.teamId); const store = await this.#read(); const query = request.query?.toLocaleLowerCase(); return (request.teamId ? [request.teamId] : identity.groups).flatMap((id) => store.teams[id] ?? []).filter((item) => !query || item.content.toLocaleLowerCase().includes(query)).sort(compare).slice(0, request.limit ?? 20); }); }
  add(raw: unknown): Promise<DesktopTeamMemoryEntry> { return this.#run(async () => { const request = addRequest(raw); const identity = await this.#identity(); authorize(identity.groups, request.teamId); const store = await this.#read(); const now = new Date().toISOString(); const entry: DesktopTeamMemoryEntry = { id: `team-memory-${randomUUID()}`, teamId: request.teamId, content: request.content, createdBy: identity.userId, createdAt: now, updatedAt: now }; store.teams[request.teamId] = [entry, ...(store.teams[request.teamId] ?? [])].sort(compare).slice(0, 200); await this.#write(store); return entry; }); }
  delete(raw: unknown): Promise<DesktopTeamMemoryDeleteResult> { return this.#run(async () => { const request = deleteRequest(raw); const identity = await this.#identity(); authorize(identity.groups, request.teamId); const store = await this.#read(); const entries = store.teams[request.teamId] ?? []; const next = entries.filter((item) => item.id !== request.entryId); if (next.length) store.teams[request.teamId] = next; else delete store.teams[request.teamId]; if (next.length !== entries.length) await this.#write(store); return { teamId: request.teamId, removedCount: entries.length - next.length }; }); }
  async #identity(): Promise<Identity> { const identity = await this.identity(); if (typeof identity.userId !== "string" || !identity.userId || identity.userId.length > 240) throw new Error("Authenticated team identity is invalid."); return { userId: identity.userId, groups: [...new Set(identity.groups.flatMap((value) => { try { return [teamId(value)]; } catch { return []; } }))].slice(0, 200) }; }
  async #read(): Promise<Store> { try { const parsed = JSON.parse(await readFile(this.filePath, "utf8")) as { teams?: unknown }; const teams: Store["teams"] = {}; if (parsed.teams && typeof parsed.teams === "object") for (const [rawTeamId, values] of Object.entries(parsed.teams)) { let id: string; try { id = teamId(rawTeamId); } catch { continue; } if (!Array.isArray(values)) continue; const entries = values.filter(isEntry).filter((item) => item.teamId === id).sort(compare).slice(0, 200); if (entries.length) teams[id] = entries; } return { schemaVersion: 2, teams }; } catch { return { schemaVersion: 2, teams: {} }; } }
  async #write(store: Store): Promise<void> { await mkdir(dirname(this.filePath), { recursive: true }); const temporary = `${this.filePath}.${process.pid}.${randomUUID()}.tmp`; try { await writeFile(temporary, `${JSON.stringify({ ...store, schemaVersion: 2 }, null, 2)}\n`, { encoding: "utf8", mode: 0o600 }); await replaceFileSafely(temporary, this.filePath); await chmod(this.filePath, 0o600).catch(() => undefined); } finally { await rm(temporary, { force: true }); } }
  #run<T>(operation: () => Promise<T>): Promise<T> { const run = this.#queue.catch(() => undefined).then(operation); this.#queue = run.then(() => undefined, () => undefined); return run; }
}
function teamId(value: unknown): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{1,63}$/.test(value)) throw new Error("Team id is invalid."); return value; }
function content(value: unknown): string { if (typeof value !== "string" || !value.trim() || value.length > 4000) throw new Error("Team memory content is invalid."); const result = value.trim(); if (redactDesktopSecrets(result) !== result) throw new Error("Team memory must not contain credentials or secrets."); return result; }
function query(value: unknown): string | undefined { if (value === undefined) return undefined; if (typeof value !== "string" || !value.trim() || value.length > 240 || /[\r\n\0]/.test(value)) throw new Error("Team memory query is invalid."); return value.trim(); }
function limit(value: unknown): number | undefined { return value === undefined ? undefined : Math.max(1, Math.min(100, Math.floor(Number(value) || 20))); }
function listRequest(raw: unknown): DesktopTeamMemoryListRequest { if (!raw || typeof raw !== "object") throw new Error("Team memory list request must be an object."); const value = raw as Record<string, unknown>; return { ...(value.teamId === undefined ? {} : { teamId: teamId(value.teamId) }), ...(limit(value.limit) ? { limit: limit(value.limit) } : {}), ...(query(value.query) ? { query: query(value.query) } : {}) }; }
function addRequest(raw: unknown): { teamId: string; content: string } { if (!raw || typeof raw !== "object") throw new Error("Team memory add request must be an object."); const value = raw as Record<string, unknown>; return { teamId: teamId(value.teamId), content: content(value.content) }; }
function deleteRequest(raw: unknown): { teamId: string; entryId: string } { if (!raw || typeof raw !== "object") throw new Error("Team memory delete request must be an object."); const value = raw as Record<string, unknown>; if (typeof value.entryId !== "string" || !/^team-memory-[A-Za-z0-9-]{36}$/.test(value.entryId)) throw new Error("Team memory entry id is invalid."); return { teamId: teamId(value.teamId), entryId: value.entryId }; }
function authorize(groups: string[], id: string): void { if (!groups.includes(id)) throw new Error("You are not authorized to access this team's memory."); }
function compare(a: DesktopTeamMemoryEntry, b: DesktopTeamMemoryEntry): number { return b.updatedAt.localeCompare(a.updatedAt); }
function isEntry(value: unknown): value is DesktopTeamMemoryEntry { const item = value as DesktopTeamMemoryEntry; return Boolean(item && /^team-memory-[A-Za-z0-9-]{36}$/.test(item.id) && typeof item.teamId === "string" && typeof item.content === "string" && item.content.length <= 4000 && typeof item.createdBy === "string" && typeof item.createdAt === "string" && typeof item.updatedAt === "string"); }
async function currentIdentity(): Promise<Identity> { const auth = await requireAuthContext(); return { userId: auth.userId, groups: auth.session.user?.groups ?? [] }; }
const dataRoot = process.env.DRSAI_HOME?.trim() || join(homedir(), ".drsai"); export const teamMemoryStore = new TeamMemoryStore(join(dataRoot, "desktop", "team-memory.json"), currentIdentity);
export const listTeamMemory = (raw: unknown = {}) => teamMemoryStore.list(raw); export const addTeamMemory = (raw: unknown) => teamMemoryStore.add(raw); export const deleteTeamMemory = (raw: unknown) => teamMemoryStore.delete(raw);
