import { createHash, randomUUID } from "node:crypto";
import { readFile, realpath, stat } from "node:fs/promises";
import { isAbsolute, join, relative } from "node:path";
import { homedir } from "node:os";
import type { DesktopApprovalProposalResult, DesktopWorkflowMarketplaceListResult, DesktopWorkflowMarketplaceSyncResult, DesktopWorkflowRunPrepareRequest, DesktopWorkflowRunPrepareResult, DesktopWorkflowRunStep, DesktopWorkflowTemplate } from "../api/desktopApi";
import { readDurableJson, writeDurableJson } from "./durableJsonStore";
import { CONNECTOR_DIGEST_TEMPLATE, createConnectorDigestSteps } from "./connectorDigestWorkflow";
import { redactDesktopSecrets } from "./secretRedaction";

const BUILT_INS: DesktopWorkflowTemplate[] = [
  { id: "plan-review-fix", name: "Plan, review, fix", category: "review", status: "available", summary: "Plan, review, implement, and verify a scoped change.", trigger: "/plan, /review, /fix", steps: ["Create scoped plan", "Review current diff", "Apply fixes", "Run focused verification"], requiredCapabilities: ["workspace context", "diff visibility", "terminal verification"], approvalRequired: false, verification: "Run the feature-specific verifier.", risk: "low" },
  { id: "test-and-commit", name: "Test and commit", category: "testing", status: "available", summary: "Run tests and prepare a policy-gated commit.", trigger: "/test then /commit", steps: ["Run tests", "Capture evidence", "Review staged diff", "Queue commit approval"], requiredCapabilities: ["terminal", "git diff", "approval center"], approvalRequired: false, verification: "Run approval and execution-policy verification; the /commit step owns the write approval.", risk: "high" },
  { id: "memory-to-skill", name: "Memory to skill", category: "automation", status: "available", summary: "Promote a project lesson into a reviewed local skill.", trigger: "Project memory promotion", steps: ["Save retrospective", "Create draft", "Review SKILL.md", "Install after approval"], requiredCapabilities: ["project memory", "skill drafts", "approval center"], approvalRequired: false, verification: "Run project memory and project skill verification; skill installation owns its approval.", risk: "medium" },
  CONNECTOR_DIGEST_TEMPLATE,
  { id: "external-runtime-reconnect", name: "External runtime reconnect", category: "automation", status: "available", summary: "Recover an external runtime workflow without silent re-execution.", trigger: "Runtime handoff", steps: ["Prepare runtime context", "Reconnect explicitly", "Confirm result"], requiredCapabilities: ["restart recovery", "approval center"], approvalRequired: true, verification: "Run workflow restart recovery verification.", risk: "high" },
];
type ImportStore = { schemaVersion: 2; workspaces: Record<string, { workspacePath: string; sourcePath: string; syncedAt: string; templates: DesktopWorkflowTemplate[] }> };
const MAX_WORKFLOW_MARKETPLACE_STORE_BYTES = 16 * 1024 * 1024;
export class WorkflowMarketplaceStore {
  #queue = Promise.resolve();
  constructor(readonly filePath: string) {}
  list(rawPath?: unknown): Promise<DesktopWorkflowMarketplaceListResult> { return this.#run(async () => { const workspacePath = rawPath === undefined ? undefined : sanitizePath(rawPath); const store = await this.#read(); const imported = workspacePath ? store.workspaces[key(workspacePath)] : undefined; const templates = [...BUILT_INS, ...(imported?.templates ?? [])].map(cloneTemplate); return { templates, generatedAt: new Date().toISOString(), availableCount: templates.filter((item) => item.status === "available").length, approvalRequiredCount: templates.filter((item) => item.approvalRequired).length, syncedCount: imported?.templates.length ?? 0, ...(imported ? { lastSyncedAt: imported.syncedAt } : {}) }; }); }
  sync(raw: unknown): Promise<DesktopWorkflowMarketplaceSyncResult> { return this.#run(async () => { const request = syncRequest(raw); const root = await realpath(request.workspacePath); const sourcePath = await realpath(request.sourcePath ?? join(root, ".drsai", "workflow-marketplace.json")); const rel = relative(root, sourcePath); if (rel.startsWith("..") || isAbsolute(rel)) throw new Error("Workflow marketplace source must stay inside the Workspace."); const info = await stat(sourcePath); if (!info.isFile() || info.size > 256 * 1024) throw new Error("Workflow marketplace source is invalid or too large."); const text = await readFile(sourcePath, "utf8"); if (redactDesktopSecrets(text) !== text) throw new Error("Workflow marketplace source must not contain credentials or secrets."); const parsed = JSON.parse(text) as unknown; const values = Array.isArray(parsed) ? parsed : parsed && typeof parsed === "object" && Array.isArray((parsed as { templates?: unknown }).templates) ? (parsed as { templates: unknown[] }).templates : []; const templates: DesktopWorkflowTemplate[] = []; let ignoredCount = Math.max(0, values.length - 40); for (const value of values.slice(0, 40)) { const item = normalizeTemplate(value); if (item && !BUILT_INS.some((builtIn) => builtIn.id === item.id) && !templates.some((existing) => existing.id === item.id)) templates.push(item); else ignoredCount += 1; } const syncedAt = new Date().toISOString(); const store = await this.#read(); store.workspaces[key(root)] = { workspacePath: root, sourcePath, syncedAt, templates }; await this.#write(store); return { workspacePath: root, sourcePath, syncedAt, importedCount: templates.length, ignoredCount, templates: templates.map(cloneTemplate), message: "Synced reviewed workspace-local workflow templates; no network request was made." }; }); }
  async get(templateId: string, workspacePath?: string): Promise<DesktopWorkflowTemplate | null> { const builtIn = BUILT_INS.find((item) => item.id === templateId); if (builtIn) return cloneTemplate(builtIn); if (!workspacePath) return null; const imported = (await this.#read()).workspaces[key(workspacePath)]?.templates.find((item) => item.id === templateId); return imported ? cloneTemplate(imported) : null; }
  async prepare(raw: unknown, proposal?: DesktopApprovalProposalResult): Promise<DesktopWorkflowRunPrepareResult> { const request = prepareRequest(raw); const template = await this.get(request.templateId, request.workspacePath); const createdAt = new Date().toISOString(); const missingApproval = Boolean(template?.approvalRequired && !proposal); if (!template || template.status !== "available" || missingApproval || proposal?.blocked || proposal?.allowed === false) { const reason = !template ? "Unknown workflow template." : template.status !== "available" ? `Workflow template is ${template.status}.` : missingApproval ? "Workflow approval proposal is required before this recipe can become ready." : proposal?.reason ?? "Workflow blocked."; return { recipe: { id: runRecipeId(request.templateId), templateId: request.templateId, name: template?.name ?? request.templateId, ...(request.workspacePath ? { workspacePath: request.workspacePath } : {}), status: "blocked", createdAt, steps: template ? steps(template) : [], verification: template?.verification ?? "No verifier.", message: reason }, blocked: true, queued: false, reason }; } const queued = Boolean(proposal?.queued && proposal.approval); return { recipe: { id: runRecipeId(template.id), templateId: template.id, name: template.name, ...(request.workspacePath ? { workspacePath: request.workspacePath } : {}), status: queued ? "approval_queued" : "ready", createdAt, steps: steps(template), verification: template.verification, ...(proposal?.approval ? { approvalId: proposal.approval.id } : {}), message: queued ? "Workflow is waiting in Approval Center." : "Workflow recipe is ready." }, ...(proposal?.approval ? { approval: proposal.approval } : {}), blocked: false, queued, reason: proposal?.reason ?? "Workflow recipe prepared." }; }
  async #read(): Promise<ImportStore> { return (await readDurableJson(this.filePath, decodeImportStore, { maxBytes: MAX_WORKFLOW_MARKETPLACE_STORE_BYTES }))?.value ?? { schemaVersion: 2, workspaces: {} }; }
  async #write(store: ImportStore): Promise<void> { await writeDurableJson(this.filePath, { ...store, schemaVersion: 2 }, { maxBytes: MAX_WORKFLOW_MARKETPLACE_STORE_BYTES }); }
  #run<T>(operation: () => Promise<T>): Promise<T> { const run = this.#queue.catch(() => undefined).then(operation); this.#queue = run.then(() => undefined, () => undefined); return run; }
}
function sanitizePath(value: unknown): string { if (typeof value !== "string" || !value.trim() || value.length > 4096 || /[\r\n\0]/.test(value)) throw new Error("Workflow Workspace path is invalid."); return value.trim(); }
function syncRequest(raw: unknown): { workspacePath: string; sourcePath?: string } { if (!raw || typeof raw !== "object") throw new Error("Workflow sync request is invalid."); const value = raw as Record<string, unknown>; return { workspacePath: sanitizePath(value.workspacePath), ...(value.sourcePath === undefined ? {} : { sourcePath: sanitizePath(value.sourcePath) }) }; }
function prepareRequest(raw: unknown): DesktopWorkflowRunPrepareRequest { if (!raw || typeof raw !== "object") throw new Error("Workflow prepare request is invalid."); const value = raw as Record<string, unknown>; if (typeof value.templateId !== "string" || !/^[a-z][a-z0-9-]{1,63}$/.test(value.templateId)) throw new Error("Workflow template id is invalid."); return { templateId: value.templateId, ...(value.workspacePath === undefined ? {} : { workspacePath: sanitizePath(value.workspacePath) }) }; }
function normalizeTemplate(value: unknown): DesktopWorkflowTemplate | null { if (!value || typeof value !== "object") return null; const row = value as Record<string, unknown>; if (typeof row.id !== "string" || !/^[a-z][a-z0-9-]{1,63}$/.test(row.id) || typeof row.name !== "string" || !row.name.trim() || typeof row.summary !== "string" || typeof row.trigger !== "string" || typeof row.verification !== "string" || !Array.isArray(row.steps) || !Array.isArray(row.requiredCapabilities)) return null; const category = ["planning", "review", "testing", "release", "research", "automation"].includes(String(row.category)) ? row.category as DesktopWorkflowTemplate["category"] : null; const status = ["available", "preview", "planned"].includes(String(row.status)) ? row.status as DesktopWorkflowTemplate["status"] : null; const risk = ["low", "medium", "high"].includes(String(row.risk)) ? row.risk as DesktopWorkflowTemplate["risk"] : null; if (!category || !status || !risk || typeof row.approvalRequired !== "boolean") return null; const text = (input: unknown, max = 600) => typeof input === "string" ? input.trim().slice(0, max) : ""; return { id: row.id, name: text(row.name, 120), category, status, summary: text(row.summary), trigger: text(row.trigger), steps: row.steps.map((item) => text(item)).filter(Boolean).slice(0, 12), requiredCapabilities: row.requiredCapabilities.map((item) => text(item, 120)).filter(Boolean).slice(0, 12), approvalRequired: row.approvalRequired, verification: text(row.verification), risk }; }
function decodeImportStore(value: unknown): ImportStore { if (!value || typeof value !== "object" || !("workspaces" in value) || !value.workspaces || typeof value.workspaces !== "object" || Array.isArray(value.workspaces)) throw new Error("Workflow marketplace store schema is invalid."); const workspaces: ImportStore["workspaces"] = {}; for (const [workspaceKey, raw] of Object.entries(value.workspaces)) { if (!/^[a-f0-9]{64}$/.test(workspaceKey) || !raw || typeof raw !== "object") continue; const item = raw as Record<string, unknown>; const templates = Array.isArray(item.templates) ? item.templates.flatMap((candidate) => { const template = normalizeTemplate(candidate); return template ? [template] : []; }).slice(0, 40) : []; if (typeof item.workspacePath === "string" && typeof item.sourcePath === "string" && typeof item.syncedAt === "string") workspaces[workspaceKey] = { workspacePath: item.workspacePath, sourcePath: item.sourcePath, syncedAt: item.syncedAt, templates }; } return { schemaVersion: 2, workspaces }; }
function cloneTemplate(value: DesktopWorkflowTemplate): DesktopWorkflowTemplate { return { ...value, steps: [...value.steps], requiredCapabilities: [...value.requiredCapabilities] }; }
function steps(template: DesktopWorkflowTemplate): DesktopWorkflowRunStep[] {
  if (template.id === "plan-review-fix") {
    return [
      { id: "plan", kind: "chat_command", title: "Plan", detail: template.steps[0], command: "/plan", requiresApproval: false },
      { id: "review", kind: "chat_command", title: "Review", detail: template.steps[1], command: "/review", requiresApproval: false },
      { id: "fix", kind: "chat_command", title: "Fix", detail: template.steps[2], command: "/fix", requiresApproval: false },
      { id: "verify", kind: "terminal_command", title: "Verify", detail: template.steps[3], command: template.verification, requiresApproval: true },
    ];
  }
  if (template.id === "test-and-commit") {
    return [
      { id: "test", kind: "chat_command", title: "Run focused tests", detail: "Use the chat test command to infer and run focused verification.", command: "/test", requiresApproval: false },
      { id: "capture", kind: "manual_review", title: "Capture test evidence", detail: "Confirm the terminal result and relevant logs are recorded for the active workspace.", requiresApproval: false },
      { id: "preflight", kind: "manual_review", title: "Inspect staged diff", detail: "Review staged files, unstaged risk, secrets, and the intended commit message.", requiresApproval: false },
      { id: "commit", kind: "chat_command", title: "Request commit approval", detail: "Replace the placeholder message, then route the commit through Approval Center.", command: "/commit <message>", requiresApproval: false },
    ];
  }
  if (template.id === "memory-to-skill") {
    return [
      { id: "retrospective", kind: "chat_command", title: "Save retrospective", detail: "Replace the placeholder with the durable project lesson to save.", command: "/memory retrospective <lesson>", requiresApproval: false },
      { id: "draft", kind: "manual_review", title: "Create skill draft", detail: "In Skills, create a project skill draft from the reviewed retrospective.", requiresApproval: false },
      { id: "review-skill", kind: "manual_review", title: "Review SKILL.md", detail: "Inspect frontmatter, instructions, scope, and secret scan before installation.", requiresApproval: false },
      { id: "install-skill", kind: "manual_review", title: "Install after approval", detail: "Use the project skill install control and complete its own Approval Center flow.", requiresApproval: false },
    ];
  }
  if (template.id === "external-runtime-reconnect") {
    return [
      { id: "prepare", kind: "chat_command", title: "Prepare runtime context", detail: "Gather provider scope, restart constraints, and expected evidence.", command: "/plan external runtime reconnect", requiresApproval: false },
      { id: "runtime", kind: "external_runtime", title: "Reconnect external runtime", detail: "Reconnect through the provider control plane. The workflow never starts a process automatically.", requiresApproval: true },
      { id: "verify-runtime", kind: "manual_review", title: "Verify runtime result", detail: "Review provider output and background state before completing the workflow.", requiresApproval: false },
    ];
  }
  if (template.id === "connector-digest") {
    return createConnectorDigestSteps();
  }
  return template.steps.map((detail, index) => ({
    id: `step-${index + 1}`,
    kind: "manual_review",
    title: `Step ${index + 1}`,
    detail,
    requiresApproval: false,
  }));
}
function key(value: string): string { return createHash("sha256").update(value.toLowerCase()).digest("hex"); } function runRecipeId(templateId: string): string { return `workflow:${templateId}:${randomUUID()}`; }
const root = join(process.env.DRSAI_HOME?.trim() || join(homedir(), ".drsai"), "desktop"); export const workflowMarketplaceStore = new WorkflowMarketplaceStore(join(root, "workflow-marketplace-imports.json"));
export const listWorkflowMarketplace = (path?: unknown) => workflowMarketplaceStore.list(path); export const syncWorkflowMarketplace = (raw: unknown) => workflowMarketplaceStore.sync(raw); export const getWorkflowTemplate = (id: string, path?: string) => workflowMarketplaceStore.get(id, path); export const createWorkflowRunRecipe = (raw: unknown, proposal?: DesktopApprovalProposalResult) => workflowMarketplaceStore.prepare(raw, proposal);
